### ISSUE TITLE
[ERROR] Failed to close loop

### ISSUE THREAD

**Issue by donlk** [mkazhdan/PoissonRecon#10]
Hello!
I'm using poisson mesh generation on Android devices, and i run into the following issue multiple times:

 Tree set in:       2.9 (s),       0.2 (GB)
Input Points: 86490
Leaves/Nodes: 397769/454593
Memory Usage: 0.195 GB
Constraints set in:       1.3 (s),       0.2 (GB)
Memory Usage: 0.195 GB
Depth[0/8]: 8
Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (0.195 GB)
Depth[1/8]: 64
Evaluated / Got / Solved in:  0.000 /  0.000 /  0.001   (0.195 GB)
1Depth[2/8]: 512
Evaluated / Got / Solved in:  0.000 /  0.001 /  0.002   (0.195 GB)
Depth[3/8]: 4096
Evaluated / Got / Solved in:  0.000 /  0.009 /  0.004   (0.195 GB)
Depth[4/8]: 32768
Evaluated / Got / Solved in:  0.000 /  0.073 /  0.016   (0.195 GB)
Depth[5/8]: 262144
Evaluated / Got / Solved in:  0.000 /  0.620 /  2.431   (0.195 GB)
Depth[6/8]: 54352
1Evaluated / Got / Solved in:  0.000 /  0.304 /  1.266  (0.198 GB)
Depth[7/8]: 100016
Evaluated / Got / Solved in:  0.000 /  0.354 /  0.382   (0.199 GB)
Depth[8/8]: 632
Evaluated / Got / Solved in:  0.000 /  0.030 /  0.835   (0.199 GB)
Linear system solved in:       6.5 (s),       0.2 (GB)
Memory Usage: 0.199 GB
Got average in: 0.086310
Iso-Value: 3.226770e+00
[ERROR] Failed to close loop [8: 144 36 42] | (454465): 756464301900354

(You may notice i altered the printout for memory usage, as the currently used reading of '/proc/self/stat' resulted in gibberish on Android. I'm using 'getrusage' to retrieve the 'ru_maxrss' value for consumption tracking)

What bothers me is that its non-deterministic. The issue comes up around 3 times in 10 run. I tried to resolve the issue with the following:
- Compile the code without funroll-loops and ffast-math
- Turn on lInear interpolaion
-  Turn on double precision

None of the above resolved the error. Do you have any suggestion what went wrong and how to eliminate it?

**Comment by mkazhdan** [comment]
Would you be able to share the point set? That way, I could see if I can reproduce the problem on Windows/Linux and try to debug. 

-- misha

-----Original Message-----

**Comment by donlk** [comment]
Here you go:
https://drive.google.com/file/d/0B963YD5ngbzSazJKYVV1bGhlNUE/view?usp=sharing

**Comment by mkazhdan** [comment]
Thanks.

I’m having trouble reproducing the problem.

When I run under Windows/Linux I get the output below.

What’s strange is that things look quite different even after the initial tree construction phase. (e.g. My run has ~800,000 nodes while yours had ~450,000).

The only parameters I used were “--in teddy_cloud.ply --double --linearFit –verbose”. Were these the ones you used?

 

-- Misha

 

C:\>PoissonRecon.exe --in teddy_cloud.ply --double --linearFit --verbose

Running Screened Poisson Reconstruction (Version 8.0)

        --in teddy_cloud.ply

        --verbose

        --double

        --linearFit

#             Tree set in:       1.7 (s),      57.1 (MB)

Input Points: 148245

Leaves/Nodes: 704754/805433

Memory Usage: 64.066 MB

#      Constraints set in:       0.5 (s),      81.2 (MB)

Memory Usage: 55.555 MB

Depth[0/8]: 8

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (65.301 MB)

Depth[1/8]: 64

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.001   (65.301 MB)

Depth[2/8]: 512

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.002   (65.301 MB)

Depth[3/8]: 4096

        Evaluated / Got / Solved in:  0.000 /  0.004 /  0.003   (65.750 MB)

Depth[4/8]: 32768

        Evaluated / Got / Solved in:  0.000 /  0.021 /  0.009   (67.691 MB)

Depth[5/8]: 262144

        Evaluated / Got / Solved in:  0.002 /  0.134 /  0.049   (66.418 MB)

Depth[6/8]: 41608

        Evaluated / Got / Solved in:  0.001 /  0.064 /  0.065   (70.969 MB)

Depth[7/8]: 130008

        Evaluated / Got / Solved in:  0.004 /  0.172 /  0.179   (67.652 MB)

Depth[8/8]: 334224

        Evaluated / Got / Solved in:  0.005 /  0.368 /  0.370   (80.984 MB)

# Linear system solved in:       1.5 (s),      81.0 (MB)

Memory Usage: 61.793 MB

Got average in: 0.050000

Iso-Value: 4.973178e-001

**Comment by donlk** [comment]
Apologies, forgot to list my parameter values:

Depth.value = 9;
SamplesPerNode.value = 10;
PointWeight.value = 0;
In.set = true;
Out.set = true;
Density.set = true;
Verbose.set = true;
ASCII.set = false;
NoComments.set = true;
Color.set = false;
LinearFit.set = true;

**Comment by mkazhdan** [comment]
I see.

My output for these parameters are below.

For some reason, I’m still getting more nodes than you. I also appear to get reconstructions going out to depth 9.

And finally, for some reason I appear to be reading in more points than you (148K vs. 86K).

 

-- Misha

 

C:\ >PoissonRecon.exe --in \datateddy_cloud.ply --out foo.ply --depth 9 --verbose --samplesPerNode 10 --pointWeight 0 --density --linearFit --double

Running Screened Poisson Reconstruction (Version 8.0)

        --in teddy_cloud.ply

        --depth 9

        --out foo.ply

        --verbose

        --double

        --samplesPerNode 10.000000

        --pointWeight 0.000000

        --density

        --linearFit

#             Tree set in:       1.7 (s),      33.2 (MB)

Input Points: 148245

Leaves/Nodes: 511603/584689

Memory Usage: 41.016 MB

#      Constraints set in:       0.4 (s),      58.7 (MB)

Memory Usage: 38.578 MB

Depth[0/9]: 8

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (47.438 MB)

Depth[1/9]: 64

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (47.438 MB)

Depth[2/9]: 512

        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.002   (47.441 MB)

Depth[3/9]: 4096

        Evaluated / Got / Solved in:  0.000 /  0.003 /  0.002   (47.926 MB)

Depth[4/9]: 32768

        Evaluated / Got / Solved in:  0.000 /  0.019 /  0.005   (48.145 MB)

Depth[5/9]: 262144

        Evaluated / Got / Solved in:  0.000 /  0.122 /  0.029   (49.480 MB)

Depth[6/9]: 30832

        Evaluated / Got / Solved in:  0.000 /  0.035 /  0.033   (55.898 MB)

Depth[7/9]: 81624

        Evaluated / Got / Solved in:  0.000 /  0.089 /  0.090   (55.797 MB)

Depth[8/9]: 153592

        Evaluated / Got / Solved in:  0.000 /  0.143 /  0.162   (51.816 MB)

Depth[9/9]: 19048

        Evaluated / Got / Solved in:  0.000 /  0.039 /  0.105   (53.102 MB)

# Linear system solved in:       1.0 (s),      55.9 (MB)

Memory Usage: 42.090 MB

Got average in: 0.040000

Iso-Value: 2.152141e+000

#        Got triangles in:       0.4 (s),      49.9 (MB)

#             Total Solve:       3.5 (s),      58.7 (MB)

Vertices / Polygons: 42757 / 85332

**Comment by donlk** [comment]
Yes you are right, t think i pasted the wrong log output.
Here is the correct one, which has a lot more correlation with yours, though it fails just the same:

> Tree set in:       4.8 (s),       0.2 (GB)
> Input Points: 148245
> Leaves/Nodes: 511603/584689
> Memory Usage: 0.193 GB
> Constraints set in:       1.7 (s),       0.2 (GB)
> Memory Usage: 0.193 GB
> Depth[0/9]: 8
> Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000	(0.193 GB)
> Depth[1/9]: 64
> Evaluated / Got / Solved in:  0.000 /  0.000 /  0.002	(0.193 GB)
> Depth[2/9]: 512
> Evaluated / Got / Solved in:  0.000 /  0.001 /  0.003	(0.193 GB)
> Depth[3/9]: 4096
> Evaluated / Got / Solved in:  0.000 /  0.011 /  0.006	(0.193 GB)
> Depth[4/9]: 32768
> Evaluated / Got / Solved in:  0.000 /  0.100 /  0.019	(0.193 GB)
> Depth[5/9]: 262144
> Evaluated / Got / Solved in:  0.000 /  0.720 /  0.878	(0.193 GB)
> Depth[6/9]: 30832
> Evaluated / Got / Solved in:  0.000 /  0.168 /  0.187	(0.193 GB)
> Depth[7/9]: 81624
> Evaluated / Got / Solved in:  0.000 /  0.432 /  0.528	(0.193 GB)
> Depth[8/9]: 153592
> Evaluated / Got / Solved in:  0.000 /  0.731 /  0.939	(0.197 GB)
> Depth[9/9]: 19048
> Evaluated / Got / Solved in:  0.000 /  0.134 /  0.525	(0.197 GB)
> Linear system solved in:       5.6 (s),       0.2 (GB)
> Memory Usage: 0.197 GB
> Got average in: 0.187036
> Iso-Value: 2.152256e+00
> [ERROR] Failed to close loop [9: 394 252 256] | (573717): 4521193927345706

**Comment by mkazhdan** [comment]
I see.

That does match the output I am seeing under Linux, though the Linux reconstruction doesn’t run into the same trouble. (Even when I remove the unroll loops and fast math flags.)

I am not that familiar with the C compiler for Android, so I am not sure if that’s the issue.

 

It could be that there’s an issue with OpenMP. Do things behave better if you force the number of threads to 1?

Also, can you add the flag “--voxel teddy.raw” to your command line and share the teddy.raw file? This samples the implicit function on a regular grid prior to extracting the iso-surface, and would let me know if the problem is specifically with the iso-surface extraction or if something bad happens earlier on.

 

-- Misha

**Comment by donlk** [comment]
Hey, settings forcing the thread count to 1 worked, no more crashes. If i have the time, i try to investigate it further and send you the voxel of a bad run.
