### ISSUE TITLE
error when thread number is more than 26

### ISSUE THREAD

**Issue by DamonsJ** [mkazhdan/PoissonRecon#101]
In the file Geometry.h line 507, there is a fuction named _mktemp in windows platform.
From the descrition of this documention : https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/mktemp-wmktemp?view=vs-2019
_mktemp will return 26 temp filname at most . so if thread number is more than 26, this place will be corrupted.

**Comment by mkazhdan** [comment]
Have you run into a problem with this? My understanding was that it creates up to 26 file-names _per thread_, so it shouldn't matter how many thread there are.

**Comment by DamonsJ** [comment]
yes, my computer have 40 cores, so it corrupt every time.
if you call _mktemp  more than 26 times , _mktemp returns an empty string : ""
so it will fail at : _fp = fopen( _fileName , "w+b" ); 
then it will corrupt at : if( !_fp ) ERROR_OUT( "Failed to open file: " , _fileName );

**Comment by mkazhdan** [comment]
Thanks. I'll try to take a look. What confuses me is that the standard says "this value is a unique number identifying the calling process, or in multithreaded programs, the calling thread." So I figured that as long as no individual thread opens more than 26 files things should be ok. Regardless of how many threads are running.

**Comment by mkazhdan** [comment]
OK. I've posted new code that should address the problem. Please let me know if it does/doesn't work.

**Comment by DamonsJ** [comment]
Thanks a lot , I believe it will work and I will try later.
If it does/doesn't work, I will let you know

**Comment by DamonsJ** [comment]
It works for me now, thanks again!

**Comment by mkazhdan** [comment]
The call to mktemp has been removed in Version 16.09.
Hopefully that fixes this problem without introducing others.
