### ISSUE TITLE
a little confusion about poisson reconstruction

### ISSUE THREAD

**Issue by DamonsJ** [mkazhdan/PoissonRecon#103]
I wonder is poisson reconstruction method suitable for construction of  terrain points.
I mean I want to build mesh for terrain point cloud like this :

![terrain-points-set](https://user-images.githubusercontent.com/28893028/56174958-a1706700-6027-11e9-83df-10f800668f51.png)

Actually， the point cloud is more like 2.5D , not 3D, so I want to know is poisson reconstruction method suitable for this sutuation? I have tried some real 3D point clouds , this method generate very good result.

here is what I get using  command line :  --in "a.ply" --out "b.ply" --density --scale 1.001 --samplesPerNode 3 :
![image](https://user-images.githubusercontent.com/28893028/56175049-f57b4b80-6027-11e9-89b2-7f77912dcb77.png)

I want to get result which has right boundary like this:
![image](https://user-images.githubusercontent.com/28893028/56175155-6a4e8580-6028-11e9-82db-ef978403a529.png)

I know I can use  surfaceTrimmer to trim it with density, but in practice, How can I know the right density to trim it?

**Comment by mkazhdan** [comment]
Typically I would use a relatively low density, like 4 or 5, though I don't have hard and fast rules for this. Basically, you can think of the density as the depth, so that if you specify a density d you mean to throw out triangles whose width is bigger than 1/2^d the width of the working volume.

**Comment by DamonsJ** [comment]
> Typically I would use a relatively low density, like 4 or 5, though I don't have hard and fast rules for this. Basically, you can think of the density as the depth, so that if you specify a density d you mean to throw out triangles whose width is bigger than 1/2^d the width of the working volume


Thanks a lot!
so, it means typically , the poisson reconstruction method is not suitable for 2.5D point cloud?
If I want to use it, there is no perfect way to get the right density?

**Comment by mkazhdan** [comment]
I'm not sure. Why would that imply that it doesn't work for a 2.5D point cloud? (I'm assuming you still have normals.)

**Comment by DamonsJ** [comment]
I don't know , my point cloud have normals , may be the parameters I used is not proper?
the point cloud I have used is attached in the attachment.

[terrain-point-set.zip](https://github.com/mkazhdan/PoissonRecon/files/3082771/terrain-point-set.zip)

I mean I get the result but I do not know how to trim it in practice, I can not select the right density for every point cloud

**Comment by mkazhdan** [comment]
What happens when you run the reconstruction with a depth value of 10 and use a trim value of 7? (That is, what about the trimmed results would you like to improve?)

**Comment by DamonsJ** [comment]
no problem, the result is very good.
but what I want to know is how do you know trim value is 7 ? and if I use another point clouds, this value will be different?

**Comment by mkazhdan** [comment]
I found that values between 5 and 7 all worked pretty well. I think that, in general, 6 should work pretty well if you're pointsets have (roughly) the same density as the one you sent.

**Comment by DamonsJ** [comment]
Thanks a lot , I think I can understand now
