### ISSUE TITLE
Throwing std::bad_alloc when I increase depth

### ISSUE THREAD

**Issue by johnrachwan123** [mkazhdan/PoissonRecon#105]
Hello, first I would like to thank you for your great tool. 
I have been running into an issue with very large point clouds. First I would like to note that i enabled the BIG_DATA variable in the code.
When i run on depths 10-12 it ran successfully. But when I increased to 20 (i want it to get as much detail as possible, that is why i increased the upper bound to a high amount) i get the following error: 

root@139ca55cdd43:~/PoissonRecon/Bin/Linux# ./PoissonRecon --in /Data/brazil.ply --out /Data/out.ply --depth 20 --pointWeight 0 --scale 0.4 --colors --inCore --performance --verbose
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 11.01) **
*************************************************************
*************************************************************
Running with 40 threads
        --in /Data/brazil.ply
        --depth 20
        --out /Data/out.ply
        --scale 0.400000
        --verbose
        --pointWeight 0.000000
        --colors
        --performance
        --inCore
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Do you have any idea what could cause such an error?

I would like to also add that before I added the --scale attribute I was getting an Iso-Value containing NaN similar to issue #102 . Same as him this NaN does not happen if choose a low depth <10, but happens for depths >10

It would be also interesting to note that I built PoissonRecon on a docker, and I am executing it from the docker

Thank you in advance for your help!

**Comment by johnrachwan123** [comment]
It would be also interesting to note that I built PoissonRecon on a docker, and I am executing it from the docker

**Comment by mkazhdan** [comment]
Wow. I've never seen a depth 20 run. How big is your point-set? And, how much memory do you have on your machine?

**Comment by johnrachwan123** [comment]
My point set is 10 GB almost half a trillion points. By memory you mean RAM?

**Comment by johnrachwan123** [comment]
Storage wise its almost unlimited you could say. RAM wise its 256 GB.

**Comment by mkazhdan** [comment]
Wow. That is big. For 500 billion points at depth 20, 256 GB may not be enough. For example, on a 2 billions point set at depth 16, I ended up using 536 GB of RAM.

**Comment by mkazhdan** [comment]
By the way, I'm assuming that you mean half a billion points.
10GB / (6*4bytes) = 416 M

**Comment by johnrachwan123** [comment]
I am sorry it was a mistake, I meant half a billion points. 370,038,992 to be exact

**Comment by mkazhdan** [comment]
Can you post the data on your website and send me a link (e.g. by email if you don't want the URL publicly available)? My email is misha@cs.jhu.edu

**Comment by johnrachwan123** [comment]
I just ran everything on depth 14 and I still got the same error. It is very strange.

root@139ca55cdd43:~/PoissonRecon/Bin/Linux# ./PoissonRecon --in /Data/brazil.ply --out /Data/out.ply --depth 14 --pointWeight 0 --scale 0.4 --colors  --performance --verbose
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 11.01) **
*************************************************************
*************************************************************
Running with 40 threads
        --in /Data/brazil.ply
        --depth 14
        --out /Data/out.ply
        --scale 0.400000
        --verbose
        --pointWeight 0.000000
        --colors
        --performance
[WARNING] Src/FEMTree.Initialize.inl (Line 166)
          Initialize
          Found out-of-bound points: 226814030
Input Points / Samples: 143224962 / 138370604
# Read input into tree:     345.2 (s),   82311.5 (MB) /   82311.5 (MB) /       0.0 (MB)
#   Got kernel density:     219.0 (s),  135903.2 (MB) /  135903.2 (MB) /       0.4 (MB)
#     Got normal field:     433.6 (s),  219023.1 (MB) /  219023.1 (MB) /       0.0 (MB)
Point weight / Estimated Area: 8.79261e-08 / 12.5932
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

I also just sent the data set to your email. If you didn't receive it or if there's any problem, please tell me.
Thanks Again!

**Comment by mkazhdan** [comment]
Note that right before the code crashes, you have:
"Got normal field: 433.6 (s), 219023.1 (MB) / 219023.1 (MB) / 0.0 (MB)"
So you're already using 219GB of RAM and likely you go over the 256GB limit in the next stage of processing.

**Comment by johnrachwan123** [comment]
Yes I see. Thank you for pointing that out. Did you receive the data set?

**Comment by mkazhdan** [comment]
Didn't receive an email yet.

**Comment by johnrachwan123** [comment]
That's odd, I sent it using an online service. I will have to send it Tuesday when I get back to my office. Thank you again for everything and sorry for the delay till Tuesday.

**Comment by johnrachwan123** [comment]
If I would like to obtain a reconstruction at octree depths >=14, is the only solution to upgrade my memory ?

**Comment by mkazhdan** [comment]
We did work on out-of-core implementation years ago. Source code and executables are available at:
http://www.cs.jhu.edu/~misha/Code/StreamingRecon_918.zip
This code has not been maintained, but last I checked it still worked.

**Comment by johnrachwan123** [comment]
Yes i know of all of your work, I am actually a big fan. I have already tried the out-of-core implementation. But I my problem is I need the colors in my point cloud to be extrapolated to the resulting mesh since I need visual clarity to label the mesh for object detection and that is why unfortunately i could not use it.

**Comment by mkazhdan** [comment]
Ah. I see. Then I'm afraid the only other option that comes to mind is "more memory". Which is not a great option, I understand.

**Comment by johnrachwan123** [comment]
Yes exactly. I guess one possible solution would be to split the point cloud into two or more pieces and run poisson with depth 13 on them. I would assume that would much higher accuracy than a single octree 13 run on all of the data set.

**Comment by mkazhdan** [comment]
Yep. Though then you're stuck with the question of "how do I stitch the two halves together?"
It's also possible that once the NaN problem is resolved, you can use the default scale and, possibly, then things will fit into memory. It depends on what it's a point-set of.

**Comment by mkazhdan** [comment]
I just got something in my spam that looks like it could be it. Can you tell me whom I should be expecting an email from?

**Comment by johnrachwan123** [comment]
The website i used is https://www.sendtransfer.com/. I placed your email, and you should recieve it from my  email "johnrachwan@gmail.com". In the body of the email there should be a small text of me telling you that this is the data set you requested. The file's name is brazil.ply .

**Comment by johnrachwan123** [comment]
Did you recieve the data set, or should i still send it on Tuesday?

**Comment by mkazhdan** [comment]
You should still send it. The spam turned out to be spam.

**Comment by johnrachwan123** [comment]
I just shared the file with you. Did you receive it?

**Comment by johnrachwan123** [comment]
You can recreate it using this script

root@c3c6fa5fe7d0:~/PoissonRecon/Bin/Linux# ./PoissonRecon --in /Data/brazil.ply                                                                                                                                                                                                                                              --out /Data/out.ply --depth 13 --pointWeight 0 --performance --verbose
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 11.01) **
*************************************************************
*************************************************************
Running with 40 threads
        --in /Data/brazil.ply
        --depth 13
        --out /Data/out.ply
        --verbose
        --pointWeight 0.000000
        --performance
Input Points / Samples: 370038992 / 106183496
# Read input into tree:     870.9 (s),   20210.3 (MB) /   20210.3 (MB) /       0                                                                                                                                                                                                                                             .0 (MB)
#   Got kernel density:      40.9 (s),   29059.5 (MB) /   29059.5 (MB) /       0                                                                                                                                                                                                                                             .5 (MB)
#     Got normal field:     197.5 (s),   72907.1 (MB) /   72907.1 (MB) /       0.0 (MB)
Point weight / Estimated Area: nan / nan
#       Finalized tree:     232.4 (s),  132700.3 (MB) /  132700.3 (MB) /       0.0 (MB)
#  Set FEM constraints:     144.9 (s),   98744.9 (MB) /  132700.3 (MB) /       0.0 (MB)
Leaf Nodes / Active Nodes / Ghost Nodes: 794126005 / 896009632 / 11562945
Memory Usage: 90050.055 MB
Cycle[0] Depth[ 0/13]:  Updated constraints / Got system / Solved in:  0.001 /  0.001 /  0.000  (94923.812 MB)  Nodes: 8
Cycle[0] Depth[ 1/13]:  Updated constraints / Got system / Solved in:  0.008 /  0.000 /  0.000  (94923.812 MB)  Nodes: 27
Cycle[0] Depth[ 2/13]:  Updated constraints / Got system / Solved in:  0.001 /  0.001 /  0.000  (94923.812 MB)  Nodes: 125
Cycle[0] Depth[ 3/13]:  Updated constraints / Got system / Solved in:  0.001 /  0.010 /  0.001  (94923.812 MB)  Nodes: 729
Cycle[0] Depth[ 4/13]:  Updated constraints / Got system / Solved in:  0.002 /  0.018 /  0.003  (94923.812 MB)  Nodes: 4913
Cycle[0] Depth[ 5/13]:  Updated constraints / Got system / Solved in:  0.002 /  0.031 /  0.025  (94923.812 MB)  Nodes: 35937
Cycle[0] Depth[ 6/13]:  Updated constraints / Got system / Solved in:  0.002 /  0.011 /  0.018  (94923.812 MB)  Nodes: 48624
Cycle[0] Depth[ 7/13]:  Updated constraints / Got system / Solved in:  0.003 /  0.018 /  0.032  (94923.812 MB)  Nodes: 210152
Cycle[0] Depth[ 8/13]:  Updated constraints / Got system / Solved in:  0.009 /  0.061 /  0.106  (94923.812 MB)  Nodes: 1102688
Cycle[0] Depth[ 9/13]:  Updated constraints / Got system / Solved in:  0.033 /  0.242 /  0.498  (94923.812 MB)  Nodes: 5769816
Cycle[0] Depth[10/13]:  Updated constraints / Got system / Solved in:  0.163 /  0.931 /  2.930  (94923.812 MB)  Nodes: 24625472
Cycle[0] Depth[11/13]:  Updated constraints / Got system / Solved in:  0.518 /  3.447 / 13.008  (96546.598 MB)  Nodes: 89470752
Cycle[0] Depth[12/13]:  Updated constraints / Got system / Solved in:  1.497 /  9.656 / 35.264  (103572.477 MB) Nodes: 260320352
Cycle[0] Depth[13/13]:  Updated constraints / Got system / Solved in:  0.025 / 20.084 / 67.510  (114165.293 MB) Nodes: 514393736
# Linear system solved:     302.5 (s),  114165.3 (MB) /  132700.3 (MB) /       0.0 (MB)
Got average:       5.1 (s),   87619.8 (MB) /  132700.3 (MB) /       0.9 (MB)
Iso-Value: -nan = -nan / 3.70039e+08
Vertices / Polygons: 0 / 0
Corners / Vertices / Edges / Surface / Set Table / Copy Finer: 65.8 / 12.5 / 31.6 / 18.0 / 111.7 / 11.1 (s)
#        Got triangles:     520.2 (s),  118391.1 (MB) /  132700.3 (MB) /       0.0 (MB)
#          Total Solve:    2344.7 (s),  132700.3 (MB)
Time (Wall/CPU): 2358.04 / 26664.88
Peak Memory (MB): 132700

**Comment by mkazhdan** [comment]
Got it. And at depth 13 you don't get the NaN problem, right?

**Comment by johnrachwan123** [comment]
You do get the problem at depth 13, if you take a look at my previous comment:
Iso-Value: -nan = -nan / 3.70039e+08

**Comment by mkazhdan** [comment]
But not depth 12, right? (I ask because my machine only has 16GB of RAM so at depth 13 I will run out of memory before I get to the error.)

**Comment by johnrachwan123** [comment]
at depth 12 also it gives NaN

**Comment by johnrachwan123** [comment]
it also happens if you set depth to 11

root@77de33e635d8:~/PoissonRecon/Bin/Linux# ./PoissonRecon --in /Data/brazil.ply --out out.ply --depth 11 --pointWeight 0 --colors --performance --verbose *************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 11.01) **
*************************************************************
*************************************************************
Running with 40 threads
        --in /Data/brazil.ply
        --depth 11
        --out out.ply
        --verbose
        --pointWeight 0.000000
        --colors
        --performance
Input Points / Samples: 370038992 / 8819388
Read input into tree:     271.9 (s),    1594.3 (MB) /    1594.3 (MB) /       0.0 (MB)
Got kernel density:       3.1 (s),    2188.1 (MB) /    2188.1 (MB) /       0.5 (MB)
 Got normal field:      15.0 (s),    5696.3 (MB) /    5696.3 (MB) /       0.0 (MB)
Point weight / Estimated Area: nan / nan
 Finalized tree:      16.3 (s),    9871.7 (MB) /    9871.7 (MB) /       0.0 (MB)
Set FEM constraints:       9.9 (s),    7368.0 (MB) /    9871.7 (MB) /       0.0 (MB)
Leaf Nodes / Active Nodes / Ghost Nodes: 58698697 / 66943088 / 141137
Memory Usage: 6985.289 MB
Cycle[0] Depth[ 0/11]:  Updated constraints / Got system / Solved in:  0.000 /  0.000 /  0.000  (6985.289 MB)   Nodes: 8
Cycle[0] Depth[ 1/11]:  Updated constraints / Got system / Solved in:  0.014 /  0.000 /  0.000  (6985.289 MB)   Nodes: 27
Cycle[0] Depth[ 2/11]:  Updated constraints / Got system / Solved in:  0.012 /  0.067 /  0.039  (6985.289 MB)   Nodes: 125
Cycle[0] Depth[ 3/11]:  Updated constraints / Got system / Solved in:  0.011 /  0.120 /  0.059  (6985.289 MB)   Nodes: 729
Cycle[0] Depth[ 4/11]:  Updated constraints / Got system / Solved in:  0.010 /  0.195 /  0.108  (6985.289 MB)   Nodes: 4913
Cycle[0] Depth[ 5/11]:  Updated constraints / Got system / Solved in:  0.012 /  0.310 /  4.899  (6985.289 MB)   Nodes: 35937
Cycle[0] Depth[ 6/11]:  Updated constraints / Got system / Solved in:  0.009 /  0.167 /  2.619  (6985.289 MB)   Nodes: 48304
Cycle[0] Depth[ 7/11]:  Updated constraints / Got system / Solved in:  0.010 /  0.240 /  3.866  (6985.289 MB)   Nodes: 207464
Cycle[0] Depth[ 8/11]:  Updated constraints / Got system / Solved in:  0.015 /  0.425 /  5.895  (7005.945 MB)   Nodes: 1081104
Cycle[0] Depth[ 9/11]:  Updated constraints / Got system / Solved in:  0.036 /  0.851 / 10.594  (7191.828 MB)   Nodes: 5270520
Cycle[0] Depth[10/11]:  Updated constraints / Got system / Solved in:  0.138 /  1.882 / 20.484  (7727.531 MB)   Nodes: 19179264
Cycle[0] Depth[11/11]:  Updated constraints / Got system / Solved in:  0.006 /  3.700 / 39.190  (8796.133 MB)   Nodes: 41088392
Linear system solved:     105.1 (s),    8796.1 (MB) /    9871.7 (MB) /       0.0 (MB)
Got average:       0.5 (s),    6730.8 (MB) /    9871.7 (MB) /       0.1 (MB)
Iso-Value: -nan = -nan / 3.70039e+08

**Comment by mkazhdan** [comment]
Got the file. And I'm seeing the same NaN error. I'll see if I can track down the why. Thanks.

**Comment by johnrachwan123** [comment]
Great. Thank You.

**Comment by mkazhdan** [comment]
OK. I think I've tracked down the issue. This seems to be a numerical precision issue resulting from the fact that the code is using single-precision floating point values _and_ there is an octree node that has too many sample points falling into it.

The simplest fix is change the code in PoissonRecon.cpp so that the flag "USE_DOUBLE" is defined. This resolves the problem by switching to double-precision floating point values, but comes at the cost of additional memory and time. I'm working on a less drastic fix.

Alternatively, I have just pushed code that does some error handling to catch (and correct) the situation when multiple samples fall into the same node.

**Comment by mkazhdan** [comment]
Two small notes:
If you want a sharper reconstruction, you should use the default value for point weight. (Setting it to zero makes the reconstruction smoother.)

**Comment by johnrachwan123** [comment]
Great. Thank you!

Concerning your second point. You mean that the data set itself is corrupted in some way?

**Comment by mkazhdan** [comment]
I'm not sure. It could be that your samples are highly non-uniform (e.g. the whole scene was acquired with a relatively low-res scanner but then some individual locations were scanned at a very high resolution.) I'm just not sure. It may be worth inspecting the data. 

I should add that nothing jumped out at me as "broken" when I looked at the reconstruction.

**Comment by johnrachwan123** [comment]
Okay I will most definitely look into the data. 
One last question, when do you recommend enabling the variable BIG_DATA ( I mean how many samples would require its use) ?

**Comment by mkazhdan** [comment]
That's a tricky question as it's a combination of factors including the number of points and the depth. Basically, it should be enabled when the expected number of nodes in the tree is bigger that what can be represented by a 32-bit integer. (i.e. a couple billion nodes.)

I would say you probably won't need it if you are reconstructing at depth 13 or below.

**Comment by johnrachwan123** [comment]
Yes since 2^32  is approximately 4.29 billion and 4^16 is the same. I would say depth 16 is the maximum it could handle without switching to long long.

**Comment by johnrachwan123** [comment]
One more thing if I turn off BIG_DATA i get a segfault core dumped on depth 13.

**Comment by mkazhdan** [comment]
That could be. If you run with BIG_DATA defined, how many octree nodes does it say you're using?

**Comment by johnrachwan123** [comment]
Leaf Nodes / Active Nodes / Ghost Nodes: 794126103 / 896009920 / 11562769

**Comment by jcmadsen** [comment]
This fixes my problem as well, using version 11.02. It's it 30+ million point cloud that's a few hundred meters on a side, and getting past depth 11 was previously very difficult.

Only change made was in the PoissonRecon header: 
```
#define USE_DOUBLE
```
