### ISSUE TITLE
Bogus foundBadNode?

### ISSUE THREAD

**Issue by cdcseacave** [mkazhdan/PoissonRecon#109]
I am probably wrong as I did not go deep in understanding the code, but to me it seems that the code here has a bug: https://github.com/mkazhdan/PoissonRecon/blob/master/Src/FEMTree.Initialize.inl#L105 as no matter what the data is, `foundBadNode` is always set to `true`. In my opinion there should be:
```
			bool foundBadNode = false;
			for( int d=0 ; d<Dim ; d++ )
			{
				if     ( p[d]<start[d]       ) { p[d] = start[d]; foundBadNode = true; }
				else if( p[d]>start[d]+width ) { p[d] = start[d]+width; foundBadNode = true; }
			}
```

**Comment by mkazhdan** [comment]
Thanks. It's been fixed.
