### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by puffosauro** [mkazhdan/PoissonRecon#11]
Hi.
I'm trying to run the last version (binary distibution of v8, 64 bit) on a Windows 10 system. I have installed the VS2013 redist package. The application crashes on startup (even with no arguments).
Instead the 32 bit version seems to work, if I run it with no arguments it prints the usage.
There are some dependencies needed?

**Comment by mkazhdan** [comment]
There shouldn’t be any other dependencies.

Can you confirm that you are running a 64-bit OS? (http://www.tenforums.com/tutorials/4399-system-type-32-bit-x86-64-bit-x64-windows-10-a.html)

 

-- Misha

**Comment by puffosauro** [comment]
Yes I have a 64 bit OS. I can run all version up to 5.71. The versions 6 and next crash in my system.
I have also tried on another PC with Windows 7 but I can't run it.
If I'm not wrong, I remember that in a old PC with Windows Vista there was not problems (but now I can't try because that PC is dead :( )
Some time ago I needed the v 7 (because of the color extrapolation) and I have built it with my Visual Studio (2008 Standard Edition), and the executable works, but without OpenMP (because OpenMP is not supported in VS2008 SE).

**Comment by mkazhdan** [comment]
It might be the case that the OpenMP is still causing trouble.

Do you get an error message when it crashes? Have you been able to run other stuff that requires OpenMP?

 

If you do have some version of Visual Studios, you could just try disabling OpenMP.

To do this, go to

Properties -> C/C++ -> Language
and make sure that “Open MP Support” is not enabled.

 

 

-- Misha

**Comment by puffosauro** [comment]
Unfortunately I don't get any error message.
I don't know about other stuff, but I can run PoissonRecon 5.71 that requires OpenMP (I think! I read something about OpenMP in the changelog of 5.7 version). I don't know what is changed between v 5.71 and v 6.
I could build using VS2008 SE (as the v 7), but I think that OpenMP make it faster. What a pity!

**Comment by mkazhdan** [comment]
Hi,

 

It’s strange that there are no messages. Not even one about missing .dlls.

You could try running “depends.exe” (you will need to download it) to check for missing dependencies.

It’s likely that it’s a problem with OpenMP, so recompiling w/o it should work, though that will also make the application run slower. You could try and see if you can download the vcomp.dll directly and place it in the directory with the executable.

 

-- Misha

**Comment by giancan** [comment]
Hi @mkazhdan ,
I know it is an old post but I just tried to download the v8 executable and it crashes as soon as I run it without explanation. SurfaceTrimmer seems to work fine
Thanks

**Comment by mkazhdan** [comment]
Strange.

I am assuming you are running on Windows (10?).

It could be the case that you need to download the Microsoft redistributable package (https://www.microsoft.com/en-us/download/details.aspx?id=40784).

 

-- Misha

**Comment by giancan** [comment]
I had it installed and I tried with a repair. Nothing seems to have changed.
And yes, I am on windows (but 7, not 10).
Anything else I can try?

**Comment by nmm02003** [comment]
Hi, I'm having the same problem. Trying to run 64 bit executable (tried both version 8 and 9) on Windows 10 64 bit. Poissonrecon.exe crashes immediately without any error message.  I have the redistributable packages installed fpr 2010-2015. Are there any other dependencies?

**Comment by mkazhdan** [comment]
I am assuming you are running from a command prompt. Is there an error message?

It's also possibly that you are running on older hardware. The code is compiled to leverage hardware acceleration on newer machines. If yours doesn't support it and you have a Visual Studios compiler, you can try setting the extended architecture support to SSE2. 

-- misha

**Comment by nmm02003** [comment]
Thank you mkazhdan, that was exactly the issue.  Code is running now.

**Comment by puffosauro** [comment]
Hi.
Maybe I've found the cause of the problem but I'm not sure how to solve it.
Now I've built PoissonRecon 9.0 with Visual Studio 2015, both Debug and Realease mode. In Debug mode it works without errors, in Release mode crashes at startup. Running under Visual Studio, I get this error:

Illegal Instruction.
PoissonRecon.exe!`dynamic initializer for 'face_props''() Line 241 (Ply.h)

So the problem is in the initialization of this static variable:
static PlyProperty face_props[] =
{
	{ _strdup( "vertex_indices" ) , PLY_INT , PLY_INT , offsetof( PlyFace , vertices ) , 1 , PLY_UCHAR, PLY_UCHAR , offsetof(PlyFace,nr_vertices) },
};

in Ply.h line 241.

Googoling for "Illegal Instruction dynamic initializer for" I've found some similar cases.

**Comment by AParvizi66** [comment]
Hi,
I am using V6.11. The project crashes when I enable Openmp. So I used two simple threads and I found that threads share orig_line and words variables which have been defined in https://github.com/mkazhdan/PoissonRecon/blob/master/Src/PlyFile.cpp->ply_read()#749,752.
But I do not know how to fix it.

**Comment by mloskot** [comment]
Would it be possible to just remove the `_strdup`?

**Comment by FlowzZz** [comment]
Hi,
I have a similar issue when running in release mode (with last source, VS2015 and no args), the code crash in Octree.inl (line 84). In debug, no problem. I try to set extended architecture support to SSE2, but it does not solve the problem. Is it a known issue?

Thank you,

**Comment by mkazhdan** [comment]
Sorry for the delayed response. Removing _strdup may work.
Alternatively, you may be able to declare the string "vertex_indices" as a static char* outside of the definition of face_props and then use the pointer in the definition (without having to use _strdup to make a copy).

**Comment by FlowzZz** [comment]
I try to remove it or to declare the string "vertex_indices" as a static char* outside of the definition of face_props and then use the pointer in the definition, but no success. Any other idea?
