### ISSUE TITLE
Empty .ply files?

### ISSUE THREAD

**Issue by trosslbg** [mkazhdan/PoissonRecon#113]
The following command return an empty .ply file with no faces or vertices. Why could this be happening?

**PoissonRecon --in points_1.las --out example.ply --depth 10 --colors**

**Comment by mkazhdan** [comment]
What does the point set look like? Can you share it?

**Comment by trosslbg** [comment]
I unfortunately can't share it, but I believe the error may have something to do with a lack of point normals. Could this be the case?

**Comment by mkazhdan** [comment]
It's certainly the case that without normals the code won't work.

**Comment by trosslbg** [comment]
Thank you!
