### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mkazhdan/PoissonRecon#117]
I would like to point out that identifiers like “[`__PLY_FILE_H__`](https://github.com/mkazhdan/PoissonRecon/blob/c1b1214e8f30daa5996f40976e5195c9e71871f6/Src/PlyFile.h#L32 "Update candidate")” and “[`__SPARSEMATRIX_HPP`](https://github.com/mkazhdan/PoissonRecon/blob/c1b1214e8f30daa5996f40976e5195c9e71871f6/Src/SparseMatrix.h#L28 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mkazhdan** [comment]
Thanks. I've made the change my codebase. It will be reflected in the GitHub repo at the next push.
