### ISSUE TITLE
[ERROR] Failed to validate properties in file

### ISSUE THREAD

**Issue by nikhilkoditala** [mkazhdan/PoissonRecon#118]
I captured a .ply file using intel realsense camera. When I am trying to create a surface recon of this ply file I got the below error. If I try it for some other ply file its working fine. Can any one suggest a way to fix this?

[ERROR] Src/PointStream.inl (Line 339)
reset
Failed to validate properties in file

**Comment by mkazhdan** [comment]
Can you share the .ply file, or even post the header?

**Comment by nikhilkoditala** [comment]
Here is the ply file:
[Link](https://drive.google.com/file/d/1dVXTG0PObRjCptaz0neG061B6hwKEGgX/view?usp=sharing)

**Comment by mkazhdan** [comment]
The problem is that the ply file does not contain normals.

**Comment by nikhilkoditala** [comment]
Oh, is there any way to generate normals?

**Comment by mkazhdan** [comment]
The reconstruction code doesn't provide it. But you could try using MeshLab.

**Comment by nikhilkoditala** [comment]
@mkazhdan 
I was able to create normals and run the poissonrecon sucessfully. But what I observed was the background beside the object is also generating a mesh. You can look at this [link](https://drive.google.com/file/d/178SBfHxDRoUYhQ_CV5H5pkAYMvbS7g6e/view?usp=sharing) for the screenshot. Can you please suggest what's wrong with it

**Comment by mkazhdan** [comment]
Can you try running with an additional "--bType 2" parameter?
If that still doesn't work, it's possible that the code generating the normals may be doing so inconsistently. (That is, it might have gotten the wrong sign.)

**Comment by nikhilkoditala** [comment]
Thanks for your quick reply @mkazhdan, adding the --bType parameter works. One last question does PoissonRecon work for point clouds aswell? Actually, I need a way of converting pointcloud to mesh is there any way to do it?

**Comment by mkazhdan** [comment]
Unfortunately, the code requires normals. However, there are techniques out there for turning unoriented point clouds to oriented point clouds. 
For example, at SGP this year there was a paper "Parallel Globally Consistent Normal Orientation of Raw Unorganized Point Clouds". You can check if they provide source code.

**Comment by nikhilkoditala** [comment]
Sure I will look into it, I am closing this issue now, I will reopen if anyone has any problem
