### ISSUE TITLE
Divide-by-zero exception thrown with --density

### ISSUE THREAD

**Issue by rgb2hsv** [mkazhdan/PoissonRecon#12]
Problem traced to _GetSampleDepthAndWeight() in MultiGridOctreeData.WeightedSamples.inl

Suggested fix:
if(oldWeight>0&&newWeight>0){
double denom=log( newWeight / oldWeight ) ;
if(denom!=0){
depth = Real( _Depth( temp ) + log( newWeight ) / denom);
}
} else {
depth = Real( _Depth( temp ));
}

**Comment by mkazhdan** [comment]
Problem should be resolved in new release
