### ISSUE TITLE
Surface Trimmer

### ISSUE THREAD

**Issue by nikanfds** [mkazhdan/PoissonRecon#121]
I have a mesh (vertices, faces, and color), and I want to remove the disconnected patches. What should I set for the signal value per vertex?

**Comment by mkazhdan** [comment]
In no particular order:
1. Is the mesh the output of poisson reconstruction with the --density flag turned on?
2. Can you share the data?
3. Is the problem that you want to trim the data in regions where there were no samez or that you want to remove small islands (disconnected components)?

**Comment by nikanfds** [comment]
My 3D triangular mesh contains three 2D vectors(using C++ STL), one is for vertices coordinates, one is the faces and one is colors(per vertex), which I converted them to your data structure (point stream);

I want to trim parts of the mesh that is small island (like less than 50 connected triangles) by using Execute function of SurfaceTrimmer.cpp

Currently I have my mesh inside the code but I may be able to export obj file for you to see it.

**Comment by mkazhdan** [comment]
I'm afraid that in that case my code will not work out of the box as it assumes that the mesh has a signal (density) value with each vertex. 

This is something that PoissonRecon can provide with its output. 

If you're only interested in removing islands, you may be able to trick the code by creating a vector of scalar values each with value (e.g.) 1. Then you can run the surface trimmer by using a trimming value less than (e.g.) 1.

**Comment by nikanfds** [comment]
I did that by trying different IslandRatio but it doesn't remove any triangle. And if I set trim value more than the per-vertex signal it removes all the triangles(obvious!).

By the trick you said gtPolygons would contain the whole mesh triangles at the end!

Lets say my mesh contains 1000 connected triangles and also another 20 connected triangles which is separated from the rest. I would assume small island removal should delete the piece that has 20 connected triangles. But after island removal I get the same mesh I import.

**Comment by mkazhdan** [comment]
Can you create a .ply file with signal (density) values per vertex and share it?

**Comment by nikanfds** [comment]
Here is my points saved as ply file(face.ply) and I am trying to use poisson reconstruction first(face_pssn.ply), but it doesn't reconstruct well (a plane cut through the face). I appreciate having your thoughts about that.
[face.zip](https://github.com/mkazhdan/PoissonRecon/files/3483303/face.zip)

**Comment by mkazhdan** [comment]
It looks like all your normals are zero.

**Comment by nikanfds** [comment]
[face_normals.ply.zip](https://github.com/mkazhdan/PoissonRecon/files/3486882/face_normals.ply.zip)
This one has normals.

**Comment by mkazhdan** [comment]
I'm not sure I understand what you mean by "a plane cut through the face". Do you mean that the back of the head does not close off?
If you would like to get a mesh without boundary, you need to use Dirichlet boundary conditions. Specifically:
1. You need to negate the x-, y-, and z-coordinates of your normals so that they point outward instead of inward.
2. When running the reconstruction code, you should the parameter "--bType 2".
(Independently, it looks like your data is very noisy, so you may want to disable screening, "--pointWeight 0", and you may want to use a lower default, "--depth 7".)

**Comment by nikanfds** [comment]
Thank you so much, the key point was in the normals that should be outward; and also boundary condition worked like a charm!

**Comment by jaquilio** [comment]
In Kazdan et al's 2006 "Poisson Surface Reconstruction" paper, normals are assumed to be inward facing. Does the code actually assume the other way, i.e., that normals are facing outward, as stated above?
