### ISSUE TITLE
Problem in building the  SSDrecons project

### ISSUE THREAD

**Issue by SomayehHesabi** [mkazhdan/PoissonRecon#123]
![Error](https://user-images.githubusercontent.com/46501252/62657620-eb61bd80-b934-11e9-9a20-8e15275a29fd.JPG)

I got this error compiling both versions 12 and 11.0.
Really appericiate it if you any indeas how to fix it.

Thanks

**Comment by mkazhdan** [comment]
What version of MSVC are you using?

**Comment by SomayehHesabi** [comment]
I am using MSCV 2015( v 14.0). And I am having the same problem for PoissonRecon.

**Comment by SomayehHesabi** [comment]
By installing MSCV 2019, I could buid bothe SSDrecons and PoissonRecon projects, successfully.
