### ISSUE TITLE
PoissonRecon mesh result issue when point cloud has collision

### ISSUE THREAD

**Issue by happyfrank** [mkazhdan/PoissonRecon#125]
Hi @mkazhdan, this is my PoissonRecon mesh result. The wall between two rooms was broken.
![2](https://user-images.githubusercontent.com/12987532/63848741-08812d80-c9c3-11e9-967c-48c676887c4c.jpg)
I think it was because the point cloud of the two rooms collided.
![0](https://user-images.githubusercontent.com/12987532/63848957-87766600-c9c3-11e9-821d-b98ae7a3490a.png)
 [test data](https://drive.google.com/open?id=18MWTIU2k9s4NwiDSB5wAZ2f1PXQUke-V)
Can you tell me how to solve this problem? Thanks. ^v^

**Comment by mkazhdan** [comment]
Looking at the dataset you shared, it looks like the problem is due to the fact that the alignment is off and (half of) the points on the front side of the wall end up being behind the points on the backside. Can you try to re-register the two point-sets?

**Comment by happyfrank** [comment]
Of course, re-registering the two point-sets can fix it. 
I wanna ask if there is any other way to solve this problem? Thanks.

**Comment by mkazhdan** [comment]
Unfortunately, nothing comes to mind. You could try to flip the normals in the region of overlap, but I don't know of an easy way to do that.

**Comment by happyfrank** [comment]
That's all right, thanks.

**Comment by happyfrank** [comment]
Sorry, I just leave this issue open. Maybe someone can answer my question. ^v^
