### ISSUE TITLE
how can get two plane ?

### ISSUE THREAD

**Issue by elfc2000** [mkazhdan/PoissonRecon#127]
There are two planes point cloud。I wan‘t restructure the planes。But I got two closure mesh ，when use default parameters。
How do I set the parameters?
![QQ截图20190904215335](https://user-images.githubusercontent.com/7008108/64261359-f709c980-cf5e-11e9-9744-9821c2e9b1ff.jpg)
 
![QQ截图20190904215822](https://user-images.githubusercontent.com/7008108/64261450-21f41d80-cf5f-11e9-9235-a6dc41b4c478.jpg)

**Comment by elfc2000** [comment]
This is point cloud
[pointcloud.zip](https://github.com/mkazhdan/PoissonRecon/files/3574859/pointcloud.zip)

**Comment by mkazhdan** [comment]
I'm sorry. I'm afraid I don't follow the question. Can you write again what you are trying to do?

**Comment by elfc2000** [comment]
> I'm sorry. I'm afraid I don't follow the question. Can you write again what you are trying to do?
> More precisely, looking at the point cloud I see that you have two squares. One on top of the other. Both with normals pointing in the same direction. What is it that you would like to see in the reconstruction?

I want reconstruction the two squares from the point cloud.
like this

![QQ截图20190904224603](https://user-images.githubusercontent.com/7008108/64265603-cda06c00-cf65-11e9-81b7-72cc02c287c0.jpg)
[plane.zip](https://github.com/mkazhdan/PoissonRecon/files/3575044/plane.zip)

**Comment by elfc2000** [comment]
> Given your pointset, I don't think that's possible.
> To get this kind of reconstruction you would need to:
> 
> 1. Flip the normals on one of the two squares
> 2. Reconstruct
> 3. Use the surface trimmer to remove the reconstruction in regions away from the samples.

Thank you very very much. It works。
![QQ截图20190904225855](https://user-images.githubusercontent.com/7008108/64266767-c1b5a980-cf67-11e9-9aab-54572170dbb2.jpg)
