### ISSUE TITLE
Use SurfaceTrimmer with another reconstruction library output

### ISSUE THREAD

**Issue by sealiutree7** [mkazhdan/PoissonRecon#129]
Hello, thank you for sharing such a powerful library and I don't know whether this question is stupid or not.  I am trying to use another pipeline (COLMAP+OpenMVS) to finish my 3D reconstruction and use SurfaceTrimmer to trim the final result. However, there is no `property float value` in my final .ply which will be needed in SurfaceTrimmer like this:

> ply
format binary_little_endian 1.0
comment Running Screened Poisson Reconstruction (Version 8.0)
comment 	--in fused.ply
comment 	--out fusedoutx64.ply
comment 	--density
comment #             Tree set in:       0.9 (s),      16.1 (MB)
comment #      Constraints set in:       0.2 (s),      25.0 (MB)
comment # Linear system solved in:       0.8 (s),      26.2 (MB)
comment #        Got triangles in:       0.3 (s),      27.5 (MB)
comment #             Total Solve:       2.3 (s),      27.5 (MB)
element vertex 6015
property float x
property float y
property float z
property float value
element face 11901
property list uchar int vertex_indices
end_header

Instead, I only have `comment TextureFile model_dense_mesh_refine_texture.png` and `property list uint8 float32 texcoord` as below:

> ply
format binary_little_endian 1.0
comment TextureFile model_dense_mesh_refine_texture.png
element vertex 16619
property float32 x
property float32 y
property float32 z
element face 32488
property list uint8 uint32 vertex_indices
property list uint8 float32 texcoord
end_header

As a result, there always appears an error which says "Ply file does not contain values".
Is it possible to use the above information to provide the data that needs in SurfaceTrimmer? If you have any idea or I say something wrong, please don't refuse to offer your kind advice. Thanks a lot again.

**Comment by mkazhdan** [comment]
The only thing I can recommend is using the source for the PLY I/O to read in your file and add in the "value" property with the specified value. 

Note that the value at each vertex defines a signal on the surface. The SurfaceTrimmer code removes the part of the mesh whose value is below a specified threshold. How the per-vertex value is set is application dependent, so you will need to provide values that are meaningful to you.

**Comment by sealiutree7** [comment]
Thank you so much for replying and giving guidance. I'll try it and update if have any progress. Thanks again!

**Comment by 20181313zhang** [comment]
Hello, gays, have you make any progress in your work? I want to use another pipeline (COLMAP+OpenMVS) to finish my 3D reconstruction and use SurfaceTrimmer to trim the final result too. So if you have any suggest, that would be wonderful.
