### ISSUE TITLE
Poisson Reconstuction command line - silent mode

### ISSUE THREAD

**Issue by petrasvestartas** [mkazhdan/PoissonRecon#135]
Is it possible to execute PoissonReccon .exe  file in a silent mode?

I am executing this .exe file in C# using the code below.
If I want to run executable in silent mode I usually uncomment UseShellExecute  and RedirectStandardOutput properties, but this gives me an error:
_Unhandled Exception: System.ComponentModel.Win32Exception_: The system cannot find the file specified

If I keep a code like this it runs, but the additional command line screen is popping up and closing.

    ```
        var proc = new System.Diagnostics.Process {
                StartInfo = new System.Diagnostics.ProcessStartInfo {
                    FileName = "PoissonRecon",
                    Arguments = "--in " + fileNameIn + " --out " + fileName + " --depth "+depth.ToString()+" --pointWeight 0 --colors",
                    //UseShellExecute = false,
                    //RedirectStandardOutput = true,
                    CreateNoWindow = true,
                    WorkingDirectory = filePath
                }
            };

            proc.Start();
            proc.WaitForExit();
```

**Comment by mkazhdan** [comment]
Out of curiosity, when running from the command line, what kind of messages do you see? Are they all warnings?

**Comment by petrasvestartas** [comment]
Hi,

It is a blank black screen:

![Blank](https://user-images.githubusercontent.com/18013985/68743706-b3d17400-05fb-11ea-800f-bffe70960610.png)

I have the correct output from PoissonRecon.exe with a resulting good mesh. It works fine, just this black splash screen.


I also asked the question in stackoverflow and one person replied that: 
_"it probably needs to be done in tandom with the original app owner "_

**Comment by mkazhdan** [comment]
Are you running the executable from my GitHub or the one from CloudCompare? I don't believe the one from my GitHub should be popping up a black screen.

**Comment by petrasvestartas** [comment]
I am running the executable from Github.
CloudCompare is just to estimate pointcloud normals.

Any ideas how this could be fixed?

**Comment by mkazhdan** [comment]
Never seen this before. Can you show a screenshot of the screen with the text? (It's obstructed in the previous snapshot.)

**Comment by petrasvestartas** [comment]
I do not know why, but adding a line:
WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden

Solves the problem. 
The windows before was just printing some debugging info.
