### ISSUE TITLE
How to use your work in my project

### ISSUE THREAD

**Issue by rlczddl** [mkazhdan/PoissonRecon#138]
Hi, I am a beginner of C++. I tried the exe file you provided, and the poisson reconstruction results are very good (better than the pcl library). However, I don't know how to use your work in my project, for example, how to compile, which header files to include, which specific function interface to call, and so on. Can you give me some help?Thanks in advance.

**Comment by jmespadero** [comment]
That question is not an issue (bug or feature request) of this project. You may have more luck trying in another forums as https://stackoverflow.com/
