### ISSUE TITLE
Debug build of PoissonRecon.cpp needs /bigobj compilation option

### ISSUE THREAD

**Issue by jedfrechette** [mkazhdan/PoissonRecon#14]
Using Visual Studio 2015 doing a debug build fails with the message:

`PoissonRecon.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
`
After adding the /bigobj compilation option the build succeeds and the binary can be run successfully.

**Comment by mkazhdan** [comment]
I have updated the project files so that the solution/project files now support debug mode.

Hopefully that should resolve the issue.

 

-- Misha
