### ISSUE TITLE
Nothing error log and output mesh.

### ISSUE THREAD

**Issue by nenoNaninu** [mkazhdan/PoissonRecon#140]
I executed PoissonRecon.exe with the attached model, but neither console log nor mesh output.
When checking the exit status with echo %ERRORLEVEL%, -1073741795 was output. (0 is returned without any argument)

```
$ PoissonRecon --in model.ply --out output.ply --normals
$echo %ERRORLEVEL%
-1073741795
```

I want to know how to solve, thank you!
[model.zip](https://github.com/mkazhdan/PoissonRecon/files/4083002/model.zip)

**Comment by mkazhdan** [comment]
Strange. I didn't have trouble running the executable on this dataset.
What version of the reconstruction code / executable are you using?
What kind of machine / OS are you running on?
Also, it may be the case that the "--normals" parameter takes an argument. You probably want to specify "--normals 2".

**Comment by nenoNaninu** [comment]
Sorry, I made a mistake in the attached model.
[this is correct](https://github.com/mkazhdan/PoissonRecon/files/4083201/model.zip)

However, the model I just attached first doesn't work either.
```
[WARNING] c:\research\poissonrecon\poissonrecon\src\femtree.initialize.inl (Line 193)
          FEMTreeInitializer<3,float>::Initialize
          Found bad data: 224
```
I tried `--normals 2` but the problem didn't change.

using 12.00 downloaded from [here](http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version12.00/AdaptiveSolvers.x64.zip).

os: windows 10 version 1903

**Comment by mkazhdan** [comment]
The warning about bad data is just a warning. You should have still gotten an output. 

What happens if you add the "--verbose" flag?

**Comment by nenoNaninu** [comment]
```
$ PoissonRecon --in model.ply --out out.ply --normals --verbose
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 12.00) **
*************************************************************
*************************************************************
Running with 8 threads
        --in model.ply
        --out hoge.ply
        --verbose
        --normals

$ echo %ERRORLEVEL%
-1073741795


$ PoissonRecon --in model.ply --out hoge.ply --normals 2 --verbose
[WARNING] c:\research\poissonrecon\poissonrecon\src\cmdlineparser.inl (Line 259)
          cmdLineParse
          Parameter name should be of the form --<name>: 2
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 12.00) **
*************************************************************
*************************************************************
Running with 8 threads
        --in model.ply
        --out hoge.ply
        --verbose
        --normals

$ echo %ERRORLEVEL%
-1073741795
```

**Comment by mkazhdan** [comment]
Strange. Running the same example on my Windows 10 machine (with the same downloaded executable you are using) I get a reconstruction that looks something like a pancake.

What CPU do you have?

Could you try running with an additional "--threads 1" flag?

**Comment by nenoNaninu** [comment]
Thank you, the issue was solved.
The above problem occurred when the CPU was i7-2600, but when I tried using i7-5557U, it worked.

**Comment by GreKro** [comment]
Hello everyone,

I have the same problem as described above,  nothing happens after a PoissonRecon.exe (ver. 12.00) call: no errors in the console and no result file.  I have a laptop with CPU Intel Core i7-3610QM 2,3 GHz and Windows 10 OS, additional switches like --threads 1 don't help. I attached a screenshot from cmd (In this example I use horse dataset from http://www.cs.jhu.edu/~misha/Code/PoissonRecon/Version12.00/)

@mkazhdan  can you help with this issue? 

![poisson_cmd](https://user-images.githubusercontent.com/26602062/77523726-77096980-6e86-11ea-8953-608e9660045b.png)

**Comment by mkazhdan** [comment]
Do you have visual studios? If so, what happens when you try to compile the code?

**Comment by GreKro** [comment]
I try to compile the code in VS2017 and at beginning I have errors like this : 

![Poisson_VS2017](https://user-images.githubusercontent.com/26602062/77549147-c748f180-6eaf-11ea-9d58-658a9e6d4edd.png)

I thought I need to upgrade my Windows SDK to a newer version so I probably downloaded the newest one. After installation, I started the compilation process. The build process was successful without errors (screens below), after building the new files I tried to run them, but the situation is identical to the executables downloaded from the official site - no bugs in the console and no result files. I tried to download exactly the SDK version that was displayed in the first VS2017 error but after building the files the situation is identical.

To be honest, I'm not a pro in C++ and VS2017, maybe I did something wrong. 
@mkazhdan  do you have some ideas ?

![Poisson_VS2017_1](https://user-images.githubusercontent.com/26602062/77550960-feb89d80-6eb1-11ea-9923-f5bc67315aff.png)

![Poisson_VS2017_2](https://user-images.githubusercontent.com/26602062/77550982-06784200-6eb2-11ea-984f-721dc8e7350e.png)

**Comment by mkazhdan** [comment]
It could be an issue of your hardware not supporting vectorization.
Can you try the following:
-- Right click on the "PoissonRecon" project and select "Properties".
-- Select "Configuation Properties" -> "C/C++" -> "Code Generation".
-- Under the option "Enable Enhanced Instruction Set", try selecting a lighter choice like "Streaming SIMD Extensions" or "Streaming SIMD Extensions 2".
-- Compile again.
-- Try running again.

**Comment by GreKro** [comment]
@mkazhdan Thanks for the hint, problem solved :-)

I compiled with "Streaming SIMD Extensions 2" option and it started to work properly :-)
Thanks a lot once more time,
Best wishes,
