### ISSUE TITLE
textual file format for color input

### ISSUE THREAD

**Issue by talkenig** [mkazhdan/PoissonRecon#141]
Hi, 
I went through all the open and closed issues, but could not find what the input format should be if I want to input an ascii file with color.
The eagle is the only color example and it is binary.
Would appreciate if you could provide a sample textual input file with color, or just specify how the header should look and how a data line should look.
Many thanks,

**Comment by mkazhdan** [comment]
There is no header. You just specify six floating point values (corresponding to vertex position and normal) and then an additional three integer values in the range [0-255]. For example, here is the first line of the file I get when converting the Eagle to .npts format:
"1.654000 -1.468270 -0.314310  -0.594618 0.371081 -0.713251 250 247 250"

**Comment by talkenig** [comment]
Thanks, that's perfect.
