### ISSUE TITLE
Running examples for PoissonRecon in Visual Studio 2019

### ISSUE THREAD

**Issue by philianeles** [mkazhdan/PoissonRecon#150]
Hello, could you give some instructions how to run the the examples for PoissonRecon in Visual Studio 2019? (How to call the Poisson surface reconstructor with the right command arguments?
Thank you!
![image](https://user-images.githubusercontent.com/11179066/78237793-14dee300-74dc-11ea-808a-c9350bf8e532.png)

**Comment by mkazhdan** [comment]
Are you asking how to compile or how to run? If it's about running, the website has a description in the "USAGE EXAMPLES (WITH SAMPLE DATA)" section.

**Comment by philianeles** [comment]
Yes, I have found that exactly:
![image](https://user-images.githubusercontent.com/11179066/78267663-81bba280-7507-11ea-8714-7167a30ca2df.png)

And I assumed that we are to pass command arguments at runtime?
But I have this error: `Failed to open file for reading: horse.npts`
![image](https://user-images.githubusercontent.com/11179066/78272357-b3d00300-750d-11ea-97ca-88a6881d6a43.png)

**Comment by mkazhdan** [comment]
Are you sure that the horse.npts file is in the same directory as the executable is being run from with MSVC? You may want to give the full path name.

**Comment by philianeles** [comment]
right. And I just realized that there is actually no .npts (or .ply) files in the repo. Am I on the wrong branch?
Where is the data located for running the examples?

**Comment by mkazhdan** [comment]
If you look at the README.md file on GitHub, then under the section “USAGE EXAMPLES (WITH SAMPLE DATA)” you can find the links to the datasets.

**Comment by philianeles** [comment]
ok found them it works, thanks!
