### ISSUE TITLE
Error running PoissonRecon 

### ISSUE THREAD

**Issue by philianeles** [mkazhdan/PoissonRecon#151]
Hi, I am running the PoissonRecon with my point cloud data (collected with Azure Kinect DK): https://www.dropbox.com/s/r94qvv8zttgf069/0.025ms_to_0.00625ms_Ed_600mm.points.ply?dl=0

I have this error:
![image](https://user-images.githubusercontent.com/11179066/78369925-3f0ccf80-75c6-11ea-817e-78e2667eb0ad.png)

Any hints how to avoid this?

Thank you.

**Comment by mkazhdan** [comment]
It likely means you have lots of points which have either zero length normals, or normals with infinity/undefined coefficients. Try saving the ply file in ASCII mode and looking through to make sure the points look reasonable.

**Comment by philianeles** [comment]
ok. I have a new .ply sample which contains the normals (hardware: Intel RealSense D435i)

I have this error now:
![image](https://user-images.githubusercontent.com/11179066/78669747-067a3800-78dd-11ea-80f2-b6096749fd5d.png)

**Comment by mkazhdan** [comment]
1. What do the command line arguments look like?
2. What does the .ply file header look like?
3. Can you share the data?

**Comment by philianeles** [comment]
1. Like this: (converted to ASCII)
```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 220501
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 438034
property list uchar int vertex_indices
end_header
```
2.  `--in rgb.points.ply --out rgb.ply --depth 10 --pointWeight 0`
3. Here it is: https://www.dropbox.com/s/9fikianmgp5kpmt/rgb_ASCII.ply?dl=0
Binary is also here: https://www.dropbox.com/s/2j6ojyqublmejub/rgb.ply?dl=0

**Comment by mkazhdan** [comment]
Running on your dataset, I managed to get a color reconstruction using the ascii version (when I added the "--colors" flag.) However, your binary file does not have normals. (If you look at the header of rgb.ply, you will see that there are no properties "nx", "ny", or "nz".)

**Comment by philianeles** [comment]
Even after adding the normals to the binary version it throws the same error as above:
`Failed to validate properties in file`

But the ascii version (also including the normals) somehow produces some result that I can visualize. Though i still see the same error, even after removing the color data:
```
FEMTreeInitializer<3,float>::Initialize
          Found bad data: 22
```

Anyways thank you!
