### ISSUE TITLE
Edge Intersections.

### ISSUE THREAD

**Issue by thebluespecs** [mkazhdan/PoissonRecon#154]
Sir, If you could please explain where do you handle the edge intersection computation in the source. It's really hard with all the branching. Query on V12.

**Comment by mkazhdan** [comment]
I'm not sure I follow the question. Could you be more precise? What part of the code is causing confusion?

**Comment by thebluespecs** [comment]
On a broader scale, I am trying to identify the nodes which are currently hidden or visible according to projection on the screen. More like adaptive subdivision but based on the visibility of the node on the computer screen. 
For that I need to calculate the edge intersections of the polygons {triangulation in this case} and further subdivide them accordingly. does this help?

**Comment by mkazhdan** [comment]
1. I'm not sure what you mean by "the edge intersections of the polygons". The intersections of the edges of the triangulation with what?
2. It's not clear to me what you are asking: Is it that something about the code doesn't make sense or that you don't understand how to adapt the code to do something else?

**Comment by thebluespecs** [comment]
I figured out the problem
- The intersections with the volume of the cube while reconstructing with marching cubes. (issue #147 )
If the node is marked visible then the polygon in that node is further sub divided {adding more children to the this node} and so on. 
Does this make sense ?
Sorry for the confusion and thank you for your help.
