### ISSUE TITLE
Missing GitHub tags.

### ISSUE THREAD

**Issue by bartoszek** [mkazhdan/PoissonRecon#155]
Looks like some tags went missing, on the home page there's already `v11.0` but highest tag on GitHub is just `v8.0`

**Comment by mkazhdan** [comment]
The tag should now be 13.0. (Although I've been updating the code, I have been remiss in updating the tags. You should be able to see the version by running any of the executables with the "--verbose" flag.)

**Comment by bartoszek** [comment]
Thanks, just a minor issue with packaging for Arch User Repository.
