### ISSUE TITLE
How to compile the project on the Ubuntu18.04?

### ISSUE THREAD

**Issue by Junkai-Liu** [mkazhdan/PoissonRecon#158]
As the question described above , I'm familier with CmakeLists to organise project files, how should I compile the project and run the executable on linux?

**Comment by mkazhdan** [comment]
You can just enter the main directory and type "make". That should compile everything. (Though it may take a bit of time.)

**Comment by Junkai-Liu** [comment]
Thank u for your reply !

**Comment by brianm-sra** [comment]
Regarding "may take a bit of time" ... I'm seeing it take about 15 minutes or more just to 
compile PoissonRecon.cpp  to PoissonRecon.o
Might be that my computer has old hardware and I need a faster Linux machine.

I want to simplify the code and build. I only need to support the simple use cases of
PoissonRecon --in infile.npts --out outfile.ply
PoissonRecon --in infile.ply --out outfile.ply

I'm trying to strip out other code that I don't need for that, and might try refactoring
from one PoissonRecon.cpp file to multiple cpp files.
I might also switch from the current Makefile to CMake at some point.
Any other tips for speeding up compilation and reducing code size?

**Comment by mkazhdan** [comment]
If you have not tried it already, in PreProcessor.h, you can change declaration so that FAST_COMPILE is defined:
     #define FAST_COMPILE
That should reduce the compilation time.

**Comment by brianm-sra** [comment]
> If you have not tried it already, in PreProcessor.h, you can change declaration so that FAST_COMPILE is defined:
> #define FAST_COMPILE
> That should reduce the compilation time.

Great, thank you.
Looks like I was able to compile a modified version of PoissonRecon (with some other things commented out also) in about 3 minutes by using FAST_COMPILE
and run it (message "Compiled for degree-1, boundary-Neumann, single-precision _only_")
to generate sample output horse_mesh_output.ply which looks good enough for my needs
at the moment. And the speed up in compile time was my main issue at the moment
while making other experimental local changes and planning to go through cycle of rebuilding/retesting multiple times.

**Comment by Russell-fan** [comment]
> You can just enter the main directory and type "make". That should compile everything. (Though it may take a bit of time.)

After Compiling it,how can I run the project ? Why did I get the error of "PoissonRecon: command not found "

**Comment by mkazhdan** [comment]
There should be a bin/Linux directory with the executable inside.
