### ISSUE TITLE
float32 type size error

### ISSUE THREAD

**Issue by srivathsanmurali** [mkazhdan/PoissonRecon#16]
Hi,
In PlyFile.cpp: ply_type_sizes,
 1) float 32 is set to be 8 bytes
 2) an entry for float64 is missing.

**Comment by srivathsanmurali** [comment]
I made a pr for the fix just in case

**Comment by mkazhdan** [comment]
Thanks for catching that.

I have moved the fix into my code and will include it with the next version.

 

-- Misha
