### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by shor-ofer** [mkazhdan/PoissonRecon#162]
## Memory foot print on PoissonRecon is much larger on versions greater or equal to version 8

for example running the same sample data  on version 11 vs version 5

running on version 11 using --btype 3  and --degree 2  --depth 12 

## Peak Memory (MB): **11938**

vs

running on version 5 using --depth 12  ( should be the same as bType 3 --degree 2 )

## Peak Memory (MB): **2924**

please notice the big difference  in memory peak.

**Comment by mkazhdan** [comment]
1. Can you share the dataset?
2. If you run with the --verbose flag, what do the outputs look like? (Specifically, I'm curious if the two octrees have the same number of nodes.)

**Comment by shor-ofer** [comment]
# Running Screened Poisson Reconstruction (Version 11.00) 

Running with 12 threads
        --degree 2
        --in in.ply
        --depth 12
        --out out.ply
        --verbose
        --pointWeight 4.000000
        --performance
[WARNING] c:\research\poissonrecon\poissonrecon\src\femtree.initialize.inl (Line 167)
          FEMTreeInitializer<3,float>::Initialize
          Found bad data: 2588
Input Points / Samples: 2543637 / 2390056
### Read input into tree:       3.6 (s),    1074.9 (MB) /    1074.9 (MB) /       0.0 (MB)
###   Got kernel density:       3.5 (s),    1668.7 (MB) /    1668.7 (MB) /       0.0 (MB)
###     Got normal field:       4.9 (s),    2661.9 (MB) /    2661.9 (MB) /       0.0 (MB)
Point weight / Estimated Area: 8.16715e-07 / 2.07743
###       Finalized tree:       8.1 (s),    3072.8 (MB) /    3072.8 (MB) /       0.0 (MB)
### Set FEM constraints:      15.5 (s),    2568.3 (MB) /    3072.8 (MB) /       0.0 (MB)
### Set point constraints:       3.0 (s),    2270.9 (MB) /    3072.8 (MB) /       0.0 (MB)
Leaf Nodes / Active Nodes / Ghost Nodes: 46090948 / 33511744 / 19163625
Memory Usage: 2270.922 MB
Cycle[0] Depth[ 0/12]:  Updated constraints / Got system / Solved in:  0.000 /  0.002 /  0.000  (2521.848 MB)   Nodes: 1
Cycle[0] Depth[ 1/12]:  Updated constraints / Got system / Solved in:  0.004 /  0.005 /  0.000  (2521.914 MB)   Nodes: 8
Cycle[0] Depth[ 2/12]:  Updated constraints / Got system / Solved in:  0.003 /  0.000 /  0.000  (2522.012 MB)   Nodes: 64
Cycle[0] Depth[ 3/12]:  Updated constraints / Got system / Solved in:  0.003 /  0.004 /  0.001  (2522.570 MB)   Nodes: 512
Cycle[0] Depth[ 4/12]:  Updated constraints / Got system / Solved in:  0.004 /  0.028 /  0.004  (2526.457 MB)   Nodes: 4096
Cycle[0] Depth[ 5/12]:  Updated constraints / Got system / Solved in:  0.005 /  0.060 /  0.049  (2542.449 MB)   Nodes: 32768
Cycle[0] Depth[ 6/12]:  Updated constraints / Got system / Solved in:  0.006 /  0.060 /  0.048  (2582.738 MB)   Nodes: 57264
Cycle[0] Depth[ 7/12]:  Updated constraints / Got system / Solved in:  0.012 /  0.144 /  0.163  (2729.063 MB)   Nodes: 230544
Cycle[0] Depth[ 8/12]:  Updated constraints / Got system / Solved in:  0.036 /  0.438 /  0.579  (3216.488 MB)   Nodes: 892008
Cycle[0] Depth[ 9/12]:  Updated constraints / Got system / Solved in:  0.103 /  1.642 /  2.218  (4628.938 MB)   Nodes: 3300576
Cycle[0] Depth[10/12]:  Updated constraints / Got system / Solved in:  0.344 /  5.473 / 10.114  (8205.527 MB)   Nodes: 10048656
Cycle[0] Depth[11/12]:  Updated constraints / Got system / Solved in:  1.828 / 14.954 / 41.162  (9733.426 MB)   Nodes: 17612552
Cycle[0] Depth[12/12]:  Updated constraints / Got system / Solved in:  0.129 /  0.909 /  1.029  (9733.426 MB)   Nodes: 1293448
### Linear system solved:      90.0 (s),    9733.4 (MB) /    9733.4 (MB) /       0.0 (MB)
Got average:       1.9 (s),    2180.7 (MB) /    9733.4 (MB) /    9733.4 (MB)
Iso-Value: 4.987065e-01 = 1.26853e+06 / 2.54364e+06
Vertices / Polygons: 5731131 / 11461086
Corners / Vertices / Edges / Surface / Set Table / Copy Finer: 8.2 / 9.5 / 10.0 / 5.4 / 14.7 / 3.8 (s)
###        Got triangles:      59.6 (s),    4046.3 (MB) /    9733.4 (MB) /       0.0 (MB)
###          Total Solve:     228.6 (s),    9733.4 (MB)
Time (Wall/CPU): 230.95 / 230.94
Peak Memory (MB): 9740





# Running Screened Poisson Reconstruction (Version 5.71)
        --in in.ply
        --depth 12
        --out out.ply
        --verbose
        --pointWeight 4.000000
        --performance
###             Tree set in:      19.3 (s),    2486.8 (MB)
Input Points: 2543637
Leaves/Nodes: 33172231/37911121
Memory Usage: 2486.809 MB
###      Constraints set in:      12.6 (s),    2889.3 (MB)
Memory Usage: 2179.109 MB
Depth[0/12]: 1
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (2323.770 MB)
Depth[1/12]: 8
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.000   (2323.777 MB)
Depth[2/12]: 64
        Evaluated / Got / Solved in:  0.000 /  0.000 /  0.001   (2323.781 MB)
Depth[3/12]: 512
        Evaluated / Got / Solved in:  0.000 /  0.001 /  0.000   (2323.781 MB)
Depth[4/12]: 4096
        Evaluated / Got / Solved in:  0.000 /  0.003 /  0.005   (2324.047 MB)
Depth[5/12]: 32768
        Evaluated / Got / Solved in:  0.001 /  0.017 /  0.058   (2335.297 MB)
Depth[6/12]: 64000
        Evaluated / Got / Solved in:  0.001 /  0.039 /  0.092   (2353.371 MB)
Depth[7/12]: 261256
        Evaluated / Got / Solved in:  0.002 /  0.126 /  0.331   (2450.996 MB)
Depth[8/12]: 927248
        Evaluated / Got / Solved in:  0.009 /  0.418 /  0.876   (2802.086 MB)
Depth[9/12]: 3444104
        Evaluated / Got / Solved in:  0.026 /  2.352 /  3.326   (2836.141 MB)
Depth[10/12]: 10603640
        Evaluated / Got / Solved in:  0.076 /  7.535 / 13.685   (2839.199 MB)
Depth[11/12]: 19813176
        Evaluated / Got / Solved in:  0.154 / 15.130 / 37.569   (2839.199 MB)
Depth[12/12]: 2760248
        Evaluated / Got / Solved in:  0.021 /  2.397 /  2.826   (2839.199 MB)
### Linear system solved in:     112.8 (s),    2839.2 (MB)
Memory Usage: 2334.168 MB
Got average in: 1.783000
Iso-Value: 8.461953e-04
###        Got triangles in:      42.0 (s),    4561.7 (MB)
###


             Total Solve:     189.1 (s),    4561.7 (MB)

PlyWritePolygons time = 6.351000Time (Wall/User/Kernel): 195.59 / 106.03 / 33.86
Peak Memory (MB): 2924

**Comment by mkazhdan** [comment]
How many vertices in the reconstruction from 5.7?

**Comment by mkazhdan** [comment]
A couple of things worth noting:
1. The new solver creates an octree with more nodes. (I'm also guessing it generates more vertices in the reconstruction.) This is likely due to the fact that the way --samplesPerNode is interpreted changed between the versions. You can probably get better memory performance and the same sized output by increasing the value of --samplesPerNode when running the Version 11.0 code.
2. It's also the case that version 6.0 the solver switched from using a conjugate gradient solver with domain decomposition to using a windowed Gauss-Seidel solver. I would not have expected it to increase the memory usage, but perhaps I was wrong.
3. It is also worth noting that Version 5.71 peaks at 4561.7 MB (in the iso-surface extraction phase), not 2924 MB as (incorrectly) stated by the solver.

**Comment by shor-ofer** [comment]
Thanks allot for the fast response

1. Working with --samplesPerNode decrease dramatically the memory footprint
you call see in the Log below . running it with version 11.0 on the same data set with samplesPerNode from 1 to 10.
on the other hand the amount of polygons in the mesh is going down,
I will check the errors(quality) between the different meshes , and may choose to work with samplesPerNode grater than 
one.

2. It would be interesting to know if the   windowed Gauss-Seidel solver has settings to decrease the amount of memory it use - if this the issue.

3. You are right about version 5.71. it is  4561.7 MB not 2924 MB but still a factor of 2.5 :-(



### Log:

samplesPerNode 1  Peak Memory (MB): 13209 Vertices / Polygons: 7700686 / 15399950
samplesPerNode 2  Peak Memory (MB): 9598	Vertices / Polygons: 4748987 / 9496848
samplesPerNode 3  Peak Memory (MB): 6551	Vertices / Polygons: 3207528 / 6413616
samplesPerNode 4  Peak Memory (MB): 5602	Vertices / Polygons: 2348911 / 4695964
samplesPerNode 5  Peak Memory (MB): 5016	Vertices / Polygons: 1915310 / 3828890
samplesPerNode 6  Peak Memory (MB): 4631	Vertices / Polygons: 1652730 / 3303990
samplesPerNode 7  Peak Memory (MB): 4306	Vertices / Polygons: 1464937 / 2928560
samplesPerNode 8  Peak Memory (MB): 3968	Vertices / Polygons: 1323778 / 2646336
samplesPerNode 9  Peak Memory (MB): 3558	Vertices / Polygons: 1201667 / 2402142
samplesPerNode 10 Peak Memory (MB): 3107	Vertices / Polygons: 1078431 / 2155562

Thanks

**Comment by mkazhdan** [comment]
Great. In terms of #1, I don't think you have to do anything as complicated as compare qualities. Comparing the number of vertices in the output reconstructions should be sufficient.

**Comment by shor-ofer** [comment]
Thanks
