### ISSUE TITLE
[PointInterpolant] Scale of gradient changes.

### ISSUE THREAD

**Issue by saedrna** [mkazhdan/PoissonRecon#163]
I have sucessfully runs PointInterpolant with only value constraint, but I can not restore the original function with the points constraint at boundary and gradient constraint inside.

After calling `FEMTreeInitializer<Dim, Real>::template Initialize<FunctionValueType>` and `FEMTreeInitializer<Dim, Real>::template Initialize<FunctionGradientType>`, I get the `valueSampleData` and `gradientSampleData` below.
![image](https://user-images.githubusercontent.com/3850191/92601401-553e5a80-f2df-11ea-8d9d-43f44a1860f4.png)
![image](https://user-images.githubusercontent.com/3850191/92601423-5bccd200-f2df-11ea-94df-64a8ec03759b.png)

But the scale of `gradientSampleData` is magnified a lot (only at the magnitude of about 10 for the inputs). And the scale of `valueSampleData` stays the same.
As a result, the scale of the output function is also magnified, with similar shape.

In addition, the input is a height map, the values are the height value and the gradient is defined as `dx=v(c+1,r) - v(c,r)` and `dy = v(c,r+1)-v(c,r)` .

Is the behavior for `gradientSampleData` expected? Or the `gradientSampleData` also changes with scale defined by `_modelToUnitCube`? Even if gradient should be scaled by the `_modelToUnitCube`, I believe the value in my case should be made smaller rather than bigger. Because the domain of my input exceeds [0,1].

Thanks,
Han

**Comment by mkazhdan** [comment]
Any chance you can provide the following:
1. An ASCII function containing the positions/values at the boundary,
2. An ASCII function containing the positions/gradients in the interior,
3. A description of the analytic solution.

**Comment by saedrna** [comment]
> Any chance you can provide the following:
> 
> 1. An ASCII function containing the positions/values at the boundary,

Please find the `values.txt`

> 2. An ASCII function containing the positions/gradients in the interior,

Please find the `gradients.txt`

> 3. A description of the analytic solution.

My problem is the standard poisson problem, i.e. interpolate the interior of a function $f$ with some guided file $v$.
![CodeCogsEqn](https://user-images.githubusercontent.com/3850191/92619480-22eb2800-f2f4-11ea-9a00-f8b15727a905.png)


[data.zip](https://github.com/mkazhdan/PoissonRecon/files/5196192/data.zip)

**Comment by mkazhdan** [comment]
Thanks. I'll take a look at things and try to get back to you.

In the meanwhile, I think the gradient values are correct.
To map the input to the unit square you scale positions by a factor of, roughly, s = 1/150. As a result, the gradients need to be scaled by a factor of 1/s (same change over a much smaller interval) thereby accounting for the significant increase in gradient size within the internal representation.

**Comment by mkazhdan** [comment]
Also, if you run with the "--ascii" flag and "--out <output ply file>" you should be able to read off the vertices of the mesh in the output ply file. The (x,y)-coordinates will give you the positions (in the original coordinate frame). The z-coordinate will give the height. Comparing to values in expected.txt, it seems like the reconstruction was doing a reasonable job. (Though I did not test exhaustively.)

**Comment by saedrna** [comment]
Below is a subset from `expected.txt`.
```
33.00 56.00 601.18
34.00 56.00 591.62
35.00 56.00 580.63
36.00 56.00 573.62
37.00 56.00 577.01
38.00 56.00 581.16
39.00 56.00 584.26
```
Below is a subset from out.ply
```
33.2754 56.4199 504.718 
33.8555 56.4199 491.014 
34.4355 56.4199 477.803 
35.0156 56.4199 466.491 
35.5957 56.4199 459.79 
36.1758 56.4199 459.106 
36.7559 56.4199 463.098 
37.3359 56.4199 470.416 
37.916 56.4199 477.095 
38.4961 56.4199 480.006 
```

You could see the difference is about 100 meters.
My command line is 
`--inValues values.txt --inGradients gradients.txt --out mesh.ply --ascii --inCore --verbose`

Outputs from console is 
```
***********************************************
** Running Point Interpolant (Version 13.60) **
***********************************************
***********************************************
Running with 16 threads
        --inValues values.txt
        --inGradients gradients.txt
        --out mesh.ply
        --verbose
        --ascii
        --inCore
Input Value Points / Value Samples: 4860 / 4860
Input Gradient Points / Gradient Samples: 11125 / 11125
# Read input into tree:       0.0 (s),       7.8 (MB) /       7.8 (MB) / 8 (MB)
#       Finalized tree:       0.0 (s),      13.0 (MB) /      13.0 (MB) / 13 (MB)
#Set point constraints:       0.0 (s),      13.6 (MB) /      13.6 (MB) / 13 (MB)
Leaf Nodes / Active Nodes / Ghost Nodes: 49399 / 65864 / 1
Memory Usage: 13.645 MB
Cycle[0] Depth[5/8]:    Updated constraints / Got system / Solved in:  0.008 /  0.014 /  0.018  (15.465 MB)     Nodes: 1156
Cycle[0] Depth[6/8]:    Updated constraints / Got system / Solved in:  0.014 /  0.010 /  0.001  (15.465 MB)     Nodes: 3696
Cycle[0] Depth[7/8]:    Updated constraints / Got system / Solved in:  0.019 /  0.028 /  0.004  (15.891 MB)     Nodes: 12896
Cycle[0] Depth[8/8]:    Updated constraints / Got system / Solved in:  0.011 /  0.058 /  0.016  (16.215 MB)     Nodes: 47200
# Linear system solved:       0.2 (s),      16.2 (MB) /      16.2 (MB) / 16 (MB)
Value Error: 0.0082024
Gradient Error: 0.0195138
#          Total Solve:       0.4 (s),      16.2 (MB)
```

**Comment by saedrna** [comment]
> To map the input to the unit square you scale positions by a factor of, roughly, s = 1/150. As a result, the gradients need to be scaled by a factor of 1/s (same change over a much smaller interval) thereby accounting for the significant increase in gradient size within the internal representation.

If gradient is rescaled? Why not rescale value?

**Comment by mkazhdan** [comment]
I don't think you need to rescale the gradients. The code should take care of that for you. The code rescales them because gradients are measured in terms of "change over distance". Remapping changes the notion of distance so gradients need to be adjusted. Values are measured in terms of "value per point", which is not affected by remapping. 

It is possible that the bilinear weight is too large. I will try to look more closely later.

**Comment by saedrna** [comment]
I have just found out the problem, it is in fact MY BAD.
The gradient is scaled up two times, because I am in fact using [Scharr filter in OpenCV](https://docs.opencv.org/4.4.0/d4/d86/group__imgproc__filter.html#gaa13106761eedf14798f37aa2d60404c9) for the gradient.
And I add a wrong scale factor.

Add the following produce correct results.
```c++
for (int i = 0; i < inCorePointsAndGradients.size(); ++i){
    auto sasmple = inCorePointsAndGradients[i];
    auto gradient = sasmple.get<1>();
    gradient = gradient / 2.0;
    sasmple.get<1>() = gradient;
    inCorePointsAndGradients[i] = sasmple;
}
```
