### ISSUE TITLE
Crash for data set (provided) when using a Dirchlet boundary condition

### ISSUE THREAD

**Issue by evercoast-smm** [mkazhdan/PoissonRecon#164]
Git Hash:

git checkout 49f75e44a9ddfeda4376b491afbd8b60de551c23

Data:

https://evercoast.s3-us-west-1.amazonaws.com/0000.evercoast.transfer/PR_bug_091220/PR_bug_091220_1.7z

Crash:

PoissonRecon --in ply_obey/EC_FRAME-OBEY.0000085.ply --out ply_recon/EC_FRAME-MESH.0000085.ply --depth 8 --bType 2 --scale 1.75 --samplesPerNode 2 --density --threads 1

Notes:

(1)

--bType 1, or 3 works fine. Dirchlet (2), crashes.

(2)

The frame that crashes is 85, but we've included adjacent frames (84 & 86) that work fine for Dirchlet.

**Comment by mkazhdan** [comment]
Thanks for catching the problem and sharing data.
Can you try out the recently posted Version 13.61? I believe it should address the issue.

**Comment by evercoast-smm** [comment]
Fixed.

Confirmation:

PR_bug_091220_1$ PoissonRecon --verbose --in EC_FRAME-OBEY.0000085.ply --out recon.ply --depth 8 --bType 2 --scale 1.75 --samplesPerNode 2 --density --threads 1
*************************************************************
*************************************************************
** Running Screened Poisson Reconstruction (Version 13.61) **
*************************************************************
*************************************************************
        --bType 2
        --in EC_FRAME-OBEY.0000085.ply
        --depth 8
        --out recon.ply
        --scale 1.750000
        --verbose
        --samplesPerNode 2.000000
        --threads 1
        --density
Input Points / Samples: 27327 / 13575
# Read input into tree:       0.1 (s),       9.5 (MB) /       9.5 (MB) / 9 (MB)
#   Got kernel density:       0.0 (s),      10.2 (MB) /      10.2 (MB) / 10 (MB)
#     Got normal field:       0.0 (s),      14.0 (MB) /      14.0 (MB) / 14 (MB)
Point weight / Estimated Measure: 6.39902e-06 / 0.174866
#Initialized point interpolation constraints:       0.0 (s),      14.7 (MB) /      14.7 (MB) / 14 (MB)
#       Finalized tree:       0.0 (s),      21.9 (MB) /      21.9 (MB) / 21 (MB)
#  Set FEM constraints:       0.1 (s),      21.4 (MB) /      21.9 (MB) / 21 (MB)
#Set point constraints:       0.0 (s),      21.4 (MB) /      21.9 (MB) / 21 (MB)
Leaf Nodes / Active Nodes / Ghost Nodes / Dirichlet Supported Nodes: 147428 / 168488 / 1 / 0
Memory Usage: 21.375 MB
Cycle[0] Depth[5/8]:    Updated constraints / Got system / Solved in:  0.001 /  0.109 /  0.026  (33.625 MB)     Nodes: 29791
Cycle[0] Depth[6/8]:    Updated constraints / Got system / Solved in:  0.002 /  0.007 /  0.004  (34.141 MB)     Nodes: 11656
Cycle[0] Depth[7/8]:    Updated constraints / Got system / Solved in:  0.005 /  0.018 /  0.010  (34.395 MB)     Nodes: 31232
Cycle[0] Depth[8/8]:    Updated constraints / Got system / Solved in:  0.000 /  0.047 /  0.023  (34.395 MB)     Nodes: 68416
# Linear system solved:       0.3 (s),      34.4 (MB) /      34.4 (MB) / 34 (MB)
Got average:       0.0 (s),      34.4 (MB) /      34.4 (MB) / 34 (MB)
Iso-Value: 4.993793e-01 = 13646.5 / 27327
Vertices / Polygons: 18429 / 36854
Corners / Vertices / Edges / Surface / Set Table / Copy Finer: 0.1 / 0.0 / 0.0 / 0.0 / 0.1 / 0.0 (s)
#        Got triangles:       0.6 (s),      56.5 (MB) /      56.5 (MB) / 56 (MB)
#          Total Solve:       1.2 (s),      56.5 (MB)

Thank you very much!

**Comment by guyuezuntinggithub** [comment]
> Fixed.
> 
> Confirmation:
> 
> ```
> PR_bug_091220_1$ PoissonRecon --verbose --in EC_FRAME-OBEY.0000085.ply --out recon.ply --depth 8 --bType 2 --scale 1.75 --samplesPerNode 2 --density --threads 1
> *************************************************************
> *************************************************************
> ** Running Screened Poisson Reconstruction (Version 13.61) **
> *************************************************************
> *************************************************************
>         --bType 2
>         --in EC_FRAME-OBEY.0000085.ply
>         --depth 8
>         --out recon.ply
>         --scale 1.750000
>         --verbose
>         --samplesPerNode 2.000000
>         --threads 1
>         --density
> Input Points / Samples: 27327 / 13575
> # Read input into tree:       0.1 (s),       9.5 (MB) /       9.5 (MB) / 9 (MB)
> #   Got kernel density:       0.0 (s),      10.2 (MB) /      10.2 (MB) / 10 (MB)
> #     Got normal field:       0.0 (s),      14.0 (MB) /      14.0 (MB) / 14 (MB)
> Point weight / Estimated Measure: 6.39902e-06 / 0.174866
> #Initialized point interpolation constraints:       0.0 (s),      14.7 (MB) /      14.7 (MB) / 14 (MB)
> #       Finalized tree:       0.0 (s),      21.9 (MB) /      21.9 (MB) / 21 (MB)
> #  Set FEM constraints:       0.1 (s),      21.4 (MB) /      21.9 (MB) / 21 (MB)
> #Set point constraints:       0.0 (s),      21.4 (MB) /      21.9 (MB) / 21 (MB)
> Leaf Nodes / Active Nodes / Ghost Nodes / Dirichlet Supported Nodes: 147428 / 168488 / 1 / 0
> Memory Usage: 21.375 MB
> Cycle[0] Depth[5/8]:    Updated constraints / Got system / Solved in:  0.001 /  0.109 /  0.026  (33.625 MB)     Nodes: 29791
> Cycle[0] Depth[6/8]:    Updated constraints / Got system / Solved in:  0.002 /  0.007 /  0.004  (34.141 MB)     Nodes: 11656
> Cycle[0] Depth[7/8]:    Updated constraints / Got system / Solved in:  0.005 /  0.018 /  0.010  (34.395 MB)     Nodes: 31232
> Cycle[0] Depth[8/8]:    Updated constraints / Got system / Solved in:  0.000 /  0.047 /  0.023  (34.395 MB)     Nodes: 68416
> # Linear system solved:       0.3 (s),      34.4 (MB) /      34.4 (MB) / 34 (MB)
> Got average:       0.0 (s),      34.4 (MB) /      34.4 (MB) / 34 (MB)
> Iso-Value: 4.993793e-01 = 13646.5 / 27327
> Vertices / Polygons: 18429 / 36854
> Corners / Vertices / Edges / Surface / Set Table / Copy Finer: 0.1 / 0.0 / 0.0 / 0.0 / 0.1 / 0.0 (s)
> #        Got triangles:       0.6 (s),      56.5 (MB) /      56.5 (MB) / 56 (MB)
> #          Total Solve:       1.2 (s),      56.5 (MB)
> ```
> 
> Thank you very much!

Hi，I have some data set without normal，I can't get the normal like yours
![image](https://user-images.githubusercontent.com/63081832/93424578-deaae980-f8ea-11ea-817d-14144b9b27c2.png)
I can just get normal like this

![image](https://user-images.githubusercontent.com/63081832/93424738-321d3780-f8eb-11ea-9217-d4abe789638c.png)

some normals orient outside of surface,but the others orinet inside of surface
how can i get the normal like yours?
