### ISSUE TITLE
the diffrent way of computting normal will get diffrent orientation ，how can this algorithm get right surface with different orientation

### ISSUE THREAD

**Issue by guyuezuntinggithub** [mkazhdan/PoissonRecon#165]
the diffrent view we set,such as the centroid or face view, will have different normal. what kind of normal should i input this algorithm.thank you!

**Comment by mkazhdan** [comment]
I'm afraid I don't follow the question. What "view" are you referring to?

**Comment by guyuezuntinggithub** [comment]
I mean that i usually use pcl get the normal，and there is a function “pcl::NormalEstimation.setViewPoint()” to set the viewpoint

**Comment by mkazhdan** [comment]
Unfortunately, I am not familiar with PCL functionality.
My guess is that this functionality is used to specify the camera's origin, allowing the code disambiguate the sign of the normal. (Specifically, using a local PCA analysis, one can estimate a normal, n, at a point, p, only up to multiplication by plus or minus one. If you know the camera's viewpoint, v, then you know that to have been seen by the camera the point must have been front facing. That is, the dot-product <n,p-v> has to be less than zero. Which tells you how to assign the sign to the normal.)

**Comment by guyuezuntinggithub** [comment]
thank you very much。I get it
