### ISSUE TITLE
Obtain solution of the Poisson equation as oriented pointcloud with no mesh

### ISSUE THREAD

**Issue by nachovizzo** [mkazhdan/PoissonRecon#167]
Hello there :+1: 

Is there any way to hack the code to obtain the solution of the Poisson equation at each node of the octree but without running marching cubes? I'm looking to somehow interpolate a given input PointCloud. Should I take a look to `PointInterpolant` ?

Thanks in advance!

**Comment by mkazhdan** [comment]
If you look in PoissonRecon.cpp, after Line 900 the solution is computed and stored in the object "solution". For example, Lines 941-952 sample the function on a regular grid (and output it to disk).

PointInterpolant will only work for you if you have values at the point samples that you want the implicit function to interpolate. (i.e. not data with normals)

**Comment by nachovizzo** [comment]
Ok, I will see if I will inspect the `solution` object then. Thanks!
