### ISSUE TITLE
How to make a proper envelope?

### ISSUE THREAD

**Issue by cdb0y511** [mkazhdan/PoissonRecon#169]
Hi, @mkazhdan. Very appreciate your great work. I am happy about this famous reconstruction algorithm is still evolving. 
I am working on RGB-D reconstruction, which uses PoissonRecon and SurfaceTrimmer; it always left some artifacts after the trim.  I find your latest works, "Poisson Surface Reconstruction with Envelope Constraints." I think PoissonRecon with envelope constraint (Dirichlet envelope) is much better than PoissonRecon with SurfaceTrimmer. The Torso example is amazing. 

However, in practice,  the RGB-D data is generally noisy, and camera pose is also inaccurate. I have the segmentation mask, depth, camera extrinsic, and intrinsic. I follow the paper, dilated the depth with minimal depth in a radius of eight pixels. But marching cubes may not work well on noisy depth. I try some others like GreedyProjectionTriangulation or PoissonRecon as envelope input.

I may get the wrong idea. The envelope is generally a fatter triangulation mesh (cause the dilate process and PoissonRecon take mesh as an envelope input, torso.hull.ply.  ). But with GreedyProjectionTriangulation or PoissonRecon as envelope input, the reconstruction has a  false outer layer instead of a ballon. 

How to make a proper envelope?
Any advice for noisy RGB-D data input?
This may relate to #168  #166
Thanks

**Comment by cdb0y511** [comment]
give an example 

marching cube:
![snapshot00](https://user-images.githubusercontent.com/11908862/98455529-d2fcd600-2169-11eb-92ec-e19cf9cb4532.png)

poission with envelope (marching cube) : 
![snapshot-raw-poission02](https://user-images.githubusercontent.com/11908862/98455543-f4f65880-2169-11eb-9085-f909a4854706.png)

poission without envelope:
![snapshot-envelope01](https://user-images.githubusercontent.com/11908862/98455533-dabc7a80-2169-11eb-8776-654ec8046fc7.png)

**Comment by mkazhdan** [comment]
Hi,

Unfortunately, I do not quite follow the problem. What does the "Marching cubes" result show? Is this the envelope? (If so, that should be ok. So long as it encloses the region within which you know the surface must lie, you should be doing ok.) I'm assuming that the last image shows results without envelope or trimming, right? One issue might be that you have flipped normals on parts of your surface.

**Comment by cdb0y511** [comment]
> Hi,
> 
> Unfortunately, I do not quite follow the problem. What does the "Marching cubes" result show? Is this the envelope? (If so, that should be ok. So long as it encloses the region within which you know the surface must lie, you should be doing ok.) I'm assuming that the last image shows results without envelope or trimming, right? One issue might be that you have flipped normals on parts of your surface.

Yes, marching cubes is the envelope generated from dilated depth maps; use marching cubes as your paper.
The last one is without an envelope or trimming.

So I get the right idea which the envelope is a fatter mesh enclose the surface. 
The middle one with an envelope (first mesh) seems to have a false outer layer caused by flipped normals.
You mean normal of the envelope or reconstruction one, or both.
If I make them towards the camera, it may solve the problem. Right?
I will let you know if I make any progress.
Thanks, @mkazhdan.

**Comment by mkazhdan** [comment]
Yep. The envelope should be a dilated mesh enclosing the surface.
I mean the normals of the input points. (And yes, they should be oriented so that the dot-product with the camera's forward direction is negative.) Though there is an assumption that the envelope is the boundary of a solid model and that the orientations are such that CCW normals point to the exterior.

**Comment by cdb0y511** [comment]
It works perfectly. However, the better result is with an envelope generated by PoissonRecon, not Marching cubes( I think the PoissonRecon is generally more robust ).
Still, I have some questions about it. 
Sometimes a warning like this:
[WARNING] Src/FEMTree.Initialize.inl (Line 199)
          Initialize
          Found bad data: 3
What does it mean?
Any advice to tweak the result, especially with the envelope case?

**Comment by mkazhdan** [comment]
That means you have three input points with bad normals. (Either zero length, or undefined values.)

**Comment by donlk** [comment]
> Thanks,@mkazhdan
> It works perfectly. However, the better result is with an envelope generated by PoissonRecon, not Marching cubes( I think the PoissonRecon is generally more robust ).
> Still, I have some questions about it.
> Sometimes a warning like this:
> [WARNING] Src/FEMTree.Initialize.inl (Line 199)
> Initialize
> Found bad data: 3
> What does it mean?
> Any advice to tweak the result, especially with the envelope case?

How do you generate an envelope with PoissonRecon? Isn't it the point to manually create a boundary somehow and feed it to PossionRecon?

**Comment by mkazhdan** [comment]
I was wondering the same thing...

**Comment by cdb0y511** [comment]
I am sorry I did not explain it quite clearly. @asmaloney 
This issue is mainly focused on how to generate a proper envelope.
I think an envelope is:

> Yep. The envelope should be a dilated mesh enclosing the surface.

So I test on some methods to generate the mesh from dilated depth.
I find PoissonRecon with a dilated point cloud as input, generate a fine envelope.
(I wonder if the noisy RGBD data make different mesh reconstruction method behave quite differently)
Then I use it as an envelope to constrain PoissonRecon with an original point cloud.
It performs a better result than PoissonRecon + SurfaceTrimmer.

The envelope is PoissonRecon (a dilated point cloud input).
The final reconstruction is PoissonRecon(original point cloud ) with the envelope above.

I think a different method to generate an envelope from the same dilated point cloud may result in quite a different reconstruction.
Right?  
@mkazhdan 

another warning :
[WARNING] Src/FEMTree.IsoSurface.specialized.inl (Line 1886)
          Extract
          bad average roots: 2
what does it mean?
