### ISSUE TITLE
How to use MemoryInputDataStream, OrientedPoint ?

### ISSUE THREAD

**Issue by brianm-sra** [mkazhdan/PoissonRecon#170]
Hello,

I am trying to wrap part of PoissonRecon open source basic functionality for use
as a library API of sorts as part of a research project (details of our project are secret at this point).
I am trying to make a method that will take input of points and normals
via memory data structure passed in as public method parameter, instead of PLY file from disk.

In PoissonRecon.cpp, I see that data from input file is read in via an input stream, such as
BinaryInputDataStream, PLYInputDataStream, or ASCIIInputDataStream.

I wanted to see if I could set pointStream to a MemoryInputDataStream
where the Data was replaced by a vector of multiple OrientedPoint objects
where OrientedPoint is defined in Geometry.h to include a Point p and Point n (normal),
and MemoryInputDataStream is defined in VertexStream.h / VertexStream.inl
or my own version of that stream with slightly different definition.

However, I was having difficulty getting the right syntax in order to compile
and match the existing templates, base class definition of virtual next methods, etc.

Has anyone tried something similar, passing in the points/normals from a data structure
in memory, instead of a file ?

Any existing sample code that I can refer to ?

Thanks for any tips.

**Comment by mkazhdan** [comment]
If you look at the code in PoissonRecon.cpp, lines 590-598, you'll see that lines 590-596 read the .ply file and add the oriented point information into an std::vector< InputSampleType >.
Then, in line 598, that std::vector is used to create a MemoryInputDataStream.
(The tricky thing is figuring out what "InputSampleType" should be, as this is a template parameter that depends on what information, in addition to positions and normals, the point-cloud contains at each point.)

**Comment by brianm-sra** [comment]
I will take a look at that. Thanks.

My current need is only to support inputs that are a set of
point (x, y, z) and corresponding normal (nx, ny, nz)
and probably a size() of total number of inputs points.
At this point in time I don't need to support any additional information.

**Comment by mkazhdan** [comment]
In the case that you are only providing points and normals, you should track the call to "Execute" when called as follows:
     Execute< Real >( FEMSigs() , VertexFactory::EmptyFactory< Real >() );
As done in lines1124, 1129, 1147, or 1152.
(This is likely overkill because you are prescribing an "empty factory" and you could probably without using one, but it would make the code a little more messy.)

**Comment by brianm-sra** [comment]
I'm trying to do something like the following.
Still working through the details indicated by TODO.
I'll keep working on it.
Any additional suggestions would be appreciated.

```
#include "Geometry.h"
...
std::vector<OrientedPoint<Real,3>>* InputData;
...
void PoissonRecon::myNewMethod( std::vector<OrientedPoint<Real,3>>* inputData)
{
...
In.value = nullptr;
In.set = false;
InputData = inputData;
...
Execute< Real >( FEMSigs() , VertexFactory::EmptyFactory< Real >() );
}

// inside Execute method:
...
    // for now, existing typedef definitions of InputSampleFactory, InputSampleDataFactory, InputPointStreamInfo, InputSampleType, InputSampleDataType, InputPointStream, etc.
    // TODO: might need to use modified typedef(s)
...
    InputPointStream* pointStream;
    if (!In.set || (In.value == nullptr))
    {
        // data provided in memory data structure InputData, not file named In.value
        // TODO: fix this, should NOT need a reinterpret_cast here if types were correct
        pointStream = reinterpret_cast<InputPointStream *>
                (new MemoryInputDataStream<vector<OrientedPoint<Real, 3>>>(InputData->size(), InputData)); // NOTE: added constructor to MemoryInputDataStream that takes *Data instead of const *Data since I defined my InputData variable without const
    }
    else
    {
        // data provided via file named In.value
        // existing code to process *.ply file from disk
        char *ext = GetFileExtension(In.value);
...
```

**Comment by mkazhdan** [comment]
One thing that looks wrong is your declaration of "MemoryInputDataStream". It probably should be:
     MemoryInputDataStream< OrientedPoint< Real , 3 > >
That is, the "vector" part is unnecessary. Including it tells the code that every element of the stream is a vector of oriented points, when every element is a single oriented point. (This probably also explains why you had to add a reinterpret_cast, which you shouldn't need.)

Also, not quite sure you needed the additional constructor, given that there shouldn't be a problem casting "Foo *" to "const Foo *". The problem should only be in the other direction.

**Comment by brianm-sra** [comment]
Thanks for the tips so far.  That helps some, and this syntax looks okay:

```
vector<OrientedPoint<Real,3>> InputData;

    typedef InputDataStream< OrientedPoint<Real, 3> >  MyInputPointStream;
    MyInputPointStream* myPointStream;
    myPointStream = new MemoryInputDataStream<OrientedPoint<Real, 3>>(InputData.size(), &InputData[0]);
```
However, I think I need to either (A) convert this data stream after creation to InputPointStream* pointStream based on new MemoryInputDataStream< InputSampleType > somehow , or (B) before creating MemoryInputDataStream< InputSampleType > convert each OrientedPoint<Real, 3> one by one to an InputSampleType object somehow

and then probably use existing code based on pointStream for creating XInputPointStream variable _pointStream and FEMTreeInitializer which uses _pointStream

I am not clear how to use both point and normal to construct a InputSampleType object

I could maybe do something like this (after or instead of example above) with additional code for TBD added as appropriate ??? 

```
    OrientedPoint<Real,3> op;
    vector<InputSampleType> inputSamples;
    while ( myPointStream->next( op ) )
    {
        Point<Real,3> point = op.p;
        Point<Real,3> normal = op.n;

        //
        // InputSampleType constructor syntax TBD
        //
        inputSamples.push_back( p )
    }
    pointStream = new MemoryInputDataStream< InputSampleType >( inputSamples.size() , &inputSamples[0] );

```

For memory and speed efficiency, I would prefer to avoid two streams if one is enough.

**Comment by mkazhdan** [comment]
Note that MemoryInputPointStream< Data > inherits from InputDataStream< Data > so the conversion should be straight-forward.

**Comment by brianm-sra** [comment]
I got this to work now. Closing.

**Comment by brianm-sra** [comment]
@mkazhdan 

I am reopening to follow up. 

I got a version to work on Android, but not on Linux. 

I am currently doing a cast as shown below, but the values in the stream after cast seem to be wrong.

vector<OrientedPoint<Real,3>> PoissonRecon::InputData;
typedef            InputDataStream< InputSampleType >  InputPointStream;
InputPointStream* pointStream;
typedef InputDataStream< OrientedPoint<Real, 3> >  MyInputPointStream;
MyInputPointStream* myPointStream;
myPointStream = new MemoryInputDataStream<OrientedPoint<Real, 3>>(PoissonRecon::InputData.size(), &PoissonRecon::InputData[0]);
pointStream = (InputPointStream*) myPointStream;

The last line above attempts to cast a stream of OrientedPoint<Real, 3> values (point and normal)
to InputSampleType values.  It compiles and runs, but it looks like the values are wrong in the pointStream after that cast.

For some reason it works on Android, but not on Linux.  Not sure why.

I think I need to either just create data as vector< InputSampleType > or vector<PointAndDataType>
at the beginning, and not vector<OrientedPoint<Real,3>>

or maybe when the FEMTree.Initialize.inl code in third Initialize method has code like:

typename InputPointStream< AuxData >::PointAndDataType pd;
while( pointStream.next( pd ) )
{
        Point< Real , Dim > p = pd.template get<0>();
	typename InputPointStream< AuxData >::DataType d = InputPointStream< AuxData >::GetData( pd );
	Point<float, 3> normal = d.template get<0>();

I would need to have different code to read the pointStream in a different way,
using OrientedPoint<Real,3> as expected data type instead of PointAndDataType.

I was hoping not to have to modify code outside of PoissonRecon.cpp very much if it could be avoided,
but I'm not sure which approach is better.

**Comment by mkazhdan** [comment]
Instead of using an std::vector of OrientedPoint< Real , 3 >, can you try using an std::vector of InputSampleType where:
   InputSampleType  <- InputPointStreamInfo::PointAndDataType
   InputPointStreamInfo <- InputOrientedPointStreamInfo< Real , Dim , typename AuxDataFactory::VertexType >
   AuxDataFactory <- VertexFactory::EmptyFactory< Real >
I believe that the problem is that an object of type OrientedPoint< Real , 3 > and an object of type InputSampleType are not the same size. However, because of packing, they are allocated the same amount of space on Android. (That plus the fact that the two classes start by storing the position and the normal, could explain why things end up working on Android but not on Linux.)

**Comment by brianm-sra** [comment]
Thank you.  I will try that.  So far I am unclear on the syntax to construct a single InputSampleType
from x, y, z, nx, ny, nz values.

I want to do something like this:

```
...

const int Dim = 3;
typedef VertexFactory::EmptyFactory< Real > AuxDataFactory;
typedef InputOrientedPointStreamInfo< Real , Dim , typename AuxDataFactory::VertexType > InputPointStreamInfo;
typedef typename InputPointStreamInfo::PointAndDataType InputSampleType;
// or maybe typename InputPointStream< AuxData >::PointAndDataType InputSampleType; // like pd in FEMTree.Initialize.inl Initialize method

std::vector< InputSampleType > testDataVector;

while( ... )
{
    Point< Real , Dim > point = new Point<Real,Dim>();
    point.coords[0] = x;
    point.coords[1] = y;
    point.coords[2] = z;

    // TODO
    // = nx;
    // = ny;
    // = nz;

    // TODO
    InputSampleType pointAndNormal // constructor with p and normal or Data or AuxData containing normal

    testDataVector.push_back( pointAndNormal );

}

...

typedef            InputDataStream< InputSampleType >  InputPointStream;
InputPointStream* pointStream;
pointStream = (InputPointStream*) new MemoryInputDataStream< InputSampleType >( testDataVector.size(), &testDataVector[0] );

...
```

**Comment by mkazhdan** [comment]
If you have have (x,y,z) and (nx,ny,nz), you can set:
     InputSampleType pointAndNormal;
     pointAndNormal.get<0>() = Point< Real , Dim >( x , y , z );
     pointAndNormal.get<1>().get<0>() = Point< Real , Dim >( nx , ny , nz );
(You certainly don't want to be doing "new Point< Real , Dim >()" since that allocates on the heap and will result in a memory leak.)

**Comment by brianm-sra** [comment]
Hmm, for some reason I am getting a compile error with that

```
error: expected primary-expression before ‘)’ token
pointAndNormal.get<0>() = Point< Real , Dim >( x , y , z );
                      ^
error: invalid operands of types ‘<unresolved overloaded function type>’ and ‘int’ to binary ‘operator<’

error: expected primary-expression before ‘)’ token
pointAndNormal.get<1>().get<0>() = Point< Real , Dim >( nx , ny , nz );
                               ^
error: invalid operands of types ‘<unresolved overloaded function type>’ and ‘int’ to binary ‘operator<’
```

**Comment by brianm-sra** [comment]
Nevermind.  I fixed it with a bit of refactoring.

And it is now generating the correct output Polygon Mesh.

Thanks for your help.

**Comment by tranvnhan** [comment]
> Hmm, for some reason I am getting a compile error with that
> 
> ```
> error: expected primary-expression before ‘)’ token
> pointAndNormal.get<0>() = Point< Real , Dim >( x , y , z );
>                       ^
> error: invalid operands of types ‘<unresolved overloaded function type>’ and ‘int’ to binary ‘operator<’
> 
> error: expected primary-expression before ‘)’ token
> pointAndNormal.get<1>().get<0>() = Point< Real , Dim >( nx , ny , nz );
>                                ^
> error: invalid operands of types ‘<unresolved overloaded function type>’ and ‘int’ to binary ‘operator<’
> ```

I had the same issue. How did you solve this? @brianm-sra . Thanks.

**Comment by mkazhdan** [comment]
Can you try something like "pointAndNormal.template get<0>() = Point< Real , Dim >(x,y,z);"?

**Comment by FrankEscobar** [comment]
I've made a naive test (a sphere)

```
	std::vector<double> pos;
	std::vector<double> nor;
	int sphereSubdivs = 500;
	double sphereRadius = 10.0;
	const double sectorStep = 2 * 3.14159265359 / sphereSubdivs;
	double stackStep = 3.14159265359 / sphereSubdivs;

	for (int i = 1; i < sphereSubdivs; ++i)
	{
		const double Phi = i * stackStep - 0.5 * 3.14159265359;
		const double cosPhi = cos(Phi);
		const double z = sin(Phi);

		for (int j = 0; j < sphereSubdivs; ++j)
		{
			const double Theta = j * sectorStep;
			const double x = cosPhi * cos(Theta); // cos(u) * cos(v)
			const double y = cosPhi * sin(Theta); // cos(u) * sin(v)

			pos.push_back(sphereRadius * x);
			nor.push_back(-x);
			pos.push_back(sphereRadius * y);
			nor.push_back(-y);
			pos.push_back(sphereRadius * z);
			nor.push_back(-z);
		}
	}

	for (int mv = 0; mv < pos.size()/3; mv++)
	{
		const int mv3 = mv*3;
		InputSampleType pointAndNormal;
		pointAndNormal.get<0>() = Point< Real, Dim >(pos[mv3], pos[mv3+1], pos[mv3+2]);
		pointAndNormal.get<1>().get<0>() = Point< Real, Dim >(nor[mv3], nor[mv3 + 1], nor[mv3 + 2]);
		inCorePoints.push_back(pointAndNormal);
	}
	pointStream = new MemoryInputDataStream< InputSampleType >(inCorePoints.size(), &inCorePoints[0]);
```

But unfortunately it didn't work 

```
[ERROR] D:\Test\PoissonRecon\Src\Geometry.h (Line 222)
        Point<float>::operator +=
        Dimensions don't match: 5 != 0
```

Do you have any idea about what could be happening? Thank you in advance
