### ISSUE TITLE
Loss of poisson reconstruction details introduced in version 13

### ISSUE THREAD

**Issue by MaximeHerpin** [mkazhdan/PoissonRecon#173]
Hi,

There is a discrepancy between the results of versions 12.0 and 13.0 of poisson reconstruction. 
Using the same parameters (--colors --density --width 0.005), the 13 version appears "pixelated":
![poisson_recon](https://user-images.githubusercontent.com/15239308/103025136-2ca14000-451f-11eb-835a-7270e844998b.png)

This behavior is also present on the versions older than 13.00.
both results have approximately the same triangle count. I used the windows executables on [this dataset](https://drive.google.com/file/d/1xmIFq05jw6_4xsm6YcURH_-AJdkjR9Aa/view?usp=sharing).

Thank you !

**Comment by mkazhdan** [comment]
Just pushed an updated version.
Can you check if the new code addresses the issue?

**Comment by MaximeHerpin** [comment]
The new version does fix the issue, thank you !
