### ISSUE TITLE
Is it possible to compile a wrapper of the PoissonRecon code to avoid calling the .exe file?

### ISSUE THREAD

**Issue by CarMineo** [mkazhdan/PoissonRecon#174]
Hello All,
I am wondering if it is possible to compile a wrapper of PoissonRecon to avoid calling the .exe file. In particular, I would like to pass the point cloud and the normals to the PoissonRecon code as arrays, rather than having to export the point cloud to a text file and call the .exe file. This would increase the speed of my application.
Regards,
CarMineo

**Comment by mkazhdan** [comment]
Hi.
The big thing here is to allow PoissonRecon to use data in memory instead of data on disk.
I believe that is discussed in issue #170.

**Comment by CarMineo** [comment]
Hello @mkazhdan,
thanks for the useful information.
Cheers,
Carmelo
