### ISSUE TITLE
Question about line 199 in SurfaceTrimmer.cpp

### ISSUE THREAD

**Issue by liweiantoine** [mkazhdan/PoissonRecon#175]
Hello，

I have a question about the line 199 in SurfaceTrimmer.cpp
https://github.com/mkazhdan/PoissonRecon/blob/28934e8798422aca09e5a54bb439b0e193615582/Src/SurfaceTrimmer.cpp#L199

Maybe it should be like this?
if( polygons[i].size()>3 )

Thanks!

**Comment by mkazhdan** [comment]
You're right. It should.
Luckily, the minimal area triangulation code still works if the polygon has three vertices (it just returns the triangle) so the code should still work.

**Comment by liweiantoine** [comment]
Yes, so this small problem is not easy to find, but it doesn't matter.
Thank you for your quick reply!
