### ISSUE TITLE
Normals in oriented point cloud

### ISSUE THREAD

**Issue by CarMineo** [mkazhdan/PoissonRecon#176]
Hello all,
I have a questions about the normals relative to the points given as input to PoissonRecon.
Sometimes estimating the normal of each point using the point neighbour points, leads to the normal pointing to the wrong direction. Obviously it is possible to flip the wrong normals, but the process of detecting the wrong normals and flipping them can be very time consuming for large point clouds. 
Assuming I acquire the point cloud with a laser scanner, I am wondering if I can use the direction of the line of sight between the detected surface point and the sensor position in place of the point normal. In other words this direction will not be the normal to the surface. Nevertheless, the line of sight direction is always facing outwards from the surface. Is this a viable option or would it compromise the accuracy of the reconstruction? 
Cheers,
CarMineo

**Comment by mkazhdan** [comment]
Yep. This tends to be the way normals are oriented. First, you compute a normal using the neighbors (e.g. by solving for the best-fit plane). Then you choose the sign of the normal so that the dot-product with the view direction is negative.

**Comment by CarMineo** [comment]
@mkazhdan, I meant something different. Can I use the direction of the light of sight instead of computing the normals as you described? or does the algorithm require accurate normals?
Thanks,
CarMineo

**Comment by mkazhdan** [comment]
That probably won't work too well, though it might be better than having the right sign.

**Comment by CarMineo** [comment]
Thanks @mkazhdan.
