### ISSUE TITLE
detail degradation between V8 and V13.72

### ISSUE THREAD

**Issue by abby-normal2** [mkazhdan/PoissonRecon#181]
greetings.  we encountered an issue with V8 in regions of very sparse data.  we switched to V13.72 in which that issue was apparently fixed, but the surface detail ... the fidelity of the mesh to the input data ... was reduced.  this occurred with the same input parameters

--depth 5 --pointWeight 4 --samplesPerNode 10

figures attached
![version_8](https://user-images.githubusercontent.com/79552974/108933450-06238200-7600-11eb-8888-ae3ca82a9030.jpg)
![version_1372](https://user-images.githubusercontent.com/79552974/108933452-06bc1880-7600-11eb-8e37-18ec4cc6090c.jpg)

**Comment by mkazhdan** [comment]
Would you be able to share the data?

**Comment by abby-normal2** [comment]
absolutely.  but i'm away from my desk.  i'll post it tomorrow morning.
thanks so much
for the rapid reply.

**Comment by abby-normal2** [comment]
here's the .ply input to both reconstructions.

**Comment by abby-normal2** [comment]
sorry ... .ply wouldn't import.  here a .txt file exported from meshlab which (i hope) is the verts
and normals
[testinput3.txt](https://github.com/mkazhdan/PoissonRecon/files/6036571/testinput3.txt)

**Comment by abby-normal2** [comment]
sorry again ... not verts.  those are the input point coords and normals from which the mesh is to be constructed.

(first time on GitHub)

**Comment by mkazhdan** [comment]
I can't quite reproduce the earlier results, but one big difference is that in the old code, the default B-spline degree was 2, while in the newer version it's 1. You can try running the new code with the additional flag "--degree 2".

**Comment by abby-normal2** [comment]
unfortunately no change.  and strange, since literally the only difference
is the call to the .exe

full disclosure:  this call is made from a matlab script.  un-commenting
the appropriate call
produces the difference documented in the figures.

version 8:  system('PoissonRecon.x64_V8.exe --in testinput3.ply --out
testoutput3.ply --depth 5 --pointWeight 4 --samplesPerNode 10')

version 13.72 (including the recommendation of B-spline degree
2):  system('PoissonRecon.exe --in testinput3.ply --out testoutput3.ply
--depth 5 --pointWeight 4 --samplesPerNode 10 --degree 2')

**Comment by abby-normal2** [comment]
and just to complete the experiment ... adding "-- degree 1" to the version
8 input does
not produce the lower fidelity version 13.72 mesh.

**Comment by mkazhdan** [comment]
I believe that if you also change the --pointWeight value to 8, you will get something closer.
However, given the large number of changes between versions 8 and versions 13 (you can see them enumerated at the bottom of the webpage) I am still not able to reproduce the older results.

**Comment by abby-normal2** [comment]
thanks.  i'm working backward through the versions.  V10 is 'closer' to V8,
but still missing some details.
and strangely, V9.01 produces a mesh nearly identical to V13.72.

and for clarity, the only change i'm making is which version of the .exe is
called.  probably something
i'm doing wrong, but i remain confused.

**Comment by abby-normal2** [comment]
BTW ... thanks for your help.  your Poisson solver is the only method that
works on our data.

**Comment by abby-normal2** [comment]
so attempting to remove all other sources of variation, i run this code snippet which executes the chosen .exe on a pre-existing non-changing input file:


 system('PoissonRecon_V_1372.exe --in testinput3.ply --out testoutput3.ply --depth 5 --pointWeight 4 --samplesPerNode 10');
%system('PoissonRecon.x64_V8.exe --in testinput3.ply --out testoutput3.ply --depth 5 --pointWeight 4 --samplesPerNode 10');

clear vertex;
clear face;

[vertex,face] = read_ply2('testoutput3.ply');

the mesh produced by the two .exe choices is here (V8 on the left, V13.72 on the right)
![figure_for_GitHub](https://user-images.githubusercontent.com/79552974/109200469-80194f80-7755-11eb-8b76-40a443eb22a6.JPG)

**Comment by mkazhdan** [comment]
Yep. Setting --degree 2 (which was the default for version 8) and bumping up to --pountWeight 8 should get you closer to your original results.

**Comment by abby-normal2** [comment]
those two changes ... --degree 2 and --pointWeight 8 certainly alter the output mesh in V13.72, but for reasons i clearly
don't understand, V8 with  "--depth 5 --pointWeight 4 --samplesPerNode 10" is a much better fit to our
typical input data.  so i guess i'm just gonna have to stay away from the low density regions which trigger the bug.

thanks again for your effort.
