### ISSUE TITLE
Crash in ThreadPool::Parallel_for

### ISSUE THREAD

**Issue by brianm-sra** [mkazhdan/PoissonRecon#182]
I have been working on a modified version for Linux, with a library built, and separate test app that calls the library.
Most of the actual logic (math, algorithms) is the same, however.
In my current version, I am seeing crashes at the very end when the test app is exiting.
I tried to address any obvious causes, and am using "valgrind" tool to assist in examining specific issues
related to memory allocation issues, etc.
One trace I see follows below.

Any ideas about this?

MyMiscellany.h:373 is in Parallel_for , line
`_DoneWithWork.wait( lock , [&]( void ){ return _RemainingTasks==0; } );`

==6892== Process terminating with default action of signal 2 (SIGINT)
==6892==    at 0x56C09F3: futex_wait_cancelable (futex-internal.h:88)
==6892==    by 0x56C09F3: __pthread_cond_wait_common (pthread_cond_wait.c:502)
==6892==    by 0x56C09F3: pthread_cond_wait@@GLIBC_2.3.2 (pthread_cond_wait.c:655)
==6892==    by 0x59898BB: std::condition_variable::wait(std::unique_lock<std::mutex>&) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25)
==6892==    by 0x52C300C: void std::condition_variable::wait<ThreadPool::Parallel_for(unsigned long, unsigned long, std::function<void (unsigned int, unsigned long)> const&, ThreadPool::ScheduleType, unsigned long)::{lambda()#4}>(std::unique_lock<std::mutex>&, ThreadPool::Parallel_for(unsigned long, unsigned long, std::function<void (unsigned int, unsigned long)> const&, ThreadPool::ScheduleType, unsigned long)::{lambda()#4}) (condition_variable:99)
==6892==    by 0x52BF3BD: ThreadPool::Parallel_for(unsigned long, unsigned long, std::function<void (unsigned int, unsigned long)> const&, ThreadPool::ScheduleType, unsigned long) (MyMiscellany.h:373)
==6892==    by 0x52D1E99: unsigned long FEMTreeInitializer<3u, float>::Initialize<VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >(RegularTreeNode<3u, FEMTreeNodeData, unsigned short>&, FEMTreeInitializer<3u, float>::InputPointStream<VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >::StreamType&, int, std::vector<NodeAndPointSample<3u, float>, std::allocator<NodeAndPointSample<3u, float> > >&, std::vector<FEMTreeInitializer<3u, float>::InputPointStream<VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >::DataType, std::allocator<FEMTreeInitializer<3u, float>::InputPointStream<VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >::DataType> >&, bool, Allocator<RegularTreeNode<3u, FEMTreeNodeData, unsigned short> >*, std::function<void (RegularTreeNode<3u, FEMTreeNodeData, unsigned short>&)>, std::function<float (Point<float, 3u> const&, FEMTreeInitializer<3u, float>::InputPointStream<VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >::DataType&)>) (FEMTree.Initialize.inl:203)
==6892==    by 0x52C89D7: void Execute<float, VertexFactory::EmptyFactory<float>, 5u, 5u, 5u>(UIntPack<5u, 5u, 5u>, VertexFactory::EmptyFactory<float> const&) (PoissonRecon.cpp:542)
==6892==    by 0x52B9AD3: PoissonRecon::runPoissonRecon(std::vector<VectorTypeUnion<float, Point<float, 3u>, VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > >, std::allocator<VectorTypeUnion<float, Point<float, 3u>, VectorTypeUnion<float, Point<float, 3u>, EmptyVectorType<float> > > > >&, char*) (PoissonRecon.cpp:962)
==6892==    by 0x1252F4: PoissonReconApp::testPoissonRecon(char*, char*) (PoissonReconApp.cpp:152)
==6892==    by 0x125502: main (PoissonReconApp.cpp:203)
DEBUG (PoissonRecon.cpp): before setting modelToUnitCube, Width.value==0.000000, Scale.value==1.100000, Depth.value==8==6892== 
==6892== HEAP SUMMARY:
==6892==     in use at exit: 2,191,643 bytes in 130 blocks

**Comment by brianm-sra** [comment]
It's possible this is a "red herring" and not my main issue.

If nothing obvious comes to mind, I'll continue debugging my issue(s).

**Comment by mkazhdan** [comment]
Unfortunately, nothing comes to mind.

**Comment by brianm-sra** [comment]
I fixed some other problem(s) in my code, and it looks like it is not crashing anymore.
I think the above is probably a non-issue.
