### ISSUE TITLE
Question about CoredMeshData, CoredFileMeshData, etc.

### ISSUE THREAD

**Issue by brianm-sra** [mkazhdan/PoissonRecon#183]
In my local copy based on your code, simplified to always use ASCII and PolygonMesh
based on input data consisting of only points and normals,
I am now attempting to modify the PoissonRecon.cpp
methods ExtractMesh and Execute to return the generated polygon mesh as a data structure in memory
that can be exposed through my a library API method I created (public runPoissonRecon).

I am having some trouble getting the right syntax because of (a) CoredMeshData is a virtual class,
(b) use of templates, (c) use of typedefs/typenames.

I see that there is a subclass of CoredMeshData called CoredFileMeshData which is constructed
and used for writing to the Out PLY file.  I don't really want to return a CoredFileMeshData as I will
eventually get rid of the output PLY file in a later version (or isolate it for debugging verification purposes).

I am experimenting with defining

template< typename Real , typename SetVertexFunction , typename InputSampleDataType , typename VertexFactory , unsigned int ... FEMSigs >
CoredMeshData< typename VertexFactory::VertexType , node_index_type >* ExtractMesh

It has to be a pointer because CoredMeshData is virtual and can't be returned by itself in C++,
it must be a pointer or a reference.

but then having some compile time issues when trying to wire up the Execute method
to pass this mesh along as its return also, and how to call the modified Execute method.

Also there seem to be two different VertexFactory definitions, the typename in template,
and the namespace in VertexFactory.h / VertexFactory.inl

Any suggestions on the best way to do something like this ?

**Comment by mkazhdan** [comment]
To be clear, the CoredFiledMeshData is not, strictly speaking, for writing stuff out to .ply files. It's a way for representing the polygon mesh data in a way that keeps only a subset of the data in memory while keeping the rest on (file) storage. The idea being that if you break up 3D space into blocks and want to run marching cubes, you can do it by running it on the blocks individually. In doing so, the geometry for the individual blocks can mostly be stored on disk, as it not needed for processing the other blocks. However, the geometry that is generated on the _boundary_ of the blocks does need to be shared between blocks (e.g. to ensure that geometry is not duplicated and that the mesh remains water-tight).
The CoredFiledMeshData does this by storing the geometry interior to the blocks on disk, while keeping the geometry at the block boundaries in RAM. (You could keep everything in RAM, if you like, by using the CoredVectorMeshData class.)

As for the dual use of "VertexFactory" e.g. in the function ExtractMesh, that's probably bad nomenclature. Though in the context of the function, "VertexFactory" becomes the type, not the namespace. (Typically the actual type is something along the lines of VertexFactory::Factory.)

**Comment by brianm-sra** [comment]
I got a version to compile and run as expected now
