### ISSUE TITLE
Boundary types options in V12 and V13.71 give different results in Poisson reconstruction

### ISSUE THREAD

**Issue by vestri** [mkazhdan/PoissonRecon#186]
Hi,
I would like to reconstruct the surface of a point cloud with free boundary type. I am satisfied with the results in v12 (used by cloudcompare) but results differ in last version v13.71 (I did not check in between).
Next is an image of Poisson results with the 3 boundary types and the 2 versions. Only Dirichlet is similar, I believe v12 using free boundary is correct too, but others might be incorrect.
![PoissonReconstructionV12-V13 71-comparison](https://user-images.githubusercontent.com/4747304/116210304-072d7880-a743-11eb-8ee0-a396e5c595c1.jpg)
I also give to you the cloud for checking.
[pain.zip](https://github.com/mkazhdan/PoissonRecon/files/6383055/pain.zip)
Thanks

**Comment by mkazhdan** [comment]
I see that the results are different. Can you explain what you prefer about the results of the earlier version?
Also, can you try running with a lower --pointWeight? Maybe "--pointWeight 0.125"?

**Comment by vestri** [comment]
Thanks for your reply,
what I am prefering in previous version is the ability to fill holes and to extrapolate at the boundaries because my final goal is to measure a volume. Extrapolation ability was what I was understanding by free boundary type.
I tried with a lower point weight and got what i wanted with pw=0. Is it correct to use poissonRecons with such a value or maybe there are better ways to extrapolate the surface?
Thanks a lot.
![PoissonReconstructionV13 71-pw-comparison](https://user-images.githubusercontent.com/4747304/116265956-ba19c880-a77b-11eb-8f29-b8786efa138d.jpg)

**Comment by mkazhdan** [comment]
There is definitely no problem with setting the point weight to zero. (This is what the original Poisson Reconstruction, i.e. not the screened Poisson Reconstruction, did and it is likely to be a bit faster.)
A word of warning however. Given the missing data, the reconstruction away from the samples is just a best-guess. As such, one should be hesitant about using global measures like volume to say something about the "true" surface when your samples don't cover the surface. (For example, as you have already noted, small changes to the parameters can cause large changes to the estimated volume.)

**Comment by vestri** [comment]
Yes, I am aware that missing data obtained by interpolation or extrapolation are just best-guesses.
Thanks a lot for your explanations.
