### ISSUE TITLE
Citing the software

### ISSUE THREAD

**Issue by gradywright** [mkazhdan/PoissonRecon#193]
How should the repo be cited in a journal article?

**Comment by mkazhdan** [comment]
I would recommend referencing the 2013 paper:
@Article{Kazhdan:TOG:2013,
  author = {Kazhdan, Michael and Hoppe, Hugues},
  journal = {ACM Transaction on Graphics},
  pages = {29:1--29:13},
  title = {Screened {Poisson} surface reconstruction},
  volume = {32},
  year = {2013}
}
And possibly the 2019 paper as well:
@article{Kazhdan:CGF:2019,
  author = {Kazhdan, Misha and Hoppe, Hugues},
  title = {An Adaptive Multigrid Solver for Applications in Computer Graphics},
  journal = {Computer Graphics Forum},
  volume = {38},
  number = {1},
  pages = {138-150},
  year = {2019}
}

**Comment by gradywright** [comment]
Got it, thanks!  Btw, The software is really nice.
