### ISSUE TITLE
Compiling using Docker and Ubuntu 16.04.7 LTS Image

### ISSUE THREAD

**Issue by Camuvingian** [mkazhdan/PoissonRecon#197]
I am wanting to compile the PoissonRecon code on a Linux/Umbuntu Docker Image (Ubuntu 16.04.7 LTS). In my Docker file, I am currently doing the simplest thing; copy the directories and build the Docket image, I then run the container, go into the OS and attempt to compile. The Docker file is below 

```
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        vim g++ make 

RUN apt-get install libjpeg-dev
RUN apt-get install libpng-dev
RUN apt-get install zlib1g-dev

COPY . .
COPY ./Makefile .
WORKDIR .
```

Then I navigate to the source directory and run the "make" command. This seems to get a fair way into the compilation process

`In file included from /usr/include/stdio.h:936:0,
                 from Src/PoissonRecon.cpp:40:
In function 'size_t fread(void*, size_t, size_t, FILE*)',
    inlined from 'static bool VertexFactory::VertexIO<Real>::ReadBinary(FILE*, VertexFactory::TypeOnDisk, size_t, Real*) [with Real = float]' at Src/VertexFactory.inl:148:46:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:293:71: warning: call to '__fread_chk_warn' declared with attribute warning: fread called with bigger size * nmemb than length of destination buffer
  return __fread_chk_warn (__ptr, __bos0 (__ptr), __size, __n, __stream);
                                                                       ^
/usr/bin/ld: cannot find -lmypng
collect2: error: ld returned 1 exit status`

There is no such package/library as "libmypng-dev" and I am struggling to resolve this issue, can anyone advise?

**Comment by mkazhdan** [comment]
The issue is that the code uses an older version of the png library. So using the version installed from libpng-dev would cause linker errors.
Instead, the source contains the code for constructing the older version of the png library.
In particular, the Makefile in the directory "PNG" should generate a library "libmypng.a" in the "Bin/Linux" directory.
The Makefile in the root directory should call the Makefile in the "PNG" directory, make the "libmypng.a" file, and then link to that.

After running the Makefile, can you see "libmypng.a" in Bin/Linux?

**Comment by Camuvingian** [comment]
Understood, thanks for getting back to me so promptly and sorry for my own late reply. I will look at resolving this over the weekend and feed back. I am happy to provide my Docker files should Docker support be something you'd like to consider.

**Comment by Camuvingian** [comment]
Hi @mkazhdan, I have build the Docker image and executed the Makefile, unfortunately this does not work by default. I have found instead of using `-I.` I have to manually make each PNG/JPEG/ZLIB by 

`
cd ./PNG 
make
`

then I have to include these directories in the command 

`
g++ -c -o Bin/Linux/PoissonRecon.o -fopenmp -Wno-deprecated -std=c++14 -pthread -Wno-invalid-offsetof -O3 -DRELEASE -funroll-loops -ffast-math -g -I. -I./PNG -I./JPEG -I./ZLIB Src/PoissonRecon.cpp
`

This command completes and I get my PoissonRecon object file, ready for the next step. However, when I now run 

`
g++ -pthread -o Bin/Linux/PoissonRecon Bin/Linux/PoissonRecon.o -LBin/Linux/ -lgomp -lstdc++ -lpthread -O3 -g -ljpeg -lmypng -lz
`

I get the following

> /usr/bin/ld: cannot find -ljpeg
> /usr/bin/ld: cannot find -lz
> collect2: error: ld returned 1 exit status
> Makefile:153: recipe for target 'Bin/Linux/PoissonRecon' failed

I then use 

`
apt-get install libjpeg-dev
apt-get install libpng-dev
apt-get install zlib1g-dev
`

And run 

`
g++ -pthread -o Bin/Linux/PoissonRecon Bin/Linux/PoissonRecon.o -LBin/Linux/ -lgomp -lstdc++ -lpthread -O3 -g -ljpeg -lmypng -lz
`

Once more and now I get 

> Bin/Linux/PoissonRecon.o: In function `JPEGWriter::JPEGWriter(char const*, unsigned int, unsigned int, unsigned int, unsigned int)':
> /src/Src/JPEG.inl:93: undefined reference to `jpeg_std_error(jpeg_error_mgr*)'
> /src/Src/JPEG.inl:94: undefined reference to `jpeg_CreateCompress(jpeg_compress_struct*, int, unsigned long)'
> /src/Src/JPEG.inl:96: undefined reference to `jpeg_stdio_dest(jpeg_compress_struct*, _IO_FILE*)'
> /src/Src/JPEG.inl:103: undefined reference to `jpeg_set_defaults(jpeg_compress_struct*)'
> /src/Src/JPEG.inl:104: undefined reference to `jpeg_set_quality(jpeg_compress_struct*, int, unsigned char)'
> /src/Src/JPEG.inl:106: undefined reference to `jpeg_start_compress(jpeg_compress_struct*, unsigned char)'
> Bin/Linux/PoissonRecon.o: In function `JPEGWriter::nextRow(unsigned char const*)':
> /src/Src/JPEG.inl:118: undefined reference to `jpeg_write_scanlines(jpeg_compress_struct*, unsigned char**, unsigned int)'
> Bin/Linux/PoissonRecon.o: In function `JPEGWriter::nextRows(unsigned char const*, unsigned int)':
> /src/Src/JPEG.inl:126: undefined reference to `jpeg_write_scanlines(jpeg_compress_struct*, unsigned char**, unsigned int)'
> Bin/Linux/PoissonRecon.o: In function `JPEGReader::nextRow(unsigned char*)':
> /src/Src/JPEG.inl:83: undefined reference to `jpeg_read_scanlines(jpeg_decompress_struct*, unsigned char**, unsigned int)'
> Bin/Linux/PoissonRecon.o: In function `JPEGReader::~JPEGReader()':
> /src/Src/JPEG.inl:75: undefined reference to `jpeg_finish_decompress(jpeg_decompress_struct*)'
> /src/Src/JPEG.inl:76: undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
> Bin/Linux/PoissonRecon.o: In function `JPEGWriter::~JPEGWriter()':
> /src/Src/JPEG.inl:110: undefined reference to `jpeg_finish_compress(jpeg_compress_struct*)'
> /src/Src/JPEG.inl:111: undefined reference to `jpeg_destroy_compress(jpeg_compress_struct*)'
> Bin/Linux/PoissonRecon.o: In function `JPEGReader::~JPEGReader()':
> /src/Src/JPEG.inl:75: undefined reference to `jpeg_finish_decompress(jpeg_decompress_struct*)'
> /src/Src/JPEG.inl:76: undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
> Bin/Linux/PoissonRecon.o: In function `JPEGWriter::~JPEGWriter()':
> /src/Src/JPEG.inl:110: undefined reference to `jpeg_finish_compress(jpeg_compress_struct*)'
> /src/Src/JPEG.inl:111: undefined reference to `jpeg_destroy_compress(jpeg_compress_struct*)'
> Bin/Linux/PoissonRecon.o: In function `JPEGReader::GetInfo(char const*, unsigned int&, unsigned int&, unsigned int&)':
> /src/Src/JPEG.inl:27: undefined reference to `jpeg_std_error(jpeg_error_mgr*)'
> /src/Src/JPEG.inl:35: undefined reference to `jpeg_CreateDecompress(jpeg_decompress_struct*, int, unsigned long)'
> /src/Src/JPEG.inl:36: undefined reference to `jpeg_stdio_src(jpeg_decompress_struct*, _IO_FILE*)'
> /src/Src/JPEG.inl:38: undefined reference to `jpeg_read_header(jpeg_decompress_struct*, unsigned char)'
> /src/Src/JPEG.inl:43: undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
> /src/Src/JPEG.inl:31: undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
> Bin/Linux/PoissonRecon.o: In function `JPEGReader::JPEGReader(char const*, unsigned int&, unsigned int&, unsigned int&)':
> /src/Src/JPEG.inl:55: undefined reference to `jpeg_std_error(jpeg_error_mgr*)'
> /src/Src/JPEG.inl:59: undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
> /src/Src/JPEG.inl:63: undefined reference to `jpeg_CreateDecompress(jpeg_decompress_struct*, int, unsigned long)'
> /src/Src/JPEG.inl:64: undefined reference to `jpeg_stdio_src(jpeg_decompress_struct*, _IO_FILE*)'
> /src/Src/JPEG.inl:66: undefined reference to `jpeg_read_header(jpeg_decompress_struct*, unsigned char)'
> /src/Src/JPEG.inl:67: undefined reference to `jpeg_start_decompress(jpeg_decompress_struct*)'
> collect2: error: ld returned 1 exit status
> Makefile:153: recipe for target 'Bin/Linux/PoissonRecon' failed

scr is the base directory containing my Makefile, the Src/PNG/JPEG and ZLIB directories.

**Comment by Camuvingian** [comment]
Note, my Bin/Linux directory contains 

> PoissonRecon.o  inflate.o   jcmainct.o  jdapistd.o  jdmaster.o  jidctflt.o  libmypng.a  pngrtran.o  trees.o
> adler32.o       inftrees.o  jcmarker.o  jdatadst.o  jdmerge.o   jidctfst.o  libmyz.a    pngrutil.o  uncompr.o
> ckconfig.o      infutil.o   jcmaster.o  jdatasrc.o  jdphuff.o   jidctint.o  png.o       pngset.o    zutil.o
> compress.o      jcapimin.o  jcomapi.o   jdcoefct.o  jdpostct.o  jidctred.o  pngerror.o  pngtest.o
> crc32.o         jcapistd.o  jcparam.o   jdcolor.o   jdsample.o  jmemmgr.o   pnggccrd.o  pngtrans.o
> deflate.o       jccoefct.o  jcphuff.o   jddctmgr.o  jdtrans.o   jmemnobs.o  pngget.o    pngvcrd.o
> gzio.o          jccolor.o   jcprepct.o  jdhuff.o    jerror.o    jquant1.o   pngmem.o    pngwio.o
> infblock.o      jcdctmgr.o  jcsample.o  jdinput.o   jfdctflt.o  jquant2.o   pngpread.o  pngwrite.o
> infcodes.o      jchuff.o    jctrans.o   jdmainct.o  jfdctfst.o  jutils.o    pngread.o   pngwtran.o
> inffast.o       jcinit.o    jdapimin.o  jdmarker.o  jfdctint.o  libmyjpg.a  pngrio.o    pngwutil.o

**Comment by Camuvingian** [comment]
I have found the solution - I will follow up shortly.
