### ISSUE TITLE
segment fault(core dumped)

### ISSUE THREAD

**Issue by captain-xuwenqiang** [mkazhdan/PoissonRecon#198]
Hello. ,The program runs well at first. After a period of time, an error occurred make program terminate: segment fault(core dumped)

I generated a core file to check the source of the error. The contents of core file are as follows:
![20210816013412](https://user-images.githubusercontent.com/68489582/129487676-91f812bf-b8d5-4381-a1ac-f63722382917.jpg)

Can you tell me what caused the termination of the program(segment fault(core dumped)). Thank you

**Comment by mkazhdan** [comment]
Looks like a bad memory access. 
1. Is the problem reproducible?
2. Does it persist if you only use one thread?
3. Would you be able to share the data?

**Comment by captain-xuwenqiang** [comment]
@mkazhdan Thank you for your response. 
1. problem is reproducible. For example, Sometimes the program will terminate at 80%, sometimes 30%. The time of termination is not repeated.

2.Yes, but only use one thread make error occur less frequently.

3.The data we use here is KITTI dataset, the website is 'http://www.cvlibs.net/datasets/kitti/raw_data.php'

**Comment by mkazhdan** [comment]
Specifically, which dataset did you use and what command line arguments did you specify when running the reconstruction?

**Comment by captain-xuwenqiang** [comment]
@mkazhdan Thank you.

We set the depth to 10, and only use one thread. Now the problem has been solved.
