### ISSUE TITLE
PLY data storage

### ISSUE THREAD

**Issue by jimmyd95** [mkazhdan/PoissonRecon#206]
I could not find where the elements are stored in the Poisson algorithm. The Nodes themselves don't seem to have such storage and the execution area didn't access these vertexes either...... where did it go????

ply
format binary_little_endian 1.0
element vertex
property float x
property float y
property float z
property float r
property float g
property float b
property float nx
property float ny
property float nz
end_header
123 123 123 0.5 0.2 0.8 23 25 36 (Where did the algorithm access these following lines? and where did it store it?)
.
.
.
136 111 98 0.25 0.8 0.1 24 26 34

The headers are stored and classified, yet the elements themselves can't be seen anywhere...... where did all of them go? And how can I track it in the regularTree/FEMTree?

**Comment by mkazhdan** [comment]
The positions and normals are pulled from the data separately, as these are needed to define the implicit function.
The remaining data, if it exists, is read as auxiliary data (described by "auxDataFactory" in the Execute call in PoissonRecon.cpp).
When the point cloud is read in, this data is read in and stored the sampleData object.
Internally, it is accumulated within the octree leaves, which store the accumulated/average value within the cell.

Then, when the iso-surface is extracted, the data is interpolated to the iso-vertices and assigned as properties.

**Comment by jimmyd95** [comment]
I'll look deeper into the sampledData object and the auxDataFactory. Thanks a lot!!

**Comment by jimmyd95** [comment]
My data said there are 2 million pointCount, yet only 400 thousand samples in sampleData with a capacity of 700 thousand unsigned_int64...... The processing does not add up (I couldn't find where you shrank down the point size), it seemed like you either built a bounding box around the points and referred to it as the sampleData, or during the process of reading in the points, you extrapolated base points for a bundle of points (or am I not right on both accounts......).

**Comment by mkazhdan** [comment]
The shrinking is likely due to the fact that point data is stored with octree (leaf) nodes and, in general, you will have multiple samples falling into the same node. You have some control over this by using a combination of the --depth flag and the --samplesPerNode flag.

**Comment by jimmyd95** [comment]
Ah I see, so it has been interpolated into different set of nodes with perhaps multiple sets of point for one node/leaf node...... Is it possible to extract point data or related elements from the nodes? It doesn't seem like the nodes themselves are storing anything related to the point data. Is it referencing to a different tree or object for these data?

**Comment by mkazhdan** [comment]
The accumulated information is stored in the "sampleData" object which is a vector in one-to-one correspondence with the vector "samples".
For a given index i, the entry in  (*samples)[i] stores the node of the octree containing the data, and the total count of points falling within that node. You can then use that count to divide the entry in (*sampleData)[i] to get the average sample information within that node.

**Comment by jimmyd95** [comment]
Alright I need to thoroughly work on the details of that (might come back for more questions, but I think I got it)...... Huge thanks!!! All those guidences are of great help, thank you so much, I just can't stress it enough.

**Comment by jimmyd95** [comment]
So I am back...... after two days.

I went through a thorough dive into samples, sampleData, auxFactoryData, FEMTree.inl/FEMTree.h node. I still couldn't find anything that remotely relates to the point data...... The images shown are the *samples and *sampleData debug watch, there are no points (or point data) in the nodes of the samples object, nor any in sampleData, the coords (I assume it meant coordinates?) do not match with the point coordinates either. The FEMTree nodes themselves don't have anything that corresponds with the point data. I thought nodeData would be useful, but almost all of the nodeData comes back with a -1 value (which begs for more questions). The offset variable is a bit curious, but I don't know what these numbers are for (the offsets are huge, like a few thousands, I don't have any data value that fits the profile. Perhaps it's an integration or derivative of the points of the nodes? I didn't seem to find an offset in your paper, so I am not sure how the math works), so I can't make any assumptions based on that either......

Am I looking at the wrong samples/sampleData? I thought the PoissonRecon.cpp main() is the right spot to overwatch everything. How did all these millions of lines of data just vanish??? I don't understand......

![874c0dc39a4df8b1d75a67e3d60d48c](https://user-images.githubusercontent.com/16414366/141669966-0095dc17-8955-47db-b96f-40fbb95cb514.png)
![cafb8da243eed507c7fbd6541ece2ae](https://user-images.githubusercontent.com/16414366/141669967-0eee9ff6-b1e5-421a-83c4-4329b676c363.png)

PS. Thanks for patiently answering all of my questions and taking up my frustrations......

**Comment by gipeto** [comment]
Hi @jimmyd95. My understanding is that you are trying to find coordinates similar of your input pointcloud in the samples data is that correct ? 
I don't know the details about the storage conventions in the samples datastructure, but on read the point data gets rescaled to fit in the unit cube.
In the PoissonRecon app the direct and inverse transform are tracked by these two variables: https://github.com/mkazhdan/PoissonRecon/blob/455ea0dbe651f31bf6985ff2891becff1dd79c72/Src/PoissonRecon.cpp#L528
My guess is that you will have to apply the `unitCubeToModel` transform to the samples coordinates in order to compare them with your input points (or equivalently apply the `modelToUnitCube` transform to your input cloud).

**Comment by jimmyd95** [comment]
Yes, you're correct. I wanted to find the correlating data from the nodes and somehow it was transmutated into something else. I couldn't for the life of me find the transformation...... 

I did wonder what the unitCubeToModel does, but it didn't seem like it's transferring the data into the nodes, so I assumed it to be a flag or some sort.

Would you care to walk me through how to transfer it back to the data sets? All I wanted to know is how I can track back to the sets...... It seemed like I'm not observent enough to spot the problem

**Comment by jimmyd95** [comment]
> Hi @jimmyd95. My understanding is that you are trying to find coordinates similar of your input pointcloud in the samples data is that correct ? I don't know the details about the storage conventions in the samples datastructure, but on read the point data gets rescaled to fit in the unit cube. In the PoissonRecon app the direct and inverse transform are tracked by these two variables:
> 
> https://github.com/mkazhdan/PoissonRecon/blob/455ea0dbe651f31bf6985ff2891becff1dd79c72/Src/PoissonRecon.cpp#L528
> 
> 
> My guess is that you will have to apply the `unitCubeToModel` transform to the samples coordinates in order to compare them with your input points (or equivalently apply the `modelToUnitCube` transform to your input cloud).

I'll read into the uniCubeToModel and modelToUnitCube. There's also voxelToUnitCube...... This is quite confusing. I was hoping to extract one point and its data value during the tree building process. It doesn't seem like it's letting me go through this entire thing easily......

**Comment by gipeto** [comment]
I think you could intercept the transformed input points in this callback and store them into a vector or a file for your comparison: https://github.com/mkazhdan/PoissonRecon/blob/455ea0dbe651f31bf6985ff2891becff1dd79c72/Src/PoissonRecon.cpp#L623

In this small example I am just printing the samples coordinates before and after being transformed:

```
auto XFormFunctor = [&]( InputSampleType &p ){ 
			auto inputSamplePosition = p.template get<0>();
			std::cout << "Original point (x,y,z): ("<< inputSamplePosition[0] << "," << inputSamplePosition[1]<< "," << inputSamplePosition[2] << ")" << std::endl;
			
			p = _modelToUnitCube( p );
			
			auto transformedInputSamplePosition = p.template get<0>();
			std::cout << "Transformed point (x,y,z): ("<< transformedInputSamplePosition[0] << "," << transformedInputSamplePosition[1]<< "," << transformedInputSamplePosition[2] << ")" << std::endl;
			};

```

**Comment by jimmyd95** [comment]
> I think you could intercept the transformed input points in this callback and store them into a vector or a file for your comparison: https://github.com/mkazhdan/PoissonRecon/blob/455ea0dbe651f31bf6985ff2891becff1dd79c72/Src/PoissonRecon.cpp#L623
> 
> In this small example I am just printing the samples coordinates before and after being transformed:
> 
> ```
> auto XFormFunctor = [&]( InputSampleType &p ){ 
> 			auto inputSamplePosition = p.template get<0>();
> 			std::cout << "Original point (x,y,z): ("<< inputSamplePosition[0] << "," << inputSamplePosition[1]<< "," << inputSamplePosition[2] << ")" << std::endl;
> 			
> 			p = _modelToUnitCube( p );
> 			
> 			auto transformedInputSamplePosition = p.template get<0>();
> 			std::cout << "Transformed point (x,y,z): ("<< transformedInputSamplePosition[0] << "," << transformedInputSamplePosition[1]<< "," << transformedInputSamplePosition[2] << ")" << std::endl;
> 			};
> 
> ```
> 

Let me check into it and get back to you really quick. Thanks for the info.

The problem is that I want to interpret the data within the treeNode or the construction of treeNode, so that might need some tweek I believe.

Thanks!!

**Comment by mkazhdan** [comment]
After the line in PoissonRecon.cpp that reads:
		unitCubeToModel = modelToUnitCube.inverse();
Try adding the following:
		if( sampleData )
		{
			for( unsigned int i=0 ; i<samples->size() ; i++ )
			{
				double weight = (*samples)[i].sample.weight;
				Point< double , 3 > p = (*samples)[i].sample.data / weight;
				InputSampleDataType sData = (*sampleData)[i] / weight;

				std::cout << "Position: " << unitCubeToModel * p << std::endl;
				std::cout << "Normal: " << sData.get<0>() << std::endl;
				std::cout << "Aux Data: ";
				auxDataFactory.writeASCII( stdout , sData.get<1>() );
				std::cout << std::endl;
			}
		}

**Comment by jimmyd95** [comment]
Thank you!! I'll test the piece first thing in the morning.

**Comment by jimmyd95** [comment]
How exactly is sData displaying its data? I can neither extract the normals from the tuple sData.get<0>(), nor can I extract the auxiliary data from the sData.get<1>().

Assuming that I am right...... The DataType is wrapped around a vertexType tuple, then an inputPoint array that is based on a FEMTree typename.........

FEMTreeInitializer<Dim, Real>::InputPointStream<VectorTypeUnion<Real, VertexFactory::NormalFatory<Real, Dim>::VertexType, AuxDataFactory::VertexType>>::DataType InputSampleDataType;

![image](https://user-images.githubusercontent.com/16414366/141874649-52813ae8-f0e3-4f5c-8734-6c7a7454977a.png)

Is there a way to actually extract individual elements...... Why couldn't I after all this effort figure out a sane way to get the int value out of just one tuple. Where did you store all these operations? Why can't I find them anywhere in the project solution?

**Comment by mkazhdan** [comment]
The normal is of type Point< Real , 3 > and is extractable using sData.get<0>();
The other information is stored as a dynamically allocated Point< Real > which you can get the size of using the Point< Real >::dim( void ) method and whose entries you can access using the square brackets.
(Note that the type for the auxiliary type cannot be hard-coded since is a template parameter and may be a Point< Real > or it may be something else. Hence the "if constexpr".)

		if( sampleData )
		{
			std::cout << "Samples: " << samples->size() << " / " << sampleData->size() << std::endl;
			for( unsigned int i=0 ; i<samples->size() ; i++ )
			{
				Real weight = (*samples)[i].sample.weight;
				Point< Real , 3 > p = (*samples)[i].sample.data / weight;
				InputSampleDataType sData = (*sampleData)[i] / weight;
				Point< Real , 3 > n = sData.get<0>();

				std::cout << "Position: " << unitCubeToModel * p << std::endl;
				std::cout << "Normal: " << n << std::endl;
				if constexpr( std::is_same< AuxDataFactory::VertexType , Point< Real > >::value )
				{
					Point< Real > auxData = sData.get<1>();
					std::cout << "Aux Data[" << auxData.dim() << "]:";
					for( unsigned int i=0 ; i<auxData.dim() ; i++ ) std::cout << " " << auxData[i];
					std::cout << std::endl;
				}
			}
		}

**Comment by jimmyd95** [comment]
My god how did you manage to construct such a magnificent piece of code...... I honestly didn't know what constexpr is before you introduced it to me.

So by introducing:
>  if constexpr( std::is_same< AuxDataFactory::VertexType , Point< Real > >::value )

I am able to "solidify" the template parameter of sData.get<1>() and make it any type I wish it to be...... Am I understanding this correctly? I believe that solved the problem that's been haunting me for literally weeks...... Thank you so much

**Comment by mkazhdan** [comment]
In general, when you have templated code, the compiler compiles a separate version for each parameter it's used with. 

Since the AuxDataFactory is a template parameter, the C++ compiler knows at compile-time what it's type is. So the "if constexpr" is a statement is saying "if, at compile time, you determine that the conditional is true for the particular template parameter type, include the code in braces for that compiled version." This is necessary because if the auxiliary data were not of type Point<Real> the code inside the if statement would not make sense/compile. 

It is definitely supported in C++-17 (making code cleaner and eliminating the need for ugly sfinae). I am not sure if it was supported in C++-14, though I think not.

**Comment by jimmyd95** [comment]
I might still need some more in-depth understanding of this, but wow, thank you so much for the thorough explanation. Hopefully, this will be the end of my node-data-storage question/s...... Again, thank you so much for the guidance. It has been of great help!!
