### ISSUE TITLE
Failed to read the ply files wrote by PCL 1.12

### ISSUE THREAD

**Issue by cdb0y511** [mkazhdan/PoissonRecon#207]
The PCL 1.12 adds "element face 0" to the ply file header. And the latest PoissonRecon failed to read these ply files. 
The original issue is here
https://github.com/PointCloudLibrary/pcl/issues/5050
I hope you can fix it soon.
Thanks,

**Comment by mkazhdan** [comment]
To be clear, the problem isn't so much that there is a line "element face 0". It's that the ply reader expects a list of properties after a declaration of an "element" and I'm guessing that the file you have does not have those.

**Comment by cdb0y511** [comment]
> To be clear, the problem isn't so much that there is a line "element face 0". It's that the ply reader expects a list of properties after a declaration of an "element" and I'm guessing that the file you have does not have those.

Thanks for the quick reply.
The input ply file indeed does not include "element face". But "element face 0" is added automatically if I use the default ply write function on PCL 1.12. It seems for compatible for VTK (  // vtk requires face entry to load PLY)
https://github.com/PointCloudLibrary/pcl/blob/7f87657e8f796373852ff7f80228a1573239de8d/io/src/ply_io.cpp#L795
I wonder if you can make the poissionRecon compatible with the new PLY header on PCL 1.12.

**Comment by mkazhdan** [comment]
I can try to look into it. But the question stands, why doesn't PCL have a line of the form "property..." after it declares that there are zero faces? (It doesn't make sense to me that it should declare an element without describing its properties. Though I understand that if there are zero faces, the list of properties won't make a difference.)

**Comment by cdb0y511** [comment]
> I can try to look into it. But the question stands, why doesn't PCL have a line of the form "property..." after it declares that there are zero faces? (It doesn't make sense to me that it should declare an element without describing its properties. Though I understand that if there are zero faces, the list of properties won't make a difference.)

Agreed, I link this issue to PCL.

**Comment by cdb0y511** [comment]
I am glad to hear that.
Thanks
