### ISSUE TITLE
What is the mathematical form for PointInterpolant?

### ISSUE THREAD

**Issue by trisct** [mkazhdan/PoissonRecon#209]
Hi,

I am wondering what the exact mathematical expression of the optimization objective is in PointInterpolant. Is there any paper/textbook I can refer to? Thanks!

**Comment by mkazhdan** [comment]
In addition to what is described in equation 3 of https://www.cs.jhu.edu/~misha/MyPapers/ToG13.pdf ?

**Comment by trisct** [comment]
Yes, equation 3 in the TOG13 paper only describes data terms (values and gradients at given points), but the description of PointInterpolant says there is a laplacian smoothness term and a bilaplacian smoothness term. I wonder what they are. Sorry I don't have enough background on this.

**Comment by mkazhdan** [comment]
Are you referring to the executable for the smoothed signed distance reconstruction (SSDRecon)?

**Comment by trisct** [comment]
@mkazhdan No. I am referrring to the executable called `PointInterpolant`:

In the README:

PointInterpolant: Fits a function to a set of sample values and/or gradients by finding the coefficients of the function that minimize an energy composed of a point-wise interpolation term and Laplacian and bi-Laplacian smoothness terms

**Comment by trisct** [comment]
And if I want to use the program `PointInterpolant`, which paper should I cite, since it doesn't seem to be the code associated to any publication? Or should I just cite this repo?

**Comment by mkazhdan** [comment]
Ah. This had nothing to do with surface reconstruction. It's code for sparse data interpolation. (e.g. if you have a samples of a functions values, Laplacian, bilaplacian, and you want to find the function within the span of the octree basis that is the least-squares best fit).

**Comment by mkazhdan** [comment]
Also, you should just cite the repo.

**Comment by trisct** [comment]
@mkazhdan Thanks. But since I am trying to be rigorous here, can you provide the exact mathematical form of the energy function? That is, with what energy function do you define the result as a "best" fit?

**Comment by mkazhdan** [comment]
Sure. Hoping that LaTex is OK.

Given the dimension D, suppose you have sets P = {(p_i,s_i)}\subset \R^D\times\R and Q = {(q_i,g_i)}\subset\R^D\times\R^D, you are looking for the function F within the span of functions defined by the octree that minimizes:
E(F) = v_w * \sum_{(p,s)\in P}(F(p)-s)^2 + g_w * \sum_{(q,g)\in Q}||\nabla F(q) - g||^2 + l_w * \int_\Omega ||\nabla F||^2 + b_w * \int_\Omega ||\Delta F||^2
where \Omega is the integration domain (roughly, the unit cube), v_w is the value weight, g_w is the gradient weight, l_w is the Laplacian  regularization weight, and b_w is the bi-Laplacian regularization weight.

Note that all of the calculation is done with respect to the domain \Omega, not the bounding box of the point set. In particular, when a scaling (and translation) transformation is applied to fit the data  into the unit cube, the inverse of the scaling transformation will be applied to the gradient constraint values.

**Comment by trisct** [comment]
Latex is perfectly OK. Thank you very much!

Only a small question remains: usually \Delta=\nabla^2 is called the Laplacian and \Delta^2=\nabla^4 is the biLaplacian. But in the energy function the Laplacian term involves merely \nabla and the biLaplacian term involves \nabla^2 (both seem to be missing a square over them). I assume this is because these two terms are named after rewriting them into a linear system using the Galerkin formulation? More specifically, minimizing ||\nabla^2 F||^2 amounts to solving a linear equation of the form \nabla^4 F=0, so you call it the biLaplacian term. Is this the correct understanding?

**Comment by mkazhdan** [comment]
Yes. That is correct. It is because the energy is using the squared norm of the gradient/Laplacian.

**Comment by trisct** [comment]
Thanks again. I have no further questions.
