### ISSUE TITLE
PoissonRecon.exe terminates due to 0xc000001d Exception

### ISSUE THREAD

**Issue by ceyhunco** [mkazhdan/PoissonRecon#212]
Hi there,

first of all, thanks @mkazhdan for the great work. 

I have been testing PoissonRecon at different machines and I found out that it terminates with a similar event log on some 3 machines I use. Every one of these machines has 16g ram, and I installed the c++ redist environment.  

I tested also several older versions down to 11 and the result was the same. 

I use standart horse.txt from the given examples.

Here is the command I use:
PoissonRecon.exe --in "horse.txt" --out "horse.ply" --depth 8 --density --performance --verbose

Here is the output screen:
![image](https://user-images.githubusercontent.com/8968382/147474229-c989aef6-61ad-4bbd-80c3-e5e9ceef4f6b.png)

Here is how the windows event log looks like:
![image](https://user-images.githubusercontent.com/8968382/147473826-5bf3bee7-d377-46a2-a5d3-eedc0f99a26a.png)

Searching for the 0xc000001d I found following:
https://stackoverflow.com/questions/32437899/c-unable-to-start-correctly-0xc000001d-opencv
maybe we are having a similar issue here?

I also tried to run ram check and harddisk check on the machines as it was recommended for 0xc000001d Exception but it did not work out.

Many thanks for your support,

Ceyhun

**Comment by mkazhdan** [comment]
Thanks for the pointer. Given the link, it seems like this is an issue with the project build settings not playing well with hardware. You may want to try to change the floating point model option and see if that resolves the issue. (What kind of CPU are you running this on?)

**Comment by ceyhunco** [comment]
Hi,

did not work on
-8 Core AMD FX-8320E (release date 2014)
-Intel® Xeon® Processor E3-1270 (8M Cache, 3.40 GHz) (release date 2011)
-Intel I7-2920 XM (release date 2011)

worked on: 
-8 Core Intel Core i7 9700K (release date 2018)
-amd ryzen threadripper 2990WX 32 core (release date 2018)

This pattern tells me somehow that poissonrecon tends not to run on older cpus. However it puzzles me to see how wide the range is.

Ceyhun

**Comment by mkazhdan** [comment]
Under "Properties" -> "C/C++" -> "Code Generation"
Can you change "Advanced Vector Extensions 2" to something simpler (or not at all)?

**Comment by ceyhunco** [comment]
works very well, thanks @mkazhdan 
this issue is related to #95
