### ISSUE TITLE
Issue About Poisson Reconstruction

### ISSUE THREAD

**Issue by JacobYeah** [mkazhdan/PoissonRecon#217]
Hi Professor,
I tried to learn code recently, and I wanted to figure out if the Poisson process could keep the UV coordinates.  After running the code, I found it can keep the UV coordinates so I want to make sure this conclusion. Another question is can you tell me which function is for calculating the mesh in Poisson Reconstruction? I totally confused because I found a function that may be the function I need. It is **ExtractMesh**. If possible, can you give some experience of texture mapping after Poisson reconstruction?

Looking forward to your reply！
Thank you so much!

**Comment by mkazhdan** [comment]
I'm not sure I follow the question. Are you asking if the method can output a surface with UV coordinates? If so, the answer is "yes, assuming the UV coordinates are reasonably continuous". E.g. the method will not work if you are using multi-chart parametrization (though then you would still have the problem of figuring out which texture chart you should be in).

**Comment by JacobYeah** [comment]
Thank you very much. Your reply has solved most questions of mine. The method can output a surface with UV but is it same as the input data's UV? 
And when I read the code. I wanted to figure out which function in the Poisson Reconstruction is for building triangular mesh. Is **function ExtractMesh**？

**Comment by mkazhdan** [comment]
It will not be identical.
And yes, the iso-surface extraction is done in ExtractMesh. Specifically, with the help of the IsoSurfaceExtractor::Extract function.

**Comment by JacobYeah** [comment]
Thank you so much! 
It's a great help to me.

**Comment by JacobYeah** [comment]
I forgot one question. I tried to find out which step change the UV.  I am not sure about which step, so can you tell me about that?

**Comment by mkazhdan** [comment]
I'm afraid I am not sure what you're asking.
What do you mean by "change the UV"? The UV values at the input samples are extrapolated into the volumetric grid and sampled there.

**Comment by JacobYeah** [comment]
Thank you for replying. That's my question which step does the extrapolating things?

**Comment by mkazhdan** [comment]
That's complicated. It's a combination of hierachical splatting at the beginning of the code with sampling/interpolation at the end (when the surface is extracted).

**Comment by JacobYeah** [comment]
Thank you so much. It helps a lot.
