### ISSUE TITLE
Can't understand the function :  NonLinearUpdateWeightContribution

### ISSUE THREAD

**Issue by jinneigeyu** [mkazhdan/PoissonRecon#227]
I saw  some poly functions in  "NonLinearUpdateWeightContribution"

```
int i, j, k;
TreeOctNode::Neighbors& neighbors = neighborKey.setNeighbors(node);
double x, dxdy, dx[DIMENSION][3];
double width;
Point3D<Real> center;
Real w;
node->centerAndWidth(center, w);
width = w;
for (i = 0; i < DIMENSION; i++)
	{
		x = (center.coords[i] - position.coords[i] - width) / width;
		dx[i][0] = 1.125 + 1.500 * x + 0.500 * x * x;
		x = (center.coords[i] - position.coords[i]) / width;
		dx[i][1] = 0.750 - x * x;
		dx[i][2] = 1.0 - dx[i][1] - dx[i][0];
	}
```
and I don`t know what does x ,dxdy anddx mean , can you explain thanks

**Comment by mkazhdan** [comment]
x is the weight giving the position of the point relative to the left side of the cell. (Value in the range [0,1] and equal to 1 if it's all the way at the left side.)

dx are the values of the evaluation of the three quadratic B-splines supported on the x- coordinate of the point.

**Comment by jinneigeyu** [comment]
so ,  the coefficients of quadratic B-splines ( dx[i][j] )  can be modified at some conditions ?

**Comment by jinneigeyu** [comment]
> so , the coefficients of quadratic B-splines ( dx[i][j] ) can be modified at some conditions ?



> x is the weight giving the position of the point relative to the left side of the cell. (Value in the range [0,1] and equal to 1 if it's all the way at the left side.)
> 
> dx are the values of the evaluation of the three quadratic B-splines supported on the x- coordinate of the point.

so , the coefficients of quadratic B-splines ( dx[i][j] ) can be modified at some conditions ?

**Comment by mkazhdan** [comment]
Not sure what you mean by "can be modified at some conditions".

**Comment by whatseven** [comment]
If I understand it correctly, the first dimension of dx is the x,y, and z coordinates. But what is the second dimension? Is it the value of "x" in the nearby voxel? Or it is the first, and the second derivative of the 3-order box filter to form the L matrix in the paper.

What is the meaning of 1.125,1.500,0.500?

**Comment by mkazhdan** [comment]
Yep. The second index gives the values in adjacent voxels. 
The idea, if I recall, is to splat the contribution of the point using a second order B-slpline. The values are the coefficients of the piecewise quadratic within each voxel.

**Comment by whatseven** [comment]
Thanks for your response! 
So it is not about the gradient of the base function, right?
Is it necessary to interpret the contribution using nearby voxel? Or I can just use the single value and suffer from some precision lost.

**Comment by mkazhdan** [comment]
Correct, and yes. But the latter will result in worse reconstructions.

**Comment by whatseven** [comment]
I get it. Thanks for your explanation!

**Comment by lzhnb** [comment]
> x is the weight giving the position of the point relative to the left side of the cell. (Value in the range [0,1] and equal to 1 if it's all the way at the left side.)
> 
> dx are the values of the evaluation of the three quadratic B-splines supported on the x- coordinate of the point.

Thanks for your patient reply. And the value of `x` in the first state should be [-1.5, 0.5], right?
```cpp
x = (center.coords[i] - position.coords[i] - width) / width;
```
this state is equal to
```cpp
x = (center.coords[i] - position.coords[i]) / width - 1.0f;
```
the range `center.coords[i] - position.coords[i]` should be [-0.5, 0.5], thus the range of `x` should be [-1.5, -0.5] and the `x` is equal to -0.5 if the point at the left side.
In the same way, the range `x` in the next state:
```cpp
x = (center.coords[i] - position.coords[i]) / width;
```
is equal to the `x` in the first state `+1`. So the range should be [-0.5, 0.5] and this `x` is equal to 0.5 if the point at the left side.

**Comment by mkazhdan** [comment]
I believe that's right.

**Comment by jay-z20** [comment]
> I saw some poly functions in "NonLinearUpdateWeightContribution"
> 
> ```
> int i, j, k;
> TreeOctNode::Neighbors& neighbors = neighborKey.setNeighbors(node);
> double x, dxdy, dx[DIMENSION][3];
> double width;
> Point3D<Real> center;
> Real w;
> node->centerAndWidth(center, w);
> width = w;
> for (i = 0; i < DIMENSION; i++)
> 	{
> 		x = (center.coords[i] - position.coords[i] - width) / width;
> 		dx[i][0] = 1.125 + 1.500 * x + 0.500 * x * x;
> 		x = (center.coords[i] - position.coords[i]) / width;
> 		dx[i][1] = 0.750 - x * x;
> 		dx[i][2] = 1.0 - dx[i][1] - dx[i][0];
> 	}
> ```
> 
> and I don`t know what does x ,dxdy anddx mean , can you explain thanks

hello，兄弟，搞懂了没有
我有疑问想请教一下，三次二阶B样条的系数在代码中怎么只有 3个？

**Comment by mkazhdan** [comment]
This is used to compute the "splat" of a sample into a 3x3x3 window around it's position. What you want is to evaluate the 2nd order b-spline in each of the 3x3x3 cells at the sample. But since the b-splines are tensor splines, it's suffices to know the values of the 1D b-splines. Which is what is stored in dx.

**Comment by hadoop73** [comment]
> This is used to compute the "splat" of a sample into a 3x3x3 window around it's position. What you want is to evaluate the 2nd order b-spline in each of the 3x3x3 cells at the sample. But since the b-splines are tensor splines, it's suffices to know the values of the 1D b-splines. Which is what is stored in dx.


- Thanks for your reply  
- First，About 1D b-splines I will show what I understand  
- Cox-de Boor defines  
![image](https://user-images.githubusercontent.com/7642067/206961788-da12812a-2701-4c7c-b516-838ee237fb1b.png)

-  we are going to get $N_{0,2},N_{1,2},N_{2,2}$ ?

```c++
for( int i=0 ; i<DIMENSION ; i++ )
{
  x = ( center[i] - position[i] - width ) / width;
  dx[i][0] = 1.125 + 1.500*x + 0.500*x*x; // 0.5*(x+1.5)^2
  dx[i][1] = -0.25 - 2. * x - x * x; // -(x+0.5)^2
  dx[i][2] = 1. - dx[i][1] - dx[i][0];
  // Note that we are splatting along a co-dimension one manifold, so uniform point samples
  // do not generate a unit sample weight.
  dx[i][0] *= SAMPLE_SCALE;
}
```

- now, we set 
 
$$\begin{cases} dx[i][0]=N_{0,2} \\ 
dx[i][1]=N_{1,2} \\
 dx[i][2]=N_{2,2}=1-N_{0,2}-N_{1,2}
\end{cases}$$

- but I dont know what the knots $u_i$ are? How can I get  
 
$$\begin{cases}dx[i][0]=0.5\cdot (x+1.5)^2  \\ 
dx[i][1]=-(x+0.5)^2 \\ 
dx[i][2]=1-dx[i][1]-dx[i][0] 
\end{cases}$$ 

I confused couple of days

**Comment by mkazhdan** [comment]
Knots should be at integer locations

**Comment by hadoop73** [comment]
> Knots should be at integer locations

- but as I know if knots are `[0,1,2,3,4,5,6]`

![image](https://user-images.githubusercontent.com/7642067/207067292-cc221d71-c311-4201-9973-b163479ab2f2.png)

but the code is not the same

```c++
for( int i=0 ; i<DIMENSION ; i++ )
{
  x = ( center[i] - position[i] - width ) / width;
  dx[i][0] = 1.125 + 1.500*x + 0.500*x*x; // 0.5*(x+1.5)^2
  dx[i][1] = -0.25 - 2. * x - x * x; // -(x+0.5)^2
  dx[i][2] = 1. - dx[i][1] - dx[i][0];
  // Note that we are splatting along a co-dimension one manifold, so uniform point samples
  // do not generate a unit sample weight.
  dx[i][0] *= SAMPLE_SCALE;
}
```

**Comment by mkazhdan** [comment]
I believe you need to add in a shift.
The above equation considers the 2nd order B-spline as supported on the range [0,3] whereas the reconstruction code considers the support to be [-1,2]

**Comment by besthwang** [comment]
Dictionary  desscribe splat that  the sound made when something wet hits a surface.
What does mean splat here?
Could you explain thanks.

**Comment by mkazhdan** [comment]
"splat" refers to the process of distributing the value(s) of a sample to discrete nodes.
For example, using first-order B-splines, if the sample falls within a cell, you could distribute the value to the four corners of the cells using weights (that sum to one) defined through bilinear interpolation.
