### ISSUE TITLE
 The envelope hash no effect on the reconstruction results

### ISSUE THREAD

**Issue by hzhao1997** [mkazhdan/PoissonRecon#233]
Hi, thanks for you great work! I generate the envelope from visual hull point cloud by running `PoissonRecon.exe --in pointcloud_surface.ply --out envelope.ply` and then run `PoissonRecon.exe --in pointcloud_depth.ply --envelope  envelope.ply --out mesh.ply`. But, it seems that the envelope hash no effect on the reconstruction results. Below are my inputs and outputs:
[00000.zip](https://github.com/mkazhdan/PoissonRecon/files/9069550/00000.zip)

**Comment by mkazhdan** [comment]
The problem is that the surface that you generate in the first reconstruction pass does not include all the points in pointcloud_depth.ply. The implementation is such that if sample points (more precisely, the derived vector field) falls outside the envelope, the envelope is eroded to allow surface to be reconstructed there. (See Section 4.2, Erosion of Exterior.)

**Comment by hzhao1997** [comment]
Thanks for your quick and nice reply and now I understand it : )

**Comment by hzhao1997** [comment]
Sorry for interrupt again. I have already kept the points of pointcloud_depth.ply inside the visual hull but there are still reconstructions outside visual hull. Is there anything I understand wrong?

[Uploading 00000.zip…]()

**Comment by hzhao1997** [comment]
[00000.zip](https://github.com/mkazhdan/PoissonRecon/files/9082249/00000.zip)

**Comment by mkazhdan** [comment]
Even if the points are strictly inside the visual hull, the erosion happens based on the vector-field constructed from the oriented points. This tends to be "thicker" than the point cloud itself.

**Comment by hzhao1997** [comment]
> Even if the points are strictly inside the visual hull, the erosion happens based on the vector-field constructed from the oriented points. This tends to be "thicker" than the point cloud itself.

It is a bit difficult for me to understand this. Could you tell me how to generate an adequate envelope? The generated visual hull needs to be dilated?
