### ISSUE TITLE
help with tweaking the envelope 

### ISSUE THREAD

**Issue by maorp** [mkazhdan/PoissonRecon#258]
Hi, first thanks for this library. can you direct me how to tweak the params or the input so the output mesh will not leak. esspically in between fingers. see image:
![image](https://user-images.githubusercontent.com/11231999/233032972-75747803-c34c-483d-a035-2b5b68bdd56b.png)
![image](https://user-images.githubusercontent.com/11231999/233033106-1ad4eb56-2881-46a6-9081-d91bc25b9787.png)
![image](https://user-images.githubusercontent.com/11231999/233033251-d4fd2b2e-d56d-4df8-bcfd-f00265ead71d.png)
and the data:https://drive.google.com/file/d/1bifrDXrFlILTBFzAq9wEMtmy4v00ZpwV/view?usp=sharing

**Comment by mkazhdan** [comment]
Unfortunately, Google is telling me I don't have access.

**Comment by maorp** [comment]
sorry try now
https://drive.google.com/file/d/1bifrDXrFlILTBFzAq9wEMtmy4v00ZpwV/view?usp=drivesdk

**Comment by mkazhdan** [comment]
Have you tried running the reconstruction at depth 10?
I got pretty good results that way. (Didn't even have to use the envelope.)
The fingers connect a tiny bit, but that is inside the envelope.
I also found that disabling screening (--pointWeight 0) seemed to help.

**Comment by maorp** [comment]
yes its better, although it exposes the noise in the pointcloud more then when using 9, ill use depth 10 and apply some mesh smoothing. thank you!
