### ISSUE TITLE
I got an empty ply after execute the PoissonRecon

### ISSUE THREAD

**Issue by wanxnyi** [mkazhdan/PoissonRecon#267]
Dear professor:

- I open a “Developer Command prompt for VS 2022” command line window.
- I go to in the exe file directory.
- I execute the "PoissonRecon.exe".
- I can see that the exe has read the number of points.

But I don't know why the output result is an empty file of 1kb. 
Am I doing something wrong? I'm hungry for some help.

Thank you very much for all replies.
![image](https://github.com/mkazhdan/PoissonRecon/assets/53291902/b806b929-a8dd-4139-a127-e7ea053303ea)

**Comment by mkazhdan** [comment]
1. Can you share the point-set?
2.  Can you try a higher depth value (e.g. the default 8)?

**Comment by wanxnyi** [comment]
I understand it. I'm sorry for the silly question. It was indeed because my depth value was set too low. Thank you very much for the reply!
