### ISSUE TITLE
hi, can I compile and run the program from the command line on ubuntu system instead of visual studio? If so, can you tell me how to do it, thank you

### ISSUE THREAD

**Issue by glt-mhs** [mkazhdan/PoissonRecon#272]
hi, can I compile and run the program from the command line on ubuntu system instead of visual studio? If so, can you tell me how to do it, thank you

**Comment by mkazhdan** [comment]
Yes. There's a Makefile. So typing "make poissonrecon" from the and prompt should compile it for you .

**Comment by glt-mhs** [comment]
> Yes. There's a Makefile. So typing "make poissonrecon" from the and prompt should compile it for you .

thank you very mush
