### ISSUE TITLE
The reconstruction is not very good

### ISSUE THREAD

**Issue by glt-mhs** [mkazhdan/PoissonRecon#273]
PoissonRecon --in p1.ply --out p1out.ply --depth 10
This is my reconstructed command, the same problem appears on every point cloud data, the effect is good in one direction, the effect is poor in the other direction, how to solve this
![image](https://github.com/mkazhdan/PoissonRecon/assets/139851770/709ed6e0-93bf-4279-b561-86304b10ba5f)
![image](https://github.com/mkazhdan/PoissonRecon/assets/139851770/985dd7c0-449f-48a7-94a8-c8e3cb417122)

**Comment by mkazhdan** [comment]
I'm afraid that I can tell by looking at the reconstructed images.
It could be the case that you are missing parts of the scene (e.g. the backs of building) so the reconstruction fits a smooth interpolant there. (If that's the case and you don't want that, you can use the SurfaceTrimmer application to remove the coarse geometry.)
Or it could be the case that you have points there but the orientation of the normals is reversed from what it should be. (This happens for some applications that attempt to assign normals to unoriented points in a point cloud.)

If you would be willing to share the data, I could take a look.

**Comment by glt-mhs** [comment]
> I'm afraid that I can tell by looking at the reconstructed images. It could be the case that you are missing parts of the scene (e.g. the backs of building) so the reconstruction fits a smooth interpolant there. (If that's the case and you don't want that, you can use the SurfaceTrimmer application to remove the coarse geometry.) Or it could be the case that you have points there but the orientation of the normals is reversed from what it should be. (This happens for some applications that attempt to assign normals to unoriented points in a point cloud.)
> 
> If you would be willing to share the data, I could take a look.

I think it's a normal problem, because I only have problems with models trained using nerfstudio, but the rest of the data works fine, and using poisson first and then ssd is much better
