### ISSUE TITLE
Real-time monitoring memory

### ISSUE THREAD

**Issue by HiJasonZou** [mkazhdan/PoissonRecon#284]
Thank you for sharing this great project，professor. 
I set the parameter --maxMemory value on Android platform.
code:
```
#else // !_WIN32 && !_WIN64
#include <sys/time.h> 
#include <sys/resource.h> 
inline void SetPeakMemoryMB( size_t sz )
{
	sz <<= 20;
	struct rlimit rl;
	getrlimit( RLIMIT_AS , &rl );
	rl.rlim_cur = sz;
	setrlimit( RLIMIT_AS , &rl );
}
#endif // _WIN32 || _WIN64
```
Function `setrlimit ` need root permission on Android.I read the code and found that Allocator.h calculates the remaining memory, but at the beginning of the Add the FEM constraints step, Allocator.h cannot calculate the remaining memory. What do I need to do to implement poisson the whole process of detecting memory before each memory request.

**Comment by mkazhdan** [comment]
Unfortunately, I am not really sure how to go about doing this as I am not familiar with the Android OS.
There does appear to be some discussion of this online, however:
    https://unix.stackexchange.com/questions/72437/how-to-grant-non-root-user-access-to-device-files
so perhaps that could be helpful.

Alternatively, you could mess with Allocator.h to try and get it to fail if too much memory allocation is requested (Allocator::newElements). The total amount of memory should be _memory.size() * sizeof(T) * _blockSize.
The tricky part about doing it through the Allocator, however, is that there may be multiple allocators.
So if you want to go this route you will need to:
1. Set up a global/static variable tracking the total amount of memory used by all the allocators.
2. Possibly, constrain the read/write of that variable to be within a lock so as to ensure there are no issues if the calls to Allocator::newElements are made in parallel from across different threads.

**Comment by HiJasonZou** [comment]
> Unfortunately, I am not really sure how to go about doing this as I am not familiar with the Android OS. There does appear to be some discussion of this online, however: https://unix.stackexchange.com/questions/72437/how-to-grant-non-root-user-access-to-device-files so perhaps that could be helpful.
> 
> Alternatively, you could mess with Allocator.h to try and get it to fail if too much memory allocation is requested (Allocator::newElements). The total amount of memory should be _memory.size() * sizeof(T) * _blockSize. The tricky part about doing it through the Allocator, however, is that there may be multiple allocators. So if you want to go this route you will need to:
> 
> 1. Set up a global/static variable tracking the total amount of memory used by all the allocators.
> 2. Possibly, constrain the read/write of that variable to be within a lock so as to ensure there are no issues if the calls to Allocator::newElements are made in parallel from across different threads.

thank you!
