### ISSUE TITLE
Failed to build with default libjpeg,libpng, and libz.

### ISSUE THREAD

**Issue by jiapei100** [mkazhdan/PoissonRecon#286]
I just did a very straightforward remove, say: remove subfolder `JPEG`, `PNG`, and `ZLIB`.

Build **PoissonRecon** with system's `libpng`, `libjpeg`, and `libz`.

And with some simple modificaiton in order to let **PoissonRecon** to start building.

However, so many [error messages](https://pastebin.com/SfdVERT8) , which only contains half of the current error messages. I believe it's enough for analyzing.

Why it's wrong?

**Comment by mkazhdan** [comment]
Could be that you're using new libraries but old headers.

**Comment by jiapei100** [comment]
Now all done. system packages work fine...
