### ISSUE TITLE
Can we conclude a leaf node is fully inside the object if indicator function evaluations on its faces come out above the iso-value?

### ISSUE THREAD

**Issue by lopeLH** [mkazhdan/PoissonRecon#290]
Hi, I have been plotting the nodes of the octree and have some questions, which I hope might be relevant for the whole community.

First, I noted that adjacent nodes seem to have depths differing by at most one level. One can see this, for instance, looking at some slice of the octree along the Z axis after running on the classic Stanford bunny (just inlining a detail, full view [here](https://github.com/mkazhdan/PoissonRecon/assets/7440734/46c0439b-645f-4dd9-b6be-fc5299e94abd))

![image](https://github.com/mkazhdan/PoissonRecon/assets/7440734/79684022-7fc8-4f10-bea3-b5b7e18698d4)

Is this expected / guaranteed by the algorithm implementation? If so, that brings me to a second question. Lets assume that for some **leaf** octant we evaluate the indicator function on a 3x3 grid over each of its faces. If the indicator comes out as being above the iso-value for all those evaluations, can we assume the whole octant to be inside of the object? In other words, can we assume the indicator function will evaluate to values above that iso-value when evaluated anywhere inside this leaf octant? Intuitively I would say so, but I struggle to find hard evidence for it.

Going back to the 2D illustration, the question would boil down to whether a case like this is possible or not:

![image](https://github.com/mkazhdan/PoissonRecon/assets/7440734/10d92315-dd4e-4547-9042-29117830be68)

where again we can see the octree structure, the red circles represent evaluations of the indicator function which yield a value above the iso-value, and the black dashed line represent the iso-surface where the indicator function crosses the iso-value.

Thanks in advance,

**Comment by lopeLH** [comment]
If I understand correctly, the B-spline degree in question is the one passed as [**first** argument to the LevelSetExtractor::Extract member function](https://github.com/mkazhdan/PoissonRecon/blob/6439de117e19f1d501d80a369e3b4069a2aa6644/Src/FEMTree.LevelSet.3D.inl#L1870), which is used to initialize the internal indicator function [evaluators](https://github.com/mkazhdan/PoissonRecon/blob/6439de117e19f1d501d80a369e3b4069a2aa6644/Src/FEMTree.LevelSet.3D.inl#L1932). Is that correct? Also, I take that this value is specified at the higher level with the [DefaultFEMDegree constant](https://github.com/mkazhdan/PoissonRecon/blob/6439de117e19f1d501d80a369e3b4069a2aa6644/Src/Reconstructors.h#L148), right?

Thanks a lot for your answer.

**Comment by mkazhdan** [comment]
That's correct. Though its use in the extraction code needs to be consistent with its use in the reconstruction code.
If you do not have the "FAST_COMPILE" flag enabled, you can set it through the command line parameter using "--degree".

**Comment by lopeLH** [comment]
Perfect. That solves all my questions. Closing the issue. Thanks again for the help. Much appreciated.
