### ISSUE TITLE
PLY file not supported

### ISSUE THREAD

**Issue by kundu03** [mkazhdan/PoissonRecon#292]
I have a .ply file with the following header : 

ply
format binary_little_endian 1.0
element vertex 57162848
property float32 x
property float32 y
property float32 z
property uint8 red
property uint8 green
property uint8 blue
property float32 nx
property float32 ny
property float32 nz
property list uint8 uint32 view_indices
property list uint8 float32 view_weights
end_header

and when i try to construct it using PoissonRecon, I am getting the following error : 

[ERROR] Src/VertexFactory.inl (Line 72)
        FromPlyType
        Unrecognized type: 19

I think file type with this header is not supported. That's why it is unable to read it. Can you please update the code to read files with such type of headers. Thanks in advance.

**Comment by mkazhdan** [comment]
Can you share the file?

**Comment by kundu03** [comment]
Here is the link to the file,
### https://drive.google.com/file/d/1n9uWDAU907VPI9EjqB38TEuSoU2hwD1c/view?usp=sharing

**Comment by mkazhdan** [comment]
I believe that the newly pushed code/executable should resolve the problem.
