### ISSUE TITLE
PoissonRecon: Interaction between `--width` and `--depth` parameters is not well documented

### ISSUE THREAD

**Issue by jedfrechette** [mkazhdan/PoissonRecon#294]
In the Readme the description of `--width` says:

"This parameter is ignored if the --depth is also specified."

However, this does not seem to be accurate after the changes that were made in version 13.99.  In the current version (16.01) if `--width`  would result in a maximum depth greater than the default `--depth` value of 8 then the user must also specify a `--depth` value greater than the value required for `--width`.

To illustrate, in Version 13.80:

`PoissonRecon --in bunny.points.ply --out bunny.mesh.ply --width 0.0001`

would produce a mesh reconstructed to depth 11. In 13.99 and later that command would only produce a mesh reconstructed down to the default maximum depth of 8. In these newer versions if you want reconstruction to continue until `--width` is achieved you will need to run something like:

`PoissonRecon --in bunny.points.ply --out bunny.mesh.ply --width 0.0001 --depth 20`

where I've arbitrarily chosen a large value for depth to ensure that reconstruction won't stop until it hits the `--width` threshold, in this case at depth 11.

**Comment by mkazhdan** [comment]
The latest version, 16.03, should address this problem.

**Comment by jedfrechette** [comment]
Tested with 16.03 and it is working as expected now.
