### ISSUE TITLE
Failed to Build : W10 VS2017

### ISSUE THREAD

**Issue by L-YMH** [mkazhdan/PoissonRecon#302]
When I compile the projects using VS2017 I get the errors. How can I solve these ?
![ERROR](https://github.com/user-attachments/assets/e6c6c0f2-87b2-4523-bc2f-b5000e995128)

**Comment by mkazhdan** [comment]
Can you try changing line 61 from:
     static const struct Frame< Real , Dim , ExtendedAxes > _Frame;
to:
     static const PointExtent::Frame< Real , Dim , ExtendedAxes > _Frame;

If this works, please let me know and I will push the change to the repo.

**Comment by L-YMH** [comment]
Yes, it works.Now there is only one error left：E0519	template parameter "HyperCube::Cube<D>::Element [with D=D]" may not have a template argument list.
![ERROR](https://github.com/user-attachments/assets/b835480d-4edb-4eda-a313-46ab82c3d074)

**Comment by mkazhdan** [comment]
Can you try changing line 439 from:
     typename std::enable_if< (_D>_K) && _K!=0 , typename Cube< D >::Element< K > >::type Cube< D >::Element< K >::_antipodal( void ) const
to:
     typename std::enable_if< (_D>_K) && _K!=0 , typename Cube< D >::template Element< K > >::type Cube< D >::Element< K >::_antipodal( void ) const

(So that it matches line 441.)

Again, please let me know if the change fixes things.

**Comment by L-YMH** [comment]
Yes, it works again.I compiled other projects successfully and several others failed with this error：	
C2275 'std::_Pad': illegal use of this type as an expression 
Project: AdaptiveTreeVisualization 
File: d:\gitproject\poissonrecon\src\femtree.inl	
Line: 195

**Comment by mkazhdan** [comment]
Can you send a screenshot of the error in MSVC?

**Comment by L-YMH** [comment]
This is the screenshot of the error:
![ERROR](https://github.com/user-attachments/assets/39949635-bedd-4eb2-bb2b-e33eaf7462ec)

**Comment by mkazhdan** [comment]
This one I'm a little certain about.
You could try changing the preprocessor directives in lines 197-285 from:
     #ifdef __GNUC__
to:
     #ifndef __GNUC__

**Comment by L-YMH** [comment]
Is it modified like this?
![ERROR](https://github.com/user-attachments/assets/b8334e8e-3245-47b4-9f4a-4193fdc9cbb5)
![ERROR2](https://github.com/user-attachments/assets/4c951882-860b-45d9-a86f-7e50686396a3)

**Comment by mkazhdan** [comment]
Like so, but you need to make the changes all the way through line 285.

**Comment by L-YMH** [comment]
I have changed all and then the error shown in the picture appears.

**Comment by mkazhdan** [comment]
I'm afraid I don't see the error,.

**Comment by L-YMH** [comment]
Thank you very much for your reply and help！I will check it again.

**Comment by L-YMH** [comment]
I changed the #ifdef __GNUC__ from line 195 to line 285 to #ifndef __GNUC__, but the same error still exists.
![ERROR](https://github.com/user-attachments/assets/b5a2a9f0-9ba7-4bd6-bab9-0c4e27229676)

**Comment by mkazhdan** [comment]
I'm a bit confused about what's going, but why don't we try moving the definition of the struct SliceEvaluator outside the function body, as it appears the compiler is not bringing in the class templates into the declaration.

This requires three changes.
1. Put the code at the bottom of this message before the declaration of FEMTree< Dim , Real >::slice (on line 192). Note the preceding line "template< unsigned int Dim , class Real , unsigned int Pad , unsigned int FEMSig >"
2. Comment out the corresponding definition inside the function body (lines 223-309).
3. Change the declaration on line 311 to "SliceEvaluator< Dim , Real , Pad , FEMSig > sliceEvaluator;"

And here's the code (basically a copy of the declaration in lines 223-309, with the preceding "template" declaration):
template< unsigned int Dim , class Real , unsigned int Pad , unsigned int FEMSig >
struct SliceEvaluator
{
	struct _SliceEvaluator
	{
		const int StartOffset = BSplineSupportSizes< FEMSignature< FEMSig >::Degree >::SupportStart-(int)Pad;
		const int   EndOffset = BSplineSupportSizes< FEMSignature< FEMSig >::Degree >::SupportEnd+1+(int)Pad;
		int start;
		Real values[ BSplineSupportSizes< FEMSignature< FEMSig >::Degree >::SupportSize+2*Pad ];
		void init( unsigned int depth , double x , unsigned int d )
		{
			// off @ depthsupports the slice if 
			//		x>(off+StartOffset)/(1<<depth) && x<(off+EndOffset)/(1<<depth)
			// <=>	x*(1<<depth)-StartOffset>off && x*(1<<depth)-EndOfset<off
			// <=>	off \in ( x*(1<<depth)-EndOffset , x*(1<<depth)-StartOffset )
			// <=	off \in [ ceil( x*(1<<depth) )-EndOffset , ceil( x*(1<<depth) ) - StartOffset )
			start = (int)ceil( x*(1<<depth)-EndOffset );

			// The derivative is lower than the degree, the derivative will be continuous so we can evaluate it directly
			if( d<FEMSignature< FEMSig >::Degree ) for( int i=0 ; i<EndOffset-StartOffset ; i++ ) values[i] = (Real)BSplineEvaluationData< FEMSig >::Value( depth , start+i , x , d );
			else if( d==FEMSignature< FEMSig >::Degree )
			{
				double eps = 1e-4/(1<<depth);
#ifdef SHOW_WARNINGS
				WARN_ONCE( "Using discrete derivative: " , eps );
#endif // SHOW_WARNINGS
				// If we are dealing with a degree-zero polynomial, we offset
				if( d==0 )
				{
					for( int i=0 ; i<EndOffset-StartOffset ; i++ )
					{
						double value = 0;
						value += BSplineEvaluationData< FEMSig >::Value( depth , start+i , x-eps , d );
						value += BSplineEvaluationData< FEMSig >::Value( depth , start+i , x+eps , d );
						values[i] = (Real)(value/2);
					}
				}
				else // Otherwise we compute the discrete derivative
				{
					for( int i=0 ; i<EndOffset-StartOffset ; i++ )
					{
						double value = 0;
						value += BSplineEvaluationData< FEMSig >::Value( depth , start+i , x , d-1 ) - BSplineEvaluationData< FEMSig >::Value( depth , start+i , x-eps , d-1 );
						value += BSplineEvaluationData< FEMSig >::Value( depth , start+i , x+eps , d-1 ) - BSplineEvaluationData< FEMSig >::Value( depth , start+i , x , d-1 );
						values[i] = (Real)(value/(2*eps) );
					}
				}

			}
			else ERROR_OUT( "Derivative exceeds degree: " , d , " > " , FEMSignature< FEMSig >::Degree );
		}
		Real operator()( int off ) const
		{
			if( off<start || off>=start+(EndOffset-StartOffset ) ) return 0;
			else return values[off-start];
		}
	};

	std::vector< _SliceEvaluator > evaluators;
	void init( unsigned int maxDepth , double x , unsigned int d )
	{
		evaluators.resize( maxDepth+1 );
		for( unsigned int depth=0 ; depth<=maxDepth ; depth++ ) evaluators[depth].init( depth , x , d );
	}
	Real operator()( int d , int off ) const
	{
		if( d<0 || d>=(int)evaluators.size() ) return 0;
		else return evaluators[d]( off );
	}
};

**Comment by L-YMH** [comment]
I added new variables FEMSig2 and Pad2 after line 197, and then modified lines 228 and 229. This also compiled successfully, but I'm not sure if it was correct. 
![ERROR](https://github.com/user-attachments/assets/7b698c12-9a81-4085-b746-b265a3f9b634)
![ERROR2](https://github.com/user-attachments/assets/4c0dc574-f916-4620-a354-2baaf7d103bd)

However, I modified it according to your method and no errors occurred.Thanks again for your help！

**Comment by mkazhdan** [comment]
I think that makes sense. 
It appears the computer is not pulling the template parameters Pad and FEMSig into the struct declaration. But it does pull in the compile time constants Pad2 and FEMSig2. 

Seems strange, and it might be a compiler issue. Have you tried updating Visual Studios?

**Comment by mkazhdan** [comment]
Sounds like it's an issue with VS.
But it also sounds like we found a work-around.

Don't hesitate to reach out if you have further questions.

**Comment by L-YMH** [comment]
Alright, thank you very much！
