### ISSUE TITLE
PoissonReconServer , Quality and error to open file.

### ISSUE THREAD

**Issue by Gabriellgpc** [mkazhdan/PoissonRecon#308]
Hi professor, hope you are doing well,
I've been trying to use the PoissonReconServer on GCP (Debian bullseye), but I'm facing a few issues.

1. One issue was a "Failed to open temporary file", it happens when I'm using a VM with more than 30 CPUs.

2. and the other thing is about the final mesh. I'm sharing a screenshot showting the issue. it looks like the triangles did not merge properly. 

![Screenshot from 2024-10-13 22-20-20](https://github.com/user-attachments/assets/8b941828-0e36-40c5-9a20-2638cc500000)

I'm trying to use the latest version v18.31, but also got the same issues and results from version v15.
I tried a few other commited versions, between v15 and 18.30, but still the same ...

I'm using the default parameters. A few settings I've tested.
depth = 8  to 12
pointWeighted 0.0 to 20
samplesPerNode 1.5 to 5
degree 1 to 2

it's strange because I got better results using the normal PoissonRecon (not distributted).

I'm doing tests on the same VM, launching the server and the client from the same VM.
Also tested launching from different VMs. launching using Dockers.

**Comment by Gabriellgpc** [comment]
Thank you for you quick reply.
yes, it does. line 200 on the latest version. in the Reconstructors.streams.h file.

![image](https://github.com/user-attachments/assets/4417af1d-7aeb-4030-9a05-39c315686e79)

Regarding the mesh result issue,
unfortunately I cannot share that first point cloud I've showed, but using a another toy point cloud, I got the same problem,
Input point cloud: 
![image](https://github.com/user-attachments/assets/dc56b846-1b17-4c6a-82da-32e16186174b)
Result
![image](https://github.com/user-attachments/assets/ba57bf6e-e39e-4a02-a874-d3efd4d60c3e)

you can access the point cloud here https://drive.google.com/file/d/1b96tvr2HALSuZeNjKEnXv2PQif5h1xkq/view?usp=sharing
I'm using the same parameters, 
--count 1
--depth 8
--density
--verbose 4


Thank you again for the support. and for the amazing work.

**Comment by mkazhdan** [comment]
Strange. I ran the server:
>>> PoissonReconServer.exe --in points.condados.ply --tempDir . --out out.ply --count 1 --port 12345 --verbose 4 --density --depth 8
And the client:
>>> PoissonReconClient.exe --port 12345
And got what looked like reasonable results.
Here's the header for the output out.ply file:
ply
format binary_little_endian 1.0
element vertex 66784
property float x
property float y
property float z
property float value
property uchar red
property uchar green
property uchar blue
element face 65670
property list int int vertex_indices
end_header

**Comment by Gabriellgpc** [comment]
Pretty much the same header I got.

> ply
> format binary_little_endian 1.0
> element vertex 66794
> property float x
> property float y
> property float z
> property float value
> property uchar red
> property uchar green
> property uchar blue
> element face 65675
> property list int int vertex_indices
> end_header

but when try to visualize it (on cloudcompare or using Open3D) I can see those artifacts
![image](https://github.com/user-attachments/assets/459910d8-243c-4426-9f15-186bf6f67f0a)
![image](https://github.com/user-attachments/assets/aa7ef64b-6785-473f-8b1f-1b72731de054)

I'll try again on a fresh machine, using the latest version without editing anything on make.
just git clone and make. to double check.

**Comment by mkazhdan** [comment]
Yep. That makes sense now.
The output of the client/server reconstruction is a polygon mesh, not a triangle mesh.
My guess is that your visualization is only showing the subset of polygons that only have three vertices.

**Comment by mkazhdan** [comment]
If you open the file with a viewer like MeshLab, you should be able to see the whole mesh. (And also convert it to a strictly triangle mesh.)
