### ISSUE TITLE
Use OS' temporary directory for BufferedReadWriteFile

### ISSUE THREAD

**Issue by twolfson** [mkazhdan/PoissonRecon#31]
We are using `PoissonRecon` in AWS Lambda which only permits creating files in its `/tmp` directory (OS' temporary directory):

http://docs.aws.amazon.com/lambda/latest/dg/limits.html

Currently `BufferedReadWriteFile` writes to the current working directory. As a workaround for now, we've hardcoded the `BufferedReadWriteFile` template to use the `/tmp` directory:

https://github.com/StandardCyborg/PoissonRecon/blob/93762c30d870752220973abb8252ca3b95e88d14/Src/Geometry.cpp#L52

I believe it's possible to find the OS' temporary directory via environment variables but am rather inexperienced in C++ and wanted to check the PR would be accepted first. If I wrote a PR to switch over to the OS' temporary directory, would you be interested in it in `PoissonRecon`?

**Comment by mkazhdan** [comment]
I have modified the code to support an additional “--tempDir” parameter which should allow you to specify the directory to which the temporary files will be written.

Do not hesitate to contact me if this is not behaving appropriately.

 

-- Misha

**Comment by twolfson** [comment]
Wow, this is awesome. Thanks a bunch @mkazhdan. I'll try it out tomorrow

I'm pre-emptively closing the issue now =)
