### ISSUE TITLE
Multi-resolution reconstruction problem

### ISSUE THREAD

**Issue by Habsburgg** [mkazhdan/PoissonRecon#313]
parameter : normalConfidence = 1.f, normalConfidenceBias = 1.f
For high-resolution areas, the normal length is set to 1.f; for low-resolution areas, the normal length is set to less than 1.
When the normal length of the low-resolution area is set to 0.5, it meets the requirements; if it is greater than 0.5, such as 0.8, there are more high-resolution areas，It is different from setting the high-resolution area, which is obviously much more.
Looking forward to your reply.
![image](https://github.com/user-attachments/assets/6db6ef9f-3e96-45ca-a43c-0412a9674137)
![image](https://github.com/user-attachments/assets/584b576c-a1c1-4845-9540-6a1092521857)

**Comment by mkazhdan** [comment]
I don't think I follow. What is the question/issue?

**Comment by Habsburgg** [comment]
sorry, maybe there is a problem with my expression.
I want to achieve multi-resolution mesh creation, according to the parameter description, I set the normal length of one part of the point cloud to 1, and the normal length of the other part of the point cloud to less than 1.
I did two experiments, the first one: the high-resolution normal length was set to 1 and the low-resolution direction length was 0.5. The second experiment: the high-resolution normal length is set to 1, and the low-resolution direction length is 0.8.
In the first experiment, the reconstruction results were as expected, and the areas with dense grids were the high-resolution areas I set.However, the second experiment only modified the low-resolution normal length to 0.8, and the reconstructed mesh did not meet expectations, and the dense area of the mesh was much larger than the high-resolution area I set.

**Comment by mkazhdan** [comment]
I think that makes sense. Every factor of 0.5 basically reduces the reconstruction depth by one, making the associated mesh triangles twice as big. This matches what you're seeing with normal lengths of 0.5. For normal lengths of 0.8 you are somewhere between the finest depth and one depth coarser. But since reconstruction depths are discreet, this means the finest resolution is constructed everywhere. 

I'm guessing that if you made the weight 1.0 in some regions, 0.5 in others, and 0.25 in still others, you should see three different resolutions of reconstructions. 

You could also try reconstructing points sampled from a plane, with normal length going from 1.0 on one side to 0.0 on the other.

**Comment by Habsburgg** [comment]
As you said, by setting three different values ​​of 1, 0.5, and 0.25, we obtained models with three different resolutions after reconstruction.
However, when I use another point cloud with a larger number of points（About 940,000 points） for reconstruction, with some of the point clouds normal lengths set to 1 and the rest to 0.5, something unexpected happens: the reconstructed high-resolution area is larger than the area I set.
Use a depth parameter of 10.

**Comment by mkazhdan** [comment]
That's because the depth isn't large enough. The sampling density for points with weight 1 likely wants to place those points at depth >=11 and the ones with weight 0.5 at depth >=10. But since the maximum depth is 10, all the points get added in at the same depth (i.e. 10).

**Comment by Habsburgg** [comment]
I tried to rebuild with depth 11 and 12, but the same problem still existed. I need the difference between high resolution and low resolution triangles is not so big, is it OK? The parameters of 1 and 0.5 are used at present, and the size of the high resolution triangle is twice that of the low resolution triangle, do you have any good suggestions

**Comment by mkazhdan** [comment]
What do you mean by: "I need the difference between high resolution and low resolution triangles is not so big, is it OK?"

Is that to say you would like the difference in triangle sizes to differ by less than a factor of two? That isn't supported because the octree cell sizes are discrete and change by a factor of two with each hierarchy level.

**Comment by Habsburgg** [comment]
Ok, I see what you mean. 
For me at the moment, after changing the depth, the regional problem is still there.

**Comment by Habsburgg** [comment]
The red circle is the set high resolution area
![image](https://github.com/user-attachments/assets/f663da6f-9a31-4c63-94b5-1956902273fb)

**Comment by mkazhdan** [comment]
This is to be expected. The depth at which points are introduced into the octree is given by the local sampling density. This use of normal confidence plays into this by allowing samples to contribute "fractionally" to the sampling density estimation. However, independent of that, the number of samples in the vicinity will also play a roll.

It is likely that the regions with coarser triangles within the red circles has slightly fewer samples.

**Comment by Habsburgg** [comment]
Thanks for your reminding, I performed voxel filtering on the original point cloud, and after the depth was changed to 12, the high-resolution area met the expectation.

**Comment by Habsburgg** [comment]
I will continue to verify the impact of this treatment on the model in the future. Thank you for your help.

**Comment by Habsburgg** [comment]
Finally, there is a question, can this use of confidence be set to be independent of density.

**Comment by mkazhdan** [comment]
Unfortunately, I do not believe there is an easy way to do that.

**Comment by mkazhdan** [comment]
You can either reduce the interpolation weight (set --pointWeight to a value close to zero) or increase the number of samples per node (setting --samplesPerNode to a value larger than the default 1.5).

**Comment by Habsburgg** [comment]
Modifying pointWeight and samplesPerNode can solve the problem of high resolution unevenness. However, in low resolution areas, the details will become unclear. My intention was to make some areas (high resolution areas) more detailed, while not reducing the details of other areas (low resolution areas).

**Comment by mkazhdan** [comment]
The easiest fix would be to use a lower --depth value. That won't change the results in sparsely sampled locations but will force smoother (and less high-res) reconstructions in densely sampled areas.
