### ISSUE TITLE
Color Interpolation

### ISSUE THREAD

**Issue by markloyman** [mkazhdan/PoissonRecon#32]
When I run my model with depth 10 (color=16), the resulting color is somewhat blurry (detail level is excellent).
Is there any way to influence the interpolation process to limit it's spatial extent?

I've attempted to make it sharper by: 
1. In `MultiGridOctreeData.WeightedSamples.inl` : `Octree< Real >::_evaluate()`, I limited the evaluation to the last depth levels.
2. Changing the BSpline degree  (`DATA_DEGREE` in `MultiGridOctreeData.h`). Hoping that higher order polynomials, would result in higher sharpness.
Both were unsuccessful.

Do I have any alternative to using depth 11?

**Comment by mkazhdan** [comment]
Have you tried using a larger --color value, say 64 instead of 16?

**Comment by markloyman** [comment]
Yes, I think that 64 was even the exact value that I tried.

By the way, I believe that Depth 10 (on my model) is enough for color interpolation, because the resulting mesh has a high resolution.

**Comment by mkazhdan** [comment]
Hi Mark,

So I've never tried this... But if you're OK recompiling the code, you can try the following:
In MultiGridOctreeData.h, change the line "#define DATA_DEGREE 1" to "#define DATA_DEGREE 0". 

If that doesn't work and you're ok with sharing your dataset, I would be happy to look in more detail. 

-- Misha

**Comment by markloyman** [comment]
Hi, I recompiled with `DATA_DEGREE 0`, and it has indeed improved the sharpness of the color in my model (skin texture).

Thank you! Both your current help and the sharing of your method, are much appreciated.

**Comment by mkazhdan** [comment]
Glad to hear that worked for you. 

-- misha

**Comment by markloyman** [comment]
A short demonstration of the effect of the order of the B-Spline used to splat in data for color interpolation:

| Data Degree 0  | Data Degree 1 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/23008771/29652015-338849e6-88ac-11e7-85a9-69d4be128e2f.png)  | ![image](https://user-images.githubusercontent.com/23008771/29652033-484a60f8-88ac-11e7-9fbb-910b7e6245a0.png)  |
