### ISSUE TITLE
How closely does SSDRecon approximate a distance function?

### ISSUE THREAD

**Issue by mikeroberts3000** [mkazhdan/PoissonRecon#33]
Hello there,

I have a quick silly question about the volume returned by SSDRecon with the ``--voxel`` option. How closely does this function approximate a distance function, assuming noise-free synthetic input data and default parameter settings?

When I examine the output volume I get using my noise-free synthetic input data, I see that the distance values appear to be "normalized", in the sense that they seem to be between -1 and 1 for my data. Based on this observation, I am assuming that the largest distance value you'd ever expect to see in the output volume is sqrt(3), because this would be the normalized distance from the origin to the most distant corner of the unit bounding box. So far, so good.

However, if I assume that the volume extends from (0,0,0) to (1,1,1), then the distance values do not seem to approximate a distance function very closely. For example, here is a slice of the distance function I obtain from my input data. I am not doing any of my own scaling here, I am simply displaying the raw values from the output volume:

![image](https://user-images.githubusercontent.com/2341965/29595050-dd82efb2-8769-11e7-8ff4-0cdda32f0929.png)

The zero level set of this function approximates my surface very accurately:

![image](https://user-images.githubusercontent.com/2341965/29595061-f10d0266-8769-11e7-8947-53ceb03f77bd.png)

But when I numerically compute the gradient magnitude of this function, it seems to be non-constant and less than 1 almost everywhere. Here is a slice of the gradient magnitude, which I computed in 3D:

![image](https://user-images.githubusercontent.com/2341965/29595067-fba7774c-8769-11e7-88e2-a52cf6701dab.png)

Assuming that I call SSDRecon with default parameter settings, how strictly is the constraint enforced that the gradient magnitude is constant? Am I wrong to expect that the distance function returned by SSDRecon is approximately correct far away from the surface?

**Comment by mkazhdan** [comment]
It might be best to ask the original authors about this.

My experience has been that this is only an approximation of the distance function.

In particular, there is no explicit constraint that the gradient has magnitude one (as in the Eikonal equation) only an energy term encouraging the Laplacian to be zero, combined with screening terms for the value and gradient at the input samples.

 

In their work, the authors show that this should behave well for a sphere. However, it is less clear how this would behave for non-convex objects. In particular, such objects have non-trivial medial axes where the function’s derivatives are discontinuous and hence the Laplacian can become unbounded. Trying to enforce zero Laplacian constraints there could have far-reaching global effects.

 

-- Misha

**Comment by mikeroberts3000** [comment]
Ah, ok, no worries. I just wanted to double-check I wasn't crazy 😄
