### ISSUE TITLE
Two questions about the algorithm

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#42]
I have two questions about the algorithm. I'd be appreciated if you could offer some information.
1. Is there a paper or something to explain the algorithm of the surface trimming method ?
2. Do you know any methods related to the GPU implementation of your screened Poisson reconstruction algorithm ?

**Comment by mkazhdan** [comment]
1. Nope. Though the idea is not too complicated. In the surface reconstruction code we construct a density/depth estimator that we sample at the vertices of the reconstructed surface. The trimming code looks at these values (per triangle) finds the edge at which the linear interpolant equals the target density/depth and discards the fragment of the triangle below the target threshold. 

2. There was a paper out of MSR Asia (I believe) called "Highly Parallel Surface Reconstruction": https://www.microsoft.com/en-us/research/publication/highly-parallel-surface-reconstruction/

**Comment by antibes0415** [comment]
Much thanks.
