### ISSUE TITLE
Questions about the algorithm

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#47]
Hi , I have not read the code much. Instead I read the papers (the original one,  screened one, and the GPU implementation one by MSR Asia). I implemented all the codes mainly according to the MSR paper (in CPU codes, not GPU), which is based on your paper published in 2006. But sadly I have not got the desired mesh and cannot find the problem by far. My mesh is distorted along the boundary . I have two questions. Hope you could give me some  direction.
1) How do we impose the boundary constraints (Dirichlet or Neumann) to the linear system Lx = b? The descriptions  about boundary constraints just appeared in screened poisson paper. And I don't know where to implement this constraints. 
2) For uniformly distributed samples, is the way to compute the implicit function value is sum(F * ϕ) ? Right now I use the following algorithm given by MSR to compute the isovalue of an arbitary point:

```
Listing 4 Compute Implicit Function Value ϕq for Point q
1: ϕq = 0
2: nodestack ← new stack
3: nodestack.push(proot)  // push root node (depth 0 node)
4: while nodestack is not empty
5:     o ← NodeArray[nodestack.pop()]
6:     ϕq+ = Fo(q)ϕo
7:     for i = 0 to 7   // traverse 8 children of this node
8:         t ← NodeArray[o.children[i]]
           // the node function range of each node is set to be [-width, width]
9:         if abs(q.x −t.x) < t.w and abs(q.y −t.y) < t.w and abs(q.z −t.z) <t.w then
10:           nodestack.push(o.children[i])
```
I use this algorithm to compute isovalue in sample points and cube vertices.
This simple algorithm just iterate the nodes whose node function cover the point and accumulate F*ϕ.
But I think since the nodes are discrete and sparse, the total number of nodes that contribute ϕ to the arbitary point is not stable and can always vary, which may lead to the incontinuity of implcit function value ϕ in the 3D domain. Let alone finer depth nodes cannot cover most vertices of coarser depth leaf nodes. By the way, since the magnitude of node fuction is scaled according to node depth ( 1 / (width^3)), the contributions of coarse depth nodes are very low, and the implicit function value may change greatly in vertices from different depth nodes. I really suspect whether this method could result in a continuous, smooth and watertight isosurface. Is this algorithm enough for computing isovalue of sample points or cube vertices? I'd appreciate a lot if you could explain it to me :)

**Comment by antibes0415** [comment]
Right now the reconstruction result of my code is like this... I've only generated surfaces in max depth nodes by far. As you can see, the final value I computed seems not be continuous and watertight. There are scattered small faces outside the model. The mesh quality is verty bad.

![2018-01-15 11_19_04-meshlab 2016 12 - project_1](https://user-images.githubusercontent.com/18564849/34925700-f23dd52c-f9e5-11e7-9e90-7911f59e0934.png)

**Comment by antibes0415** [comment]
Here's the bunny mesh generated by my codes (I only generated meshes in max depth octree nodes by far). The terraces are very obvious. Don't know why. Sad.
![2018-01-15 17_23_50-meshlab 2016 12 - project_1](https://user-images.githubusercontent.com/18564849/34935658-8e8b90d0-fa19-11e7-9e5e-5a1e6d4eb9ff.png)
![2018-01-15 17_24_06-meshlab 2016 12 - project_1](https://user-images.githubusercontent.com/18564849/34935661-904e4b7e-fa19-11e7-90c5-677ab3922c55.png)

**Comment by mkazhdan** [comment]
In reply to the first question, imposing boundary conditions is tricky. In defining your finite-elements discretization, you need to adjust correctly for the boundary. If you are working explicitly with functions, you need to either force the function to have a zero value at the boundary (Dirichlet) or a a zero boundary-crossing derivative (Neumann). The easiest way to do this is to reflect your basis function across the boundary and either subtract the two (Dirichlet)  or add them (Neumann). If you are working with a finite-differences stencil, you need to adjust the stencil accordingly. In the 1D case, your standard stencil is of the form [-1 2 -1]. If you are using Dirichlet constraints, at the left boundary it becomes [* 2 -1] and if you are using Neumann constraints it becomes [* 1 -1]. (The "*" indicates that you cannot access at the value to the left of the left boundary.)
I am less clear on the second question, though you may want to ask the MSRA folks about that, if you are implementing their paper.
