### ISSUE TITLE
Question about the B-spline function

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#49]
Hi. I have two questions.
1. In Poisson Surface Reconstruction (2006), the value of the base function is sacled by (1 / o.w^3). 
![2018-03-05 15_27_23-2006 2117 poisson surface reconstruction pdf _ -](https://user-images.githubusercontent.com/18564849/36962268-c8e91a90-2089-11e8-993a-30ee2913a711.png)
Do you implement this feature in screened Poisson, i.e. is the B-spline function scaled by (1 / o.w^3) in 3D or  (1 / o.w) in 1D whenever it is called ?
2. Is the implicit function value of an arbitary point computed as the linear combination of the solution of related nodes ( x(p) = sum(xiBi(p) ) ? Except for B-spline function, there is no other scaling factor to adjust the weight of solution value of different depth nodes, right ?

**Comment by mkazhdan** [comment]
1. I'm not sure. Though it shouldn't make a difference. Scaling the B-splines by different values does not change the function space they span. From the perspective of iterative solvers, convergence may be different  depending on the scale, but only if functions within the same level are scaled by different amounts. (Which is not the case with or without per-level normalization.)

What is important is that when splatting a normal into the tree the integral of the splat is proportional to the estimated area of the sample. (This does require scaling coarser nodes by 1/w^3.)

2. Yes, that's how evaluation is done.

**Comment by mkazhdan** [comment]
More precisely:
When scaling the different levels by different amounts, you need to be careful that the prolongation (and restriction) operators are adjusted accordingly. I believe the later paper uses the standard B-splines prolongation stencil, which means no per-level re-scaling.

**Comment by antibes0415** [comment]
Thanks. I've implemented unscreened Poisson be myself. Maybe due to different ways of implementation, I have to use an extra factor to adjust the weight among different levels ( x(p) = sum(factor * xi * Bi(p) ). Right now I try to implement the screened Poisson, however the adaptive weight of the screen term ( 2^d ) described in your paper just doesn't work for my code. Anyway I will be trying. Thanks.

**Comment by antibes0415** [comment]
Hi. Where can I find the standard B-spline prolongation stencil ? Could you give me some help ?

**Comment by mkazhdan** [comment]
In 1D, I believe that the prolongation stencil for B-splines of degree d has entries:
{ Choose(d+1,0) , ... , Choose(d+1,d+1) } / 2^d
where Choose(a,b) is "a choose b". That is:
Choose(a,b) = a! / ( (a-b)! * b! )

In dimension k, it's the k-th tensor product of the 1D stencil. 

Note that even- (resp. odd-) degree B-splines have an even (resp. odd) number of entries in their stencil. This is because even- (resp. odd-) degree B-splines are centered at cell centers (resp. corners).

-- Misha

**Comment by antibes0415** [comment]
Much thanks. I've found this 1D stencil described in your V4 Poisson code comments. But I was not so sure.

**Comment by antibes0415** [comment]
Hi, I have another question about the prolongation. I use the 2 degree B-spline and the prolongation stencil is {1/4, 3/4, 3/4, 1/4}. For example, in 1D, if the solution of a node T in depth D-1 is b(T), the prolonged solution of related 4 nodes in depth D are  {1/4, 3/4, 3/4, 1/4} * b(T) ?  To my understanding, it's like this:
node T in depth D - 1:
                   |-------------|
                           b(T)
nodes in depth D covered by node T:
|------|------|------|------|------|------|
    0            0.75b(T)      0.25b(T)
         0.25b(T)      0.75b(T)           0

But when there are some neighbor nodes T1,T2,... in depth D-1, how to compute the prolonged solution in overlap nodes in depth D ?

**Comment by antibes0415** [comment]
Hi. I just accumulate those prolonged solutions of depth D - 1 nodes for overlapped depth D nodes. It works. Much thanks. Finally I get the same quality and accuracy mesh compared with mesh generated by your codes.

**Comment by mkazhdan** [comment]
Great. Glad to hear things worked out.
