### ISSUE TITLE
About block Gauss-Seidel solver

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#55]
Hi. In the Poisson surface reconstruction paper 2006, you mentioned block Gauss-Seidel solver to solve the issue of large memory requirement of solving the Lx = b equation (size of sparse matrix L could be 125 * octree node numbers in this depth d).

> To address this issue, we augment our solver with a block Gauss-Seidel solver. That is, we decompose the d-th dimensional space into overlapping regions and solve the restriction of Ld to these different regions, projecting the local solutions back into the d-dimensional space and updating the
residuals. By choosing the number of regions to be a function of the depth d, we ensure that the size of the matrix used by the solver never exceeds a desired memory threshold.

I wonder how to implement this block Gauss-Seidel solver, how to decompose the large matrix L into small ones and solve them one by one ? Could you kindly give some guidance ? I don't find much information or code on the net.

**Comment by mkazhdan** [comment]
Basically, the idea is to decompose the domain into overlapping blocks and then run a solver (in that case conjugate-gradients) on each block, in sequence. I can't recall how it is different from domain decomposition.
