### ISSUE TITLE
Find node neighbors in octree

### ISSUE THREAD

**Issue by antibes0415** [mkazhdan/PoissonRecon#58]
Hi. I think neighbors of octree nodes should be used in the algorithm. How do you compute octree node neighbors in a fast way ? Do you save 1-ring or 2-ring neighbors of each node?

**Comment by mkazhdan** [comment]
This is done through the NeighborKey. The idea is that if I know my parent's one-ring neighbors, I can use that to compute my own one-ring. This motivates a recursive data-structure that stores the one-rings of all ancestors. The key idea is that if you traverse the octree in a reasonable order, the one-rings of most ancestors are unchanged. 

-- Misha

**Comment by antibes0415** [comment]
Thanks.
