### ISSUE TITLE
Interpolation of other input sample in version 10.01

### ISSUE THREAD

**Issue by ahmadhasan2k8** [mkazhdan/PoissonRecon#62]
Hello,
I saw this update in the latest diff :  
```
Modified the reconstruction code to facilitate interpolation of other input-sample quantities, in addition to color
```
Although I followed your suggestion and was able to finally integrate the roughness property to the code but if you include it in the main repo I will just stash mine. But unfortunately I could not find an updated README to follow on how to run with the additional property. Could you please update the README or let me know here on how to use this new functionality? Once I can build the 10.01 version I will be able to start testing. I'll have to make it CMake compatible after. 

Thanks,
Ahmad

**Comment by mkazhdan** [comment]
Sure. If you look in PoissonRecon.cpp, you will see a call:

              Execute< DIMENSION , float , PointStreamColor< float > >( argc , argv );

The function “Execute” takes a variadic template argument specifying the data types to interpolate in the output.

 

In the above, I am interpolating colors. (The class PointStreamColor is defined in PointStreamData.h.)

If you want to interpolate roughness as well, you would call:

              Execute< DIMENSION , float , PointStreamColor< float > , PointStreamRoughness< float > >( argc , argv );

If you wanted just roughness, you would call:

              Execute< DIMENSION , float , PointStreamRoughness< float > >( argc , argv );

 

Note that the ordering of the interpolated types, relative to each other, within the template list is not important (DIMENSION and float still come first and second, respectively).

 

To interpolate a home-baked data type, you need to define your own data class, following the structure (e.g. of PointStreamRoughness) in PointStreamData.h and then you could add that to the template parameter list.

 

-- Misha

**Comment by ahmadhasan2k8** [comment]
Thanks. I'll work on it.

**Comment by ahmadhasan2k8** [comment]
It works perfectly. Thanks.
