### ISSUE TITLE
Question about implementing notation in paper +

### ISSUE THREAD

**Issue by Keudeugi** [mkazhdan/PoissonRecon#63]
Hello, first of, greatly appreciated to providing your implementations!

I'm trying to implement my own version of Screened Poisson Surface Reconstruction, however I'm currently stuck on the problem with implementing some notation.

In your original paper(2006), there're a bunch of notation 'q', and it seems like it means an arbitrary 3D position.
We have an example of node function [<a href="https://www.codecogs.com/eqnedit.php?latex=Fo(q)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?Fo(q)" title="Fo(q)" /></a>](url), which is unit integral base function aligned at node o. This notation is also can be seen in various expressions: Kernel density, Vector field, Isosurface extraction etc (Even for solving linear systems?).  Unfortunately, I couldn't find any descriptions for q.

I assumed it as sample's position, however there's already a notation s.p which has equivalent meaning. It also can't be octree node's position since there's notation o.c defines node center.

1. Can I ask for the meaning of the notation q? 

ps.

2. Will there be no problem if I substitute Base function (n-th convolution of box filter: approximates to Gaussian distribution) as Unit Variance Gaussian distribution? I thought you used convoluted filter for efficiency & only wants to use in specific range (which is different point against Gaussian, since Gaussian is defined in infinite range), however I'm wondering is there any other reason you used approximated Gaussian.

Thanks for reading, and I'll looking forward for the answers! If more explanation is required, I'll post it more!

Regards, 
PilJoong

**Comment by mkazhdan** [comment]
q is an arbitrary position in 3D. 
You could use a gaussian for the basis function, but it's not compactly supported so the computation will be slower.

**Comment by Keudeugi** [comment]
Thanks for the fast reply!
