### ISSUE TITLE
Questions from original paper

### ISSUE THREAD

**Issue by Keudeugi** [mkazhdan/PoissonRecon#64]
Hello, I'd like to ask about two questions from your original paper(2006), mainly related to implement with non-uniform samples case:

1. is an evaluated value of local sampling density is formed in scalar? 
> WˆD(q) ≡ Σs∈SΣo∈NgbrˆD(s) αo,s*Fo(q) 
(sorry for readability why it doesn't rendered :| )
- I thought that every node function **Fo(q) will returns scalar** since it can be separated into three functions, and the evaluation can be done by multiplying all separated function's value for each queried point's coordinate. 
- For the case of **αo,s**, I'm understanding that it'll **return 3D vector** type value since it'll return three interpolation parameters like tx, ty, tz. 
- Finally, It seems obvious that the resulting density **WˆD(q)** should **return a scalar value**, since it's literally a density... and later when we calculate a desired depth Depth(s.p), density from a sample point is divided by average density. (Of course the average seems to be formed in scalar too). Furthermore in isovalue selection, the inverse of density is being used, which can't be done with vector form.
- However, as I tried to derive the expression, the multiplication part **αo,s*Fo(q)** seemed return **3d vector** since it's multiplication between 3d vector and a scalar...

Did I missed something with deriving the equation? How can I derive it correctly?

2. I wonder why sample's normal didn't used for calculating vector field for non-uniform samples case. I mean, in here:
>V(q) ≡ Σs∈S (1 / WˆD (s.p)) Σo∈Ngbr(Depth(s.p))(s) (αo,sFo(q))
- Should I consider sample's normal manually when I try to solve linear system?

If more description is required, I'll explain it more.

Thanks in advance!
PilJoong

**Comment by mkazhdan** [comment]
1.	\alpha_o,s is the product of the three interpolation parameters
2.	If you look at the PDF available from my website (http://www.cs.jhu.edu/~misha/MyPapers/SGP06.pdf) you’ll see a comment about the missing normal term.

**Comment by Keudeugi** [comment]
Oh, I didn't know that your archive supports for the mistypo. Thank you for the reply!
