### ISSUE TITLE
SurfaceTrimmer data extraction

### ISSUE THREAD

**Issue by ahmadhasan2k8** [mkazhdan/PoissonRecon#65]
Hello,

I'm trying to collect values inside the execute function of surfacetrimmer.cpp

In version 9 it was like 
```
   for (size_t i = 0; i < vertices.size(); i++)
    {
      vertz.push_back(vertices[i].point.coords[0]);
      vertz.push_back(vertices[i].point.coords[1]);
      vertz.push_back(vertices[i].point.coords[2]);

      clrz.push_back(vertices[i].color[0]);
      clrz.push_back(vertices[i].color[1]);
      clrz.push_back(vertices[i].color[2]);
    }
```
In version 10.00 after including roughness as you instructed this part changed to 
```
for (size_t i = 0; i < vertices.size(); i++)
    {
      vertz.push_back(vertices[i].point.coords[0]);
      vertz.push_back(vertices[i].point.coords[1]);
      vertz.push_back(vertices[i].point.coords[2]);

      clrz.push_back(vertices[i].color()[0]);
      clrz.push_back(vertices[i].color()[1]);
      clrz.push_back(vertices[i].color()[2]);

      roughness.push_back(vertices[i].roughness());
    }
```
But now in 10.01 it does not work the same way I believe and if I print out this: 
```
    for (size_t i = 0; i < vertices.size(); i++)
    {
       std::cout << vertices[i].point.coords[0] << " "
                 << vertices[i].point.coords[1] << " "
                 << vertices[i].point.coords[2] << " "
                 << vertices[i].point.coords[3] << " "
                 << vertices[i].point.coords[4] << " "
                 << vertices[i].point.coords[5] << " "
                 << vertices[i].point.coords[6] << " "
                 << vertices[i].point.coords[7] << " "
                 << vertices[i].point.coords[8] << " "
                 << vertices[i].point.coords[9] << " "
                 << vertices[i].point.coords[10] << " "
                 << vertices[i].point.coords[11] << " "
                 << vertices[i].point.coords[12] << " "
                 << vertices[i].point.coords[13] << std::endl;

      }
```
I see the values of position, color, normals etc. but I'm not sure how does the coords[i] get it's sequence from. It looks like it prints points first then roughness then normals etc. Will this sequence be the same if I do not use a property as i.e. normals? How does it work?

Thanks,
Ahmad

**Comment by mkazhdan** [comment]
To get the surface trimmer to take into account roughness as well, you need to do several things.

1.	Change line 381 so that you support reading in per-vertex roughness properties:
typedef MultiPointStreamData< float , PointStreamValue< float > , PointStreamNormal< float , DIMENSION > , PointStreamColor< float > , PointStreamRoughness< float > > VertexData;
2.	Check if the .ply file actually has roughness information:
bool hasRoughness = VertexData::ValidPlyReadProperties< 3 >( readFlags + DIMENSION );
3.	If it does have roughness, add the PointStreamRoughness< float > type to the end of the parameter list used to call Execute:
if( hasRoughness )
      if( hasColor )
            if( hasNormal ) return Execute< PointStreamNormal< float , DIMENSION > , PointStreamColor< float > , PointStreamRougness< float > >();
            else            return Execute< PointStreamColor< float >, PointStreamRougness< float > >();
      else
            if( hasNormal ) return Execute< PointStreamNormal< float , DIMENSION > , PointStreamRougness< float > >();
            else             return Execute< PointStreamRougness< float > >();
else
      if( hasColor )
            if( hasNormal ) return Execute< PointStreamNormal< float , DIMENSION > , PointStreamColor< float > >();
            else            return Execute< PointStreamColor< float > >();
      else
            if( hasNormal ) return Execute< PointStreamNormal< float , DIMENSION > >();
            else            return Execute< >();



 

-- Misha

**Comment by ahmadhasan2k8** [comment]
I apologize, I probably did not explain the question correctly. I already did what you suggested. The problem is after. Inside the execute function, let's say the function prototype is something like:
```
template <typename... VertexData>
  int Execute(std::vector<double>& vertz,
              std::vector<double>& clrz,
              std::vector<double>& tri_indices,
              std::vector<double>& roughness)
```
Now I want to populate these vectors. The way I did it previously is mentioned in the issue. But now it does not work the same way for colors or roughness etc. How can I extract these values so that I can populate these vectors from "vertices"?

**Comment by ahmadhasan2k8** [comment]
Thanks. I will try it out. 

Tri_indices is triangle indices. Yes, it should be ints, my bad.
I was doing doing:
```
   for (size_t i = 0; i < gtPolygons.size(); i++)
    {
      size_t size = gtPolygons[i].size();

      for (size_t j = 0; j < size; j++)
      {
        tri_indices.push_back(gtPolygons[i][j]);
      }
    }
```
for tri_indices. Hope this will work same as before. I will update you once I try it,

Thank you.

**Comment by ahmadhasan2k8** [comment]
So, it works fine now after I changed to what you suggested. But, I also have another question. Let's say for the situation:
```
        if (!hasRoughness && !hasMetallic)
          return Execute<PointStreamNormal<float, DIMENSION>,
                         PointStreamColor<float> >(
              vertz, clrz, nrmls, tri_indices);
        if (hasRoughness && hasMetallic)
          return Execute<PointStreamNormal<float, DIMENSION>,
                         PointStreamColor<float>,
                         PointStreamRoughness<float>,
                         PointStreamMetal<float> >(
              vertz, clrz, nrmls, tri_indices, roughness_iuv);
      

```
In this case I need an overloaded Execute function. Even if the functions are like:
```
        if (!hasRoughness && !hasMetallic)
          return Execute<PointStreamNormal<float, DIMENSION>,
                         PointStreamColor<float> >(
              vertz, clrz, nrmls, tri_indices,roughness);
        if (hasRoughness && hasMetallic)
          return Execute<PointStreamNormal<float, DIMENSION>,
                         PointStreamColor<float>,
                         PointStreamRoughness<float>,
                         PointStreamMetal<float> >(
              vertz, clrz, nrmls, tri_indices, roughness);
      
```
and at the end I check the size of roughness vector to see which one ran still I need a function overloading for execute because the get<3>/get<4> will not compile for the first scenario. Is there something I can do about it? Or overloading is the only way?

**Comment by mkazhdan** [comment]
If I understand your question correctly, the std::get<3> (respectively std::get<4>) will crash if you have less that 3 (respectively 4) template parameters passed in to the Execute function. One way to get around this is, indeed to overload Execute so that you only call std::get<3> (respectively std::get<4>) when the number of template parameters support it.

 

-- Misha

**Comment by ahmadhasan2k8** [comment]
OK. Then it's solved. Thank you so much.
