### ISSUE TITLE
[WARNING] Not clear if MarchingSquares::edgeMask and MarchingSquares::edges are set correctly

### ISSUE THREAD

**Issue by aaptho** [mkazhdan/PoissonRecon#66]
When building PoissonRecon, my compiler informs me of this message, and I didn't see an issue tracking it. Are there more details on the issue behind this warning?

**Comment by aaptho** [comment]
As pointed out in https://github.com/mkazhdan/PoissonRecon/pull/26, there seems to be a logic error in IsEdgeCorner. `cIndex && 2`, 1, or 4 would always return true, and it seems the intention was to use `&` instead of `&&`. Is it possible this change would fix the issue it's talking about here?

```
bool Cube::IsEdgeCorner( int cIndex , int e )
{
	int o , i , j;
	FactorEdgeIndex( e , o , i , j );
	switch( o )
	{
	case 0: return (cIndex && 2)==(i<<1) && (cIndex && 4)==(j<<2);
	case 1: return (cIndex && 1)==(i<<0) && (cIndex && 4)==(j<<2);
	case 2: return (cIndex && 4)==(i<<2) && (cIndex && 2)==(j<<1);
	default: return false;
	}
}
```

**Comment by mkazhdan** [comment]
Nope. It's a not I left there for myself that I am 99% certain can be ignored.

**Comment by mkazhdan** [comment]
I don't think that code exists in the latest release.

**Comment by aaptho** [comment]
Ah, right you are, it's no longer there. Thanks! Closing.
