### ISSUE TITLE
Increasing samplesPerNode decreases textrure quality

### ISSUE THREAD

**Issue by ahmadhasan2k8** [mkazhdan/PoissonRecon#69]
Hello,

In my point cloud which is cleaned up using several methods and almost noise free I use the samplesPerNode as 1.0. But if I still want some smoothing I can use some other values such as 15 or 20. But this smoothing also affects the color and the texture looks a little blurred. Is there a way in PoissonRecon to smooth the geometry only and leave the color unaffected?

Thanks,
Ahmad

**Comment by mkazhdan** [comment]
Try setting the --pointWeight parameter to a lower value. Maybe even zero.

**Comment by ahmadhasan2k8** [comment]
I tried this. Set --pointWeight to 0 and --samplesPerNode to 1. Still color seems a bit blurred and the geometry was not smooth enough. But when I do --samplesPerNode 10 or 15 it does smooth the geometry but the color seems more blurred even with pointWeight 0. I guess what I am trying to achieve is an effect somewhat similar to moving least squares which is very time consuming even with CUDA implementation.

**Comment by mkazhdan** [comment]
How about setting the point weight to something like 0.5? It's definitely the case that setting the number of samples per node to a larger value would smooth _both_ the color and the geometry. I believe that setting the point weight to a low value should only smooth the geometry.

**Comment by mkazhdan** [comment]
It looks like the amount of smoothing you want can only be obtained by setting the number of samples per node to a higher value. If that oversmooths the data, you can try recompiling the code with DATA_DEGREE defined to be 0 instead of 1. (See the discussion here, ps://github.com/mkazhdan/PoissonRecon/issues/32.)

-- Misha

**Comment by ahmadhasan2k8** [comment]
Thanks. I will try that out.

**Comment by ahmadhasan2k8** [comment]
It works. Thanks a lot.
