### ISSUE TITLE
Fail to build with debug

### ISSUE THREAD

**Issue by xiasun** [mkazhdan/PoissonRecon#72]
Hi,
I am trying to debug this code on Ubuntu 16.04 with GCC 5.4.0. `make all` works well for me but `make debug` dosent't work.
The error log is attached below, can anyone give me some advice? Thank you all !

    Src/PoissonRecon.cpp:621:26:   required from ‘int Execute(int, char**, UIntPack<CSignatures ...>) [with Real = float; SampleData = {}; unsigned int ...FEMSigs = {3u, 3u, 3u}]’
    Src/PoissonRecon.cpp:648:52:   required from ‘int Execute(int, char**) [with unsigned int Dim = 3u; Real = float; SampleData = {}]’
    Src/PoissonRecon.cpp:723:61:   required from here
    Src/Ply.h:253:103: warning: offsetof within non-standard-layout type ‘PlyVertexWithData<float, 3, MultiPointStreamData<float, PointStreamValue<float>, MultiPointStreamData<float> >, float>’ is undefined [-Winvalid-offsetof]
    g++ -o Bin/Linux/PoissonRecon Bin/Linux/PlyFile.o Bin/Linux/PoissonRecon.o -lgomp -lstdc++ -g3
    Bin/Linux/PoissonRecon.o: In function `void FEMTree<3u, float>::finalizeForMultigrid<2u, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<6u, 6u, 6u> >, SparseNodeData<Point<float, 3u>, UIntPack<6u, 6u, 6u> >, FEMTree<3u, float>::DensityEstimator<2u> >(int, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<6u, 6u, 6u> >, SparseNodeData<Point<float, 3u>, UIntPack<6u, 6u, 6u> >*, FEMTree<3u, float>::DensityEstimator<2u>*) [clone ._omp_fn.5]':
    /home/summer/Porjects/PoissonRecon/Src/FEMTree.inl:493: undefined reference to `StaticWindow<RegularTreeNode<3u, FEMTreeNodeData, unsigned short>*, UIntPack<5u, 5u, 5u> >::Size'
    Bin/Linux/PoissonRecon.o: In function `void FEMTree<3u, float>::finalizeForMultigrid<2u, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<7u, 7u, 7u> >, SparseNodeData<Point<float, 3u>, UIntPack<7u, 7u, 7u> >, FEMTree<3u, float>::DensityEstimator<2u> >(int, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<7u, 7u, 7u> >, SparseNodeData<Point<float, 3u>, UIntPack<7u, 7u, 7u> >*, FEMTree<3u, float>::DensityEstimator<2u>*) [clone ._omp_fn.219]':
    /home/summer/Porjects/PoissonRecon/Src/FEMTree.inl:493: undefined reference to `StaticWindow<RegularTreeNode<3u, FEMTreeNodeData, unsigned short>*, UIntPack<5u, 5u, 5u> >::Size'
    Bin/Linux/PoissonRecon.o: In function `void FEMTree<3u, float>::finalizeForMultigrid<2u, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<8u, 8u, 8u> >, SparseNodeData<Point<float, 3u>, UIntPack<8u, 8u, 8u> >, FEMTree<3u, float>::DensityEstimator<2u> >(int, FEMTree<3u, float>::HasNormalDataFunctor<UIntPack<8u, 8u, 8u> >, SparseNodeData<Point<float, 3u>, UIntPack<8u, 8u, 8u> >*, FEMTree<3u, float>::DensityEstimator<2u>*) [clone ._omp_fn.373]':
    /home/summer/Porjects/PoissonRecon/Src/FEMTree.inl:493: undefined reference to `StaticWindow<RegularTreeNode<3u, FEMTreeNodeData, unsigned short>*, UIntPack<5u, 5u, 5u> >::Size'
    collect2: error: ld returned 1 exit status
    Makefile:141: recipe for target 'Bin/Linux/PoissonRecon' failed
    make: *** [Bin/Linux/PoissonRecon] Error 1

**Comment by dakotabenjamin** [comment]
I get this error on both `all` and 'debug`, as well as when running individual targets. I am on Ubuntu 18.04 with gcc version 7.3.0

**Comment by mkazhdan** [comment]
Apologies. I don't believe I have ever tried compiling in debug mode. I'll try to take a look. 

-- Misha

**Comment by ahmadhasan2k8** [comment]
This issue is similar to #53 .

And for ubuntu 18.04 gcc version 7.3.0 and poisson recon latest, release builds on my end without problem.

**Comment by xiasun** [comment]
@dakotabenjamin Yes building failed for all target with code from zip. For this issue, I was fetching the code from this git repo, and only `make debug` failed then, everything else worked well.

**Comment by mkazhdan** [comment]
I have just pushed what I hope is a fix.
It appears that gcc (in DEBUG mode), was not happy with the definition of "StaticWindow::Size" inside the "StaticWindow" class.
Moving the definition outside of the class declaration seems to resolve the problem. (See the recently pushed Window.h file, around lines 307, 326, 335, and 350.)

**Comment by xiasun** [comment]
Thank you @mkazhdan ! I can work it with debug now, thank you for your great code.
