### ISSUE TITLE
PoissonRecon: `USE_DOUBLE` definition is probably not considered

### ISSUE THREAD

**Issue by romanc** [mkazhdan/PoissonRecon#77]
In `int main( int argc , char* argv[] )` of `PoissonRecon.cpp`, line 706ff, the type `Real` is defined either as `double` or `float` depending on `USE_DOUBLE`. However, in lines 718f and 722f, the template `Execute` is instantiated with `DefaultFloatType` and `float` repsectively. I think these should be changed to `Real` to actually support double precision.

**Comment by mkazhdan** [comment]
You are correct. The "USE_DOUBLE" macro is left-over from my development code that I had meant to pull out. And, as you probably noticed, the code doesn't look like it will compile if one defines "FAST_COMPILE". I'll make the change shortly and push it back to the repo.

**Comment by mkazhdan** [comment]
Code has been modified.

**Comment by romanc** [comment]
Commit a2a1949 fixes the issue. Thanks for the quick fix.
