### ISSUE TITLE
Fail to build under Ubuntu 14.04 with GCC 4.8

### ISSUE THREAD

**Issue by xiasun** [mkazhdan/PoissonRecon#78]
System: Ubuntu 14.04 LTS
Compiler: GCC 4.8

Hello Professor Kazhdan, I was trying to build PoissonRecon within Ubuntu 14.04, and it shows error log below. It says this is a bug of GCC, but could you give me any idea how may I avoid it? Maybe by changing some source code or the makefile?

Thank you so much!

```
mkdir -p Bin/Linux/
g++ -c -o Bin/Linux/PlyFile.o -fopenmp -Wno-deprecated -Wno-write-strings -std=c++11 -O3 -DRELEASE -funroll-loops -ffast-math -g -I. Src/PlyFile.cpp
g++ -c -o Bin/Linux/PoissonRecon.o -fopenmp -Wno-deprecated -Wno-write-strings -std=c++11 -O3 -DRELEASE -funroll-loops -ffast-math -g -I. Src/PoissonRecon.cpp
In file included from Src/FEMTree.h:2604:0,
                 from Src/PoissonRecon.cpp:48:
Src/FEMTree.inl: In instantiation of ‘SparseNodeData<Point<Real, Dim>, UIntPack<Begin ...> > FEMTree<Dim, Real>::setNormalField(UIntPack<Begin ...>, const std::vector<NodeAndPointSample<Dim, Real> >&, const std::vector<Data>&, const FEMTree<Dim, Real>::DensityEstimator<WeightDegree>*, Real&, std::function<Real(Real)>) [with unsigned int ...NormalSigs = {6u, 6u, 6u}; unsigned int DensityDegree = 2u; Data = MultiPointStreamData<float, PointStreamNormal<float, 3u>, MultiPointStreamData<float, PointStreamColor<float> > >; unsigned int Dim = 3u; Real = float]’:
Src/PoissonRecon.cpp:479:45:   required from ‘int Execute(int, char**, UIntPack<CSignatures ...>) [with Real = float; SampleData = {PointStreamColor<float>}; unsigned int ...FEMSigs = {3u, 3u, 3u}]’
Src/PoissonRecon.cpp:648:147:   required from ‘int Execute(int, char**) [with unsigned int Dim = 3u; Real = float; SampleData = {PointStreamColor<float>}]’
Src/PoissonRecon.cpp:722:88:   required from here
Src/FEMTree.inl:356:52: internal compiler error: in tsubst, at cp/pt.c:11895
    if( density ) _pointWeightSum += _splatPointData< true , DensityDegree , Point< Real , Dim > , NormalSigs ... >( *density , p , n , normalField , densityKey , oneKey ? *( (NormalKey*)&densityKey ) : normalKey , 0 , maxDepth , Dim , depthBias ) * sample.weight;
                                                    ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccgF67QU.out file, please attach this to your bugreport.
make: *** [Bin/Linux/PoissonRecon.o] Error 1
```

**Comment by mkazhdan** [comment]
Could you try to change the line that reads:

        if( density ) _pointWeightSum += _splatPointData< true , DensityDegree , Point< Real , Dim > , NormalSigs ... >( *density , p , n , normalField , densityKey , oneKey ? *( (NormalKey*)&densityKey ) : normalKey , 0 , maxDepth , Dim , depthBias ) * sample.weight;

to

if( density )
{
If( oneKey )
_pointWeightSum += _splatPointData< true , DensityDegree , Point< Real , Dim > , NormalSigs ... >( *density , p , n , normalField , densityKey , *( (NormalKey*)&densityKey ) , 0 , maxDepth , Dim , depthBias ) * sample.weight;
else
_pointWeightSum += _splatPointData< true , DensityDegree , Point< Real , Dim > , NormalSigs ... >( *density , p , n , normalField , densityKey , normalKey , 0 , maxDepth , Dim , depthBias ) * sample.weight;
}

 

It could be the case that using the ternary operator makes it harder for the compiler to determine the types of the template parameters.

 

-- Misha

**Comment by xiasun** [comment]
Thank you Misha, I tried to change the conditioin operator as you suggested, but the compiler shows exactly the same error.

**Comment by pisuto** [comment]
so finally, how do you solve this?
i met the same problem.

**Comment by mkazhdan** [comment]
I have just pushed an updated version of the code that should compile under gcc version 4.8.
