### ISSUE TITLE
Missing flag lists for executables

### ISSUE THREAD

**Issue by Jean-Roc** [mkazhdan/PoissonRecon#79]
Hi,

Could you please add back the list of flags that can be use with the executable ? This resource can't be found anymore without checking the README.md previous commits, the usage section does not cover all the possible flags that can be use with PoissonRecon.

Regards,
Jean-Roc Morreale

**Comment by mkazhdan** [comment]
I believe they are still there. You just need to click on "PoissonRecon" to expand them out. 

-- Misha

**Comment by Jean-Roc** [comment]
sorry for the inconvenience, I thought it was only a bullet symbol
