### ISSUE TITLE
PLY Output 

### ISSUE THREAD

**Issue by maniolek** [mkazhdan/PoissonRecon#8]
Hi, 
I'm wondering why faces list at ply output is in binary format. Is it set by default? Can it be saved as ascii?

Input file: http://s000.tinyupload.com/?file_id=66724387703494627365
Output file: http://s000.tinyupload.com/?file_id=08871875982492369292

```
--in C:\dcmtest\dicom_222906.ply --depth 10 --out C:\dcmtest\output_dicom_222906.ply --verbose --pointWeight 0
```

Can you mark some stable version? I'm trying to use it in my master's degree project :)

**Comment by mkazhdan** [comment]
If you add the “--asci” parameter, you should get an output that is no longer in binary.
