### ISSUE TITLE
Converting string constants to char* in PointStreamData.h

### ISSUE THREAD

**Issue by romanc** [mkazhdan/PoissonRecon#80]
Compiling your code with `gcc` (version 5.4.0), I get multiple warnings of the type

```
warning: ISO C++ forbids converting a string constant to `char*` [-Wwrite-strings]
```

The warning is, for example, emitted for [line 122](https://github.com/mkazhdan/PoissonRecon/blob/master/Src/PointStreamData.h#L122) in `PointStreamData.h`, where the string literal `"x"` is assigned to `char* name`, defined in the struct `PlyProperty` (declared in `Ply.h`). While this was valid in `C`, it has been deprecated in `C++03` and is undefined behavior starting with `C++11`. The problem is that string literals such as `"x"` or `"y"` are of type `const char*` in `C++11`.

Maybe it's enough to change the type of `PlyProperty::name` from `char*` to `const char*`, but I'm unsure, if that would still work when reading PLY files. I guess the cleanest solution would be to change it to `std::string`.

**Comment by mkazhdan** [comment]
The problem should be resolved with the latest version (10.04) of the code.
The PLY reading/writing code has been cleaned up to be object-oriented and char*'s have been replaced with std::strings
