### ISSUE TITLE
How to create a MemoryInputPointStreamWithData

### ISSUE THREAD

**Issue by FrankEscobar** [mkazhdan/PoissonRecon#81]
I've tried some naive test without luck.

My intention is to use PoissonRecon in other software I'm just playing around but I prefer to use it as a library to skip writting/reading/writting the file so it could be great to use it with a float* void* or whatever, also I'll be able to provide the 6 important values per vertex (x,y,z,nx,ny,nz).

In lines 418-420 of  PoissonRecon.cpp it uses BinaryInputPointStreamWithData and so to create the pointStream but I didn't manage to create it from memory.

Any tip on this? To be honest I'm just a student and I'm a bit lost with so many typedefs like Data.

Thank you so much in advance!

**Comment by mkazhdan** [comment]
Try using the MemoryInputPointStreamWithData class. It's initialized with memory location of the points/normals.

**Comment by ahmadhasan2k8** [comment]
If you just want to use PoissonRecon as a library then you can use my fork. Although, I did not try to skip I/O because it never caused any problem. There might be other forks who does it. You might wanna look into different forks.

**Comment by FrankEscobar** [comment]
@mkazhdan I did it but unfortunatly I don't know how to initialize the Data paramareter
		std::pair< Point< Real, Dim >, cosa > points[8];
I mean I don't know what should I provide for "cosa" parameter

@ahmadhasan2k8 I prefer to skip I/O to avoid writting to disk dealing with fileformat definitions and so.

**Comment by mkazhdan** [comment]
I'm not sure I follow. What is cosa? It should be an array of pairs of Point< Real , Dim > object. (The first point gives the position. The second gives the normal.)

**Comment by MotivaCG** [comment]
@mkazhdan that was my question :S 
I tried lots of posibilities like:
std::pair< Point< Real, Dim >, Point< Real, Dim > > points[8];
std::pair< Point< Real, Dim >, Real > points[8];

But I didn't find nothing that match the Data type yet.

**Comment by FrankEscobar** [comment]
@mkazhdan that was my question :S
I tried lots of posibilities like:
std::pair< Point< Real, Dim >, Point< Real, Dim > > points[8];
std::pair< Point< Real, Dim >, Real > points[8];

But I didn't find nothing that match the Data type yet.

**Comment by mkazhdan** [comment]
What is TotalPointStreamData defined as in your code (i.e. in the second line)?

**Comment by FrankEscobar** [comment]
Oh you are right! 
`std::pair< Point< Real, Dim >, TotalPointSampleData > points[8];`

Seems to work unfortunatly my naive approach:

`
		for (int i = 0; i < 8; i++)
		{
			points[i].first[3] = points[i].first[4] = 0;
			switch (i)
			{
			case 0:
				points[i].first[0] = -10;
				points[i].first[1] = -5;
				points[i].first[2] = 0;
				points[i].first[5] = -1.5708;
				points[i].first[6] = -1.5708;
				points[i].first[7] = -1.5708;
				break;
			case 1:
				points[i].first[0] = -10;
				points[i].first[1] = 5;
				points[i].first[2] = 0;
				points[i].first[5] = -1.5708;
				points[i].first[6] = 1.5708;
				points[i].first[7] = -1.5708;
				break;
			case 2:
				points[i].first[0] = 10;
				points[i].first[1] = 5;
				points[i].first[2] = 0;
				points[i].first[5] = 1.5708;
				points[i].first[6] = 1.5708;
				points[i].first[7] = -1.5708;
				break;
			case 3:
				points[i].first[0] = 10;
				points[i].first[1] = -5;
				points[i].first[2] = 0;
				points[i].first[5] = 1.5708;
				points[i].first[6] = -1.5708;
				points[i].first[7] = -1.5708;
				break;

			case 4:
				points[i].first[0] = -10;
				points[i].first[1] = -5;
				points[i].first[2] = 30;
				points[i].first[5] = -1.5708;
				points[i].first[6] = -1.5708;
				points[i].first[7] = 1.5708;
				break;
			case 5:
				points[i].first[0] = -10;
				points[i].first[1] = 5;
				points[i].first[2] = 30;
				points[i].first[5] = -1.5708;
				points[i].first[6] = 1.5708;
				points[i].first[7] = 1.5708;
				break;
			case 6:
				points[i].first[0] = 10;
				points[i].first[1] = 5;
				points[i].first[2] = 30;
				points[i].first[5] = 1.5708;
				points[i].first[6] = 1.5708;
				points[i].first[7] = 1.5708;
				break;
			case 7:
				points[i].first[0] = 10;
				points[i].first[1] = -5;
				points[i].first[2] = 30;
				points[i].first[5] = 1.5708;
				points[i].first[6] = -1.5708;
				points[i].first[7] = 1.5708;
			}
		}
		pointStream = new MemoryInputPointStreamWithData< Real, Dim, TotalPointSampleData >(8, &points[0]);`

Does not work yet

Btw I'm trying to bypass 
`if (!strcasecmp(ext, "bnpts")) pointStream = new BinaryInputPointStreamWithData< Real, Dim, TotalPointSampleData >(In.value, TotalPointSampleData::ReadBinary);`
in PoissonRecon.cpp
