### ISSUE TITLE
Not working with my ply file

### ISSUE THREAD

**Issue by meghna1301** [mkazhdan/PoissonRecon#87]
Hi,
I was trying to use PoissonRecon.exe, version 10.04, to create mesh for my Point cloud.  
However, I am getting following error:
[WARNING] Found bad data: 6677

Ply file used:
[cloud-2.zip](https://github.com/mkazhdan/PoissonRecon/files/2550929/cloud-2.zip)

Command used: 
PoissonRecon.exe --in cloud-2.ply --out try.ply

Is there anything wrong with the ply file ? I can use it with PCL and it has both color and normals.
Thanks so much for your help.

**Comment by mkazhdan** [comment]
Your normals are NaNs

**Comment by meghna1301** [comment]
Thanks so much. I added normals using PCL and then created mesh using PoissonRecon and Dirichlet boundary constraints (bType = 2). It is working well with that.
Thanks.
