### ISSUE TITLE
-aRatio with SurfaceTrimmer

### ISSUE THREAD

**Issue by lulu1315** [mkazhdan/PoissonRecon#9]
hello
I'm trying to use the aRatio parameter to get rid of "blobs" around my reconstruction.
but actually I'm getting the opposite of what I intuitively thought would happened , ie the results is like keeping the blobs only.is there a way to remove the little disconnected area and keep the surface ?

commands:
SurfaceTrimmer --in MVE/Poisson-L2-node1.ply --trim 5 --out MVE/Poisson-L2-trim5
![densecloud1](https://cloud.githubusercontent.com/assets/13677315/11719897/286ea738-9f5d-11e5-827f-4402a090c922.jpg)

SurfaceTrimmer --in MVE/Poisson-L2-node1.ply --out MVE/Poisson-L2-trim5-aRatio1 --aRatio .5
![densecloud2](https://cloud.githubusercontent.com/assets/13677315/11719907/38b1edb2-9f5d-11e5-9a92-0037644ca5aa.jpg)

thanks in advance

**Comment by mkazhdan** [comment]
Hi Luc,

Sorry. I think there is some confusion about what the --aRatio flag does. 

It does _not_ remove small disconnected components. If you want that, you could use something like the functionality in MeshLab. 

What it does is the following:
In general, the surface trimming code removes parts of the surface in regions of low sampling density. But, depending on how you define "low", this could result in the removal of many tiny components (e.g. if most of the surface is just above the cutoff threshold).  This had the undesirable effect of making the trimmed surface look like Swiss cheese. So, with the --aRatio flag, you can tell the trimmer to keep those tiny islands that are just below the cutoff threshold. 

As you observed, this has the property that the larger the --aRatio flag, the more surface area is returned. (And if the parameter is set to 1, nothing will get trimmed off.)

-- misha

-----Original Message-----

**Comment by lulu1315** [comment]
ah.ok thanks for the explanation.I will investigate with meshlab.
thank you very much
luc
