### ISSUE TITLE
Unable to compile on VS2017: "CS2244: Unable to match function definition to an existing declaration"

### ISSUE THREAD

**Issue by DanAndersen** [mkazhdan/PoissonRecon#91]
I am attempting to compile version 10.05 from source on VS2017, but am encountering the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2244	'RegularTreeNode<Dim,NodeData,DepthAndOffsetType>::ConstNeighborKey<UIntPack<Begin...>,UIntPack<__Values...>>::operator =': unable to match function definition to an existing declaration	PoissonRecon	d:\dev\holo-snap\adaptivesolvers\src\regulartree.inl	630	
```

It appears to be related to the following code in RegularTree.inl:
```
typename RegularTreeNode< Dim , NodeData , DepthAndOffsetType >::template ConstNeighborKey< UIntPack< LeftRadii ... > , UIntPack< RightRadii ... > >& RegularTreeNode< Dim , NodeData , DepthAndOffsetType >::ConstNeighborKey< UIntPack< LeftRadii ... > , UIntPack< RightRadii ... > >::operator = ( const ConstNeighborKey& key )
{
	set( key._depth );
	for( int d=0 ; d<=_depth ; d++ ) memcpy( &neighbors[d] , &key.neighbors[d] , sizeof( ConstNeighbors< UIntPack< ( LeftRadii + RightRadii + 1 ) ... > > ) );
}
```

**Comment by mkazhdan** [comment]
What version of MSVC 2017 are you using?
There was an earlier post about a compilation problem that was resolved when VS2017 was updated to version 1.9.3.

**Comment by DanAndersen** [comment]
I'm currently on version 15.6.*. I'll try the upgrade and will see if it works. Thanks!

**Comment by DanAndersen** [comment]
Update: updating to the latest version of VS2017 solved the issue. Thanks!

**Comment by VVingerfly** [comment]
Another solution, move the implementation from [RegularTree.inl](https://github.com/mkazhdan/PoissonRecon/blob/master/Src/RegularTree.inl#L741) to [RegularTree.h](https://github.com/mkazhdan/PoissonRecon/blob/master/Src/RegularTree.h#L344).
