### ISSUE TITLE
Request to add support for CMake build system, and to make this project more friendly as a dependency of other projects

### ISSUE THREAD

**Issue by daniel-packard** [mkazhdan/PoissonRecon#97]
Hi, I'm reaching out to see if there's any interest from the project owner/maintainer to add support for CMake, and to structure the code in this repo so it's easier to reuse for 3rd parties (e.g. by structuring the core functionality as a library).

I'm asking this because I've noticed at least two major ports of this surface reconstruction work, and the drift between them makes it hard for everyone to benefit from core improvements:
* PCL: https://github.com/PointCloudLibrary/pcl/tree/master/surface/include/pcl/surface/3rdparty/poisson4
* VTK: https://github.com/daviddoria/PoissonReconstruction

If there's interest, I'd be happy to make an effort to help out.

**Comment by mkazhdan** [comment]
Never having worked with cmake, I'm not sure what's involved. Can you provide a description of the kinds of changes that would be required to make the source code cmake'able?

**Comment by daniel-packard** [comment]
Hi @mkazhdan - I think the changes could be made incrementally

First - without making any changes to your code, you can add a CMakeLists.txt. This would provide a way for people to generate "makefiles" using the build system of their choice (make, msbuild, ninja, etc). Eventually you can stop maintaining separate .sln and makefiles because they would be generated by CMake. 

In the longer term, I think there is demand to make your code easier to consume as a library (instead of as command line executeables). This would involve  a reorganization of your codebase such that it can be installed in something like the following structure

e.g. on windows:
```
C:\Program Files\PoissonRecon\
     \include\
         { all public header files installed here } 
     \bin\
          { all executables and dlls installed here } 
      \lib\
          { all static lib files installed here }
      \share\
          \cmake\
            { all cmake config goes here - let's other people include your project as a dependency }
```

This would take some effort to separate out public headers, and organize your core functionality into a library. Once your code is organized as a library (or multiple libraries), you can link against it to include the core functionality in your executables (as opposed to bringing the functionality in using `#include` with `.inl` files).

**Comment by daniel-packard** [comment]
The benefit of separating your core functionality into a library is that other people will be able to use your library to build other applications without disecting/copying/pasting your code into their projects (which causes feature drift, and can be for them to update in the future)
